const {test}=require('node:test'),assert=require('node:assert/strict');const maps=require('../world-editor.js'),{createEngine}=require('../multiplayer/engine.cjs'),{LobbyService}=require('../multiplayer/lobbies.cjs');
const members=[{name:'One',faction:'human',color:'#53c9eb',team:1},{name:'Ally',faction:'horde',color:'#ef685a',team:1},{name:'Enemy',faction:'covenant',color:'#b88af0',team:2}];
function meadow(){return{version:1,size:4000,name:'Test',starts:[{x:400,y:400},{x:3600,y:3600}],resources:[],mountains:[],plateaus:[],rivers:[]};}
test('map imports reject oversized or out-of-bounds objects and unsafe terrain',()=>{const m=meadow();assert.equal(maps.validate(m).errors.length,0);m.starts[0].x=-1;assert.match(maps.validate(m).errors[0],/outside/);m.starts[0].x=400;m.resources=Array(1201).fill({x:1000,y:1000,type:'wood'});assert.match(maps.validate(m).errors[0],/too many/);});
test('map editor detects disconnected starts and accepts a bridge crossing',()=>{const m=meadow();m.mountains=[{x:2000,y:40,half:120,height:60},{x:2000,y:3960,half:120,height:60}];m.rivers=[{points:Array.from({length:164},(_,i)=>({x:2000,y:40+i*24})),width:90,bridges:[]}];assert(maps.validate(m).errors.some(e=>e.includes('disconnected')));m.rivers[0].bridges=[2000];assert.equal(maps.validate(m).errors.length,0);});
test('allies cannot be attacked, share vision and win together',()=>{const engine=createEngine(members),s=engine.state;s.count=0;const u=s.entities.find(e=>e.owner===0&&!e.building),ally=s.entities.find(e=>e.owner===1&&!e.building);assert.equal(engine.apply(0,{kind:'order',id:u.id,order:{kind:'attack',targetId:ally.id}}),'Invalid target.');assert(engine.snapshot(0).entities.some(e=>e.owner===1));s.entities=s.entities.filter(e=>e.owner!==2);engine.step(.05);assert.equal(s.ended,true);assert.equal(engine.snapshot(1).ended,true);});
test('artillery deployment cancels on movement and rejects non-artillery',()=>{const engine=createEngine(members),s=engine.state;s.count=0;const u=s.entities.find(e=>e.owner===0&&!e.building);assert.equal(engine.apply(0,{kind:'deploy',id:u.id}),'Select artillery.');u.type='siege';assert.equal(engine.apply(0,{kind:'deploy',id:u.id}),null);assert.equal(u.deployed,true);assert.equal(engine.apply(0,{kind:'order',id:u.id,order:{kind:'move',x:1000,y:1000}}),null);assert.equal(u.deployed,false);});
test('spectators may join running protected lobbies without leaking host fog or issuing orders',()=>{const service=new LobbyService(),h=service.create({...members[0],map:'highlands',passcode:'private'});service.act(h.room.code,h.token,{action:'bot',...members[2],difficulty:'hard'});service.act(h.room.code,h.token,{action:'start'});assert.throws(()=>service.join(h.room.code,{...members[1],spectator:true,passcode:'wrong'}),/passcode/);const v=service.join(h.room.code,{...members[1],spectator:true,passcode:'private'});const before=service.poll(h.room.code,h.token).snapshot.seen;const view=service.poll(h.room.code,v.token);assert.equal(view.snapshot.spectating,true);assert(view.snapshot.visible.every(Boolean));assert.deepEqual(service.poll(h.room.code,h.token).snapshot.seen,before);assert.throws(()=>service.act(h.room.code,v.token,{action:'command',command:{kind:'deploy',id:1}}),/Spectators/);assert(!JSON.stringify(view).includes(h.token));});
test('disconnected multiplayer seats survive four minutes and expire after five',()=>{const service=new LobbyService(),h=service.create({...members[0],map:'highlands'});service.act(h.room.code,h.token,{action:'bot',...members[2],difficulty:'hard'});service.act(h.room.code,h.token,{action:'start'});const room=service.get(h.room.code);room.members[0].lastSeen=Date.now()-240000;service.step();assert.equal(room.members[0].left,undefined);room.members[0].lastSeen=Date.now()-300001;service.step();assert.equal(room.members[0].left,true);});
test('destroyed bridges close ground routes and collectors can repair them',()=>{const engine=createEngine(members,'frontier'),s=engine.state;s.count=0;s.posts=[];const b=s.siegeBridges[0];assert(b);const u=s.entities.find(e=>e.owner===0&&!e.building);u.type='siege';u.x=b.x-150;u.y=b.y;u.cool=0;b.hp=1;assert.equal(engine.apply(0,{kind:'bridge',id:u.id,bridgeId:b.id}),null);engine.step(.05);assert.equal(b.hp,0);assert(!s.rivers[b.river].bridges.includes(b.y));u.type='worker';u.x=b.x-s.rivers[b.river].width/2-25;u.y=b.y;b.hp=899;assert.equal(engine.apply(0,{kind:'bridge',id:u.id,bridgeId:b.id,repair:true}),null);engine.step(.05);assert.equal(b.hp,900);assert(s.rivers[b.river].bridges.includes(b.y));});
test('formation followers regroup at their final slots after the leader stops',()=>{const engine=createEngine(members),s=engine.state;s.count=0;s.resources=[];s.mountains=[];s.plateaus=[];s.rivers=[];s.posts=[];const own=s.entities.filter(e=>e.owner===0&&!e.building);const leader=own[0],follower=own[1];leader.x=500;leader.y=500;follower.x=450;follower.y=450;for(const e of [leader,follower])assert.equal(engine.apply(0,{kind:'order',id:e.id,order:{kind:'move',x:700,y:500,formation:{key:'squad',leaderId:leader.id,dx:e===leader?0:-45,dy:e===leader?0:45,finalX:e===leader?700:655,finalY:e===leader?500:545}}}),null);engine.step(.05);assert.equal(follower.order.formation.traveling,true);leader.x=700;leader.y=500;leader.order={kind:'hold'};engine.step(.05);assert.equal(follower.order.x,655);assert.equal(follower.order.y,545);assert.equal(follower.order.formation.traveling,false);});
