const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');const {createEngine}=require('../multiplayer/engine.cjs'),{LobbyService}=require('../multiplayer/lobbies.cjs'),{MatchStore}=require('../multiplayer/persistence.cjs');
const players=[{name:'You',faction:'human',color:'#53c9eb',ai:false},{name:'Them',faction:'horde',color:'#ef685a',ai:false}];
function battle(){const engine=createEngine(players),s=engine.state;s.count=0;s.posts=[];s.resources=[];s.mountains=[];s.rivers=[];s.plateaus=[];s.ai=999;const u=s.entities.find(e=>e.owner===0&&!e.building);u.type='melee';u.x=700;u.y=700;return{engine,s,u};}
test('patrol alternates endpoints, guard follows an ally, and Stop cancels persistent orders',()=>{const {engine,s,u}=battle();assert.equal(engine.apply(0,{kind:'tactical',mode:'patrol',id:u.id,x:950,y:700}),null);u.x=950;engine.step(.05);assert.equal(u.order.x,700);assert.equal(u.tactical.destination,'a');const ally=s.entities.find(e=>e.owner===0&&e!==u&&!e.building);ally.x=800;ally.y=700;assert.equal(engine.apply(0,{kind:'tactical',mode:'guard',id:u.id,targetId:ally.id}),null);ally.x=1100;engine.step(.05);assert(u.order.x>900);assert.equal(engine.apply(0,{kind:'order',id:u.id,order:{kind:'stop'}}),null);assert.equal(u.tactical,null);assert.equal(u.order.kind,'stop');});
test('retreat overrides attacks without consuming resources and guard rejects enemies',()=>{const {engine,s,u}=battle(),enemy=s.entities.find(e=>e.owner===1&&!e.building),gold=s.players[0].gold;assert.equal(engine.apply(0,{kind:'tactical',mode:'guard',id:u.id,targetId:enemy.id}),'Choose a visible allied unit.');u.order={kind:'attack',target:enemy};assert.equal(engine.apply(0,{kind:'tactical',mode:'retreat',id:u.id}),null);assert.equal(u.order.kind,'move');assert(Number.isFinite(u.order.x)&&Math.hypot(u.order.x-u.x,u.order.y-u.y)>30);assert.equal(s.players[0].gold,gold);});
test('spending tracks refunds, losses resolve once, and economy history records actual army value',()=>{const {engine,s,u}=battle(),base=s.entities.find(e=>e.owner===0&&e.type==='base');s.players[0].gold=s.players[0].wood=1000;assert.equal(engine.apply(0,{kind:'train',id:base.id,type:'worker'}),null);assert.equal(s.players[0].stats.goldSpent,50);assert.equal(engine.apply(0,{kind:'cancel',id:base.id,jobId:base.queue[0].id}),null);assert.equal(s.players[0].stats.goldSpent,0);u.hp=0;u.lastDamageOwner=1;engine.step(.05);assert.equal(s.players[0].stats.unitsLost,1);assert.equal(s.players[1].stats.unitsKilled,1);assert(s.ruins.some(r=>r.id===u.id));engine.step(.05);assert.equal(s.players[0].stats.unitsLost,1);assert.equal(s.players[0].stats.armyValue,0);assert(s.players[0].stats.economy.length);});
test('public discovery exposes only opted-in unprotected waiting lobbies and no credentials',()=>{const service=new LobbyService(),open=service.create({...players[0],map:'highlands',public:true}),hidden=service.create({...players[1],map:'frontier'}),privateRoom=service.create({...players[0],map:'canyon',public:true,passcode:'secret-code'});const listing=service.list();assert.equal(listing.length,1);assert.equal(listing[0].code,open.room.code);assert(!JSON.stringify(listing).includes(open.token));assert(!JSON.stringify(listing).includes(privateRoom.room.code));assert(!JSON.stringify(listing).includes(hidden.room.code));});
test('atomic server recovery restores passcodes, session credentials, fog and order target references',async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'kaw-recovery-'));try{const service=new LobbyService(),h=service.create({...players[0],map:'frontier',passcode:'keep-private'}),g=service.join(h.room.code,{...players[1],passcode:'keep-private'});service.act(h.room.code,g.token,{action:'profile',...players[1],ready:true});service.act(h.room.code,h.token,{action:'start'});const original=service.get(h.room.code);original.engine.state.count=0;const worker=original.engine.state.entities.find(e=>e.owner===0&&!e.building),resource=original.engine.state.resources.find(r=>r.type==='gold');worker.order={kind:'gather',target:resource};const before=original.engine.snapshot(0).seen;const store=new MatchStore(dir);assert(await store.save(service));const recovered=new LobbyService();assert.equal(new MatchStore(dir).load(recovered),1);const room=recovered.get(h.room.code);assert.equal(room.recovering,true);const t=room.engine.state.time;recovered.step();assert.equal(room.engine.state.time,t);const view=recovered.poll(h.room.code,h.token);assert.equal(room.recovering,false);assert.deepEqual(Array.from(view.snapshot.seen),Array.from(before));const restoredWorker=room.engine.state.entities.find(e=>e.id===worker.id);assert(room.engine.state.resources.includes(restoredWorker.order.target));assert.throws(()=>recovered.join(h.room.code,{...players[0],spectator:true,passcode:'wrong'}),/passcode/);assert.equal(recovered.poll(h.room.code,g.token).you,g.room.members[1].id);if(process.platform!=='win32')assert.equal(fs.statSync(path.join(dir,'matches.json')).mode&0o777,0o600);}finally{fs.rmSync(dir,{recursive:true,force:true});}});
test('HTTP public discovery and restart recovery preserve authenticated rooms without exposing checkpoint files',async()=>{
 const {createServer}=require('../server.js'),dir=fs.mkdtempSync(path.join(os.tmpdir(),'kaw-http-recovery-'));let server;
 const listen=async()=>{server=createServer({dataDir:dir,tick:false});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));return 'http://127.0.0.1:'+server.address().port;};
 const close=()=>new Promise(resolve=>server.close(resolve));
 try{let url=await listen();const response=await fetch(url+'/api/lobbies',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...players[0],public:true,map:'frontier'})});assert.equal(response.status,201);const created=await response.json();const listing=await(await fetch(url+'/api/lobbies')).json();assert.equal(listing.lobbies[0].code,created.room.code);assert(!JSON.stringify(listing).includes(created.token));assert.equal((await fetch(url+'/.kaw-data/matches.json')).status,404);await server.checkpoint();await close();url=await listen();const recovered=await fetch(url+'/api/lobbies/'+created.room.code,{headers:{authorization:'Bearer '+created.token}});assert.equal(recovered.status,200);assert.equal((await recovered.json()).room.code,created.room.code);assert.equal((await(await fetch(url+'/api/lobbies')).json()).lobbies[0].code,created.room.code);
 }finally{if(server?.listening)await close();fs.rmSync(dir,{recursive:true,force:true});}
});
