'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const {createEngine}=require('../multiplayer/engine.cjs'),{LobbyService}=require('../multiplayer/lobbies.cjs');
const players=[{name:'A',faction:'human',color:'#53c9eb',ai:false},{name:'B',faction:'horde',color:'#ef685a',ai:false}];
function battle(rules){const engine=createEngine(players,'highlands',rules),s=engine.state;s.count=0;s.ai=999;s.posts=[];s.resources=[];s.mountains=[];s.rivers=[];s.plateaus=[];s.wallVersion++;return{engine,s};}
test('span visibility exactly matches circular cell tests and never reveals enemies outside sight',()=>{const {engine,s}=battle();const source=s.entities.find(e=>e.owner===0&&!e.building);source.x=1732.4;source.y=1693.8;source.type='scout';source.surveyUntil=10;const expected=new Uint8Array(10000);for(const e of s.entities.filter(e=>e.owner===0&&e.hp>0)){const r=e.building?260:e.type==='scout'?650:230;for(let y=0;y<100;y++)for(let x=0;x<100;x++)if(Math.hypot(x*40+20-e.x,y*40+20-e.y)<r)expected[y*100+x]=1;}const actual=engine.snapshot(0);assert.deepEqual(Array.from(actual.visible),Array.from(expected));assert(actual.entities.every(e=>e.owner===0||expected[Math.floor(e.y/40)*100+Math.floor(e.x/40)]));});
test('skirmish resources and speed are authoritative; selected supply limits enforce training',()=>{const {engine,s}=battle({resources:600,speed:1.5,supply:50,victory:'strongholds'});assert.equal(s.players[0].gold,600);engine.step(.05);assert(Math.abs(s.time-.075)<1e-8);const base=s.entities.find(e=>e.owner===0&&e.type==='base'),worker=s.entities.find(e=>e.owner===0&&!e.building);for(let i=0;i<10;i++)s.entities.push({...base,id:800+i,type:'house',queue:[]});for(let i=0;i<46;i++)s.entities.push({...worker,id:900+i,type:'melee',x:1000+i*30,queue:[]});assert.match(engine.apply(0,{kind:'train',id:base.id,type:'worker'}),/Supply full/);});
test('elimination continues after a Stronghold falls, then ends only after the last opposing entity dies',()=>{const {engine,s}=battle({victory:'elimination'});s.entities.find(e=>e.owner===1&&e.type==='base').hp=0;engine.step(.05);assert.equal(s.ended,false);assert.equal(engine.snapshot(1).ended,false);for(const e of s.entities)if(e.owner===1)e.hp=0;engine.step(.05);assert.equal(s.ended,true);assert.equal(engine.snapshot(0).result,'VICTORY');assert.equal(engine.snapshot(1).result,'DEFEAT');});
test('domination accumulates one allied hold and guest winners are correctly mapped',()=>{const teamPlayers=players.map((p,i)=>({...p,team:i?2:1}));teamPlayers.push({name:'Ally',faction:'covenant',color:'#b88af0',ai:false,team:1});const engine=createEngine(teamPlayers,'frontier',{victory:'domination'}),s=engine.state;s.count=0;s.ai=999;s.posts=[{id:1,x:1500,y:1300,owner:0},{id:2,x:2500,y:2700,owner:2}];s.domination={team:'team:1',held:119.99};engine.step(.05);assert.equal(s.ended,true);assert.equal(engine.snapshot(2).result,'VICTORY');assert.equal(engine.snapshot(1).result,'DEFEAT');});
test('ready checks invalidate guest readiness; host rule changes are validated and host-only',()=>{const service=new LobbyService(),h=service.create({...players[0],map:'frontier'}),g=service.join(h.room.code,players[1]);service.act(h.room.code,g.token,{action:'profile',...players[1],ready:true});service.act(h.room.code,h.token,{action:'readyCheck'});const room=service.get(h.room.code);assert(room.readyCheckDeadline>Date.now());assert.equal(room.members[1].ready,false);assert.throws(()=>service.act(h.room.code,h.token,{action:'start'}),/ready/);assert.throws(()=>service.act(h.room.code,g.token,{action:'rules',rules:{resources:600}}),/host/);assert.throws(()=>service.act(h.room.code,h.token,{action:'rules',rules:{supply:999}}),/supported/);service.act(h.room.code,h.token,{action:'rules',rules:{resources:300,supply:100,speed:.75,victory:'elimination'},aiTakeover:true});assert.equal(room.rules.resources,300);assert.equal(room.aiTakeover,true);});
test('optional AI takeover commands a disconnected host and immediately returns control on reconnect',()=>{const service=new LobbyService(),h=service.create({...players[0],map:'frontier',aiTakeover:true}),g=service.join(h.room.code,players[1]);service.act(h.room.code,g.token,{action:'profile',...players[1],ready:true});service.act(h.room.code,h.token,{action:'start'});const room=service.get(h.room.code),host=room.members[0];room.engine.state.count=0;host.lastSeen=Date.now()-20000;service.step();assert.equal(host.aiControl,true);assert.equal(room.engine.state.players[0].ai,true);assert(room.engine.state.entities.some(e=>e.owner===0&&e.type==='worker'&&e.order));const connected=service.poll(h.room.code,h.token);assert.equal(host.aiControl,false);assert.equal(room.engine.state.players[0].ai,false);assert(connected.room.members[0].connected);});
test('takeover is disabled by default and unit production/loss telemetry excludes initial troops',()=>{const service=new LobbyService(),h=service.create({...players[0],map:'frontier'}),g=service.join(h.room.code,players[1]);service.act(h.room.code,g.token,{action:'profile',...players[1],ready:true});service.act(h.room.code,h.token,{action:'start'});const room=service.get(h.room.code),s=room.engine.state;s.count=0;s.ai=999;room.members[0].lastSeen=Date.now()-20000;service.step();assert.equal(s.players[0].ai,false);assert.equal(Object.keys(s.players[0].stats.trainedByType).length,0);const base=s.entities.find(e=>e.owner===0&&e.type==='base');s.players[0].gold=500;room.engine.apply(0,{kind:'train',id:base.id,type:'worker'});base.queue[0].left=0;room.engine.step(.05);assert.equal(s.players[0].stats.trainedByType.worker,1);const worker=s.entities.find(e=>e.owner===0&&e.type==='worker');worker.hp=0;room.engine.step(.05);assert.equal(s.players[0].stats.lostByType.worker,1);});
for(const map of ['highlands','frontier','canyon'])test(map+' has fair resources, connected starts and two defensible expansions',()=>{const engine=createEngine(players,map),s=engine.state;assert.deepEqual(Array.from(s.mapHealth.errors),[]);assert.deepEqual(Array.from(s.mapHealth.warnings),[]);assert.equal(s.resources.filter(r=>r.expansion).length,2);assert.equal(s.rivers[0].bridges.length,4);for(const [x,y]of s.spawns){assert(s.resources.some(r=>r.type==='gold'&&Math.hypot(r.x-x,r.y-y)<450));assert.equal(s.resources.filter(r=>r.type==='wood'&&Math.hypot(r.x-x,r.y-y)<450).length,16);}});
test('compiled match closures isolate entities, resources, fog and timers between simultaneous rooms',()=>{const a=createEngine(players,'highlands',{resources:600}),b=createEngine(players,'canyon',{resources:100});const bs=JSON.stringify(b.checkpoint());a.state.count=0;a.state.players[0].gold=999;a.state.entities[0].hp=1;a.state.resources[0].amount=0;a.step(.1);a.snapshot(1);assert.equal(JSON.stringify(b.checkpoint()),bs);assert.notEqual(a.state,b.state);assert.notEqual(a.state.entities[0],b.state.entities[0]);assert.notEqual(a.visions[0].seen,b.visions[0].seen);assert.equal(b.state.players[0].gold,100);});
