const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');
function game(){const elements={};const el=id=>elements[id]??=( {value:({color:'#53c9eb',c1:'#ef685a',c2:'#b88af0',ai1:'horde',ai2:'off'})[id],style:{},classList:{toggle(){}},clientWidth:1200,clientHeight:650,getContext(){return{};},appendChild(){},getBoundingClientRect(){return{left:0,top:0};}});const c=vm.createContext({document:{getElementById:el,querySelectorAll(){return[];},createElement(){return el(Math.random());}},window:{addEventListener(){}},requestAnimationFrame(){},alert(){},console});vm.runInContext(fs.readFileSync(require.resolve('../game.js'),'utf8'),c);vm.runInContext('start();state.count=0;',c);return code=>vm.runInContext(code,c);}
test('starts with two factions and hides enemy territory',()=>{const run=game();assert.equal(run('state.players.length'),2);assert.equal(run('state.entities.filter(e=>e.owner===0&&e.type==="worker").length'),4);assert.equal(run('visible(2080,2000)'),false);assert.equal(run('visible(250,300)'),true);});
test('collectors harvest both resources and upgrades increase yield',()=>{const r=game();assert.ok(r(`(()=>{const w=state.entities[1],p=state.players[0];for(const type of ['gold','wood']){const t=state.resources.find(t=>t.type===type);w.x=t.x;w.y=t.y;w.order={kind:'gather',target:t};const before=p[type];tick(1);if(p[type]<=before)return false;}const t=state.resources.find(t=>t.type==='gold');w.x=t.x;w.y=t.y;w.order={kind:'gather',target:t};p.gather=1;const before=p.gold;tick(1);return p.gold-before>11;})()`));});
test('production consumes resources and completes real units',()=>{const r=game();assert.equal(r(`(()=>{const b=state.entities[0];train(b,'worker');tick(5.1);return state.entities.filter(e=>e.owner===0&&e.type==='worker').length;})()`),5);});
test('hero aura changes damage only inside its radius',()=>{const r=game();assert.ok(r(`(()=>{state.entities=[];entity('base',0,100,100,true);entity('base',1,2100,2100,true);state.ai=999;const a=entity('melee',1,500,500),t=entity('melee',0,510,500),h=entity('hero',0,520,500);h.order={kind:'hold'};h.cool=999;t.cool=999;tick(.01);const reduced=t.max-t.hp;h.x=1000;a.cool=0;tick(.01);const normal=t.max-t.hp-reduced;return reduced<normal&&Math.abs(reduced-normal*.7)<.001;})()`));});
test('destroying opposing stronghold wins',()=>{const r=game();assert.equal(r("state.entities.find(e=>e.owner===1&&e.type==='base').hp=0;tick(.01);state.ended"),true);});
test('pointer selection and destination command move the selected collector',()=>{const r=game();assert.ok(r(`(()=>{canvas.onpointerdown({button:0,clientX:190,clientY:385});canvas.onpointerup({button:0,clientX:190,clientY:385});if(selected.length!==1)return false;commandMode='command';canvas.onpointerdown({button:0,clientX:300,clientY:480});const w=selected[0],x=w.x;tick(.5);return w.order.kind==='move'&&w.x>x&&commandMode===null&&orderMarker.x===300;})()`));});
test('right-click orders a group without clearing selection',()=>{const r=game();assert.ok(r(`(()=>{selected=state.entities.filter(e=>e.owner===0&&!e.building);canvas.onpointerdown({button:2,clientX:800,clientY:600,preventDefault(){}});return selected.length===4&&selected.every(e=>e.order.kind==='move');})()`));});
