'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const assets=path.join(__dirname,'../assets');
function readModel(name){const data=fs.readFileSync(path.join(assets,'model-'+name+'.glb'));assert.equal(data.toString('ascii',0,4),'glTF');assert.equal(data.readUInt32LE(4),2);assert.equal(data.readUInt32LE(8),data.length);assert.equal(data.readUInt32LE(16),0x4e4f534a);return JSON.parse(data.toString('utf8',20,20+data.readUInt32LE(12)));}
test('all live meshes are valid, indexed GLB assets with physical materials',()=>{const files=fs.readdirSync(assets).filter(n=>n.startsWith('model-')&&n.endsWith('.glb'));assert.equal(files.length,118);for(const f of files){const model=readModel(f.slice(6,-4));assert(model.meshes.length>0,f);assert(model.meshes.every(m=>m.primitives.every(p=>p.indices!==undefined)),f);assert(model.materials.every(m=>m.pbrMetallicRoughness),f);assert(model.meshes.length<=24,'material batching budget: '+f);}});
test('units retain articulated rigs and distinct movement/attack animation',()=>{for(const name of ['knight','worker','peon','cavalier','devoured','cov-captain','cov-shellguard','cov-archer','cov-resin','cov-beetle','cov-wasp','cov-wasp-venom','cov-burrower','cov-centipede']){const model=readModel(name);assert(model.skins.length>0,name);assert(model.animations.some(a=>a.name==='walk'),name);assert(model.animations.some(a=>a.name==='attack'),name);for(const animation of model.animations)assert(animation.channels.length>0,name+' '+animation.name);}});
test('all factions have real stronghold geometry at each upgrade level',()=>{for(const suffix of ['','-dominion','-covenant'])for(const level of ['', '-level2','-level3','-level4']){const model=readModel('world-base'+level+suffix);assert(model.meshes.length>0);assert(!model.skins);}});
test('Verdant scales and belly materials retain independent painted textures',()=>{for(const name of ['cov-archer','cov-resin']){const model=readModel(name),indices=model.materials.map(m=>m.pbrMetallicRoughness.baseColorTexture?.index);assert(indices.every(i=>i!==undefined),name);assert(new Set(indices).size>=2,name+' must retain separate scales and belly textures');const data=fs.readFileSync(path.join(assets,'model-'+name+'.glb')),binaryOffset=20+data.readUInt32LE(12)+8;const images=model.images.map(image=>{const view=model.bufferViews[image.bufferView];return data.subarray(binaryOffset+view.byteOffset,binaryOffset+view.byteOffset+view.byteLength);});const a=model.textures[indices[0]].source,b=model.textures[indices[1]].source;assert(!images[a].equals(images[b]),name+' surface maps must have distinct painted detail');}});
test('Verdant stronghold upgrades grow geometry without exceeding the building draw-call budget',()=>{let height=0,vertices=0;for(const level of ['', '-level2','-level3','-level4']){const model=readModel('world-base'+level+'-covenant'),positions=model.meshes.flatMap(m=>m.primitives.map(p=>model.accessors[p.attributes.POSITION])),nextHeight=Math.max(...positions.map(p=>p.max[1])),nextVertices=positions.reduce((n,p)=>n+p.count,0);assert(nextHeight>height,'upgrade must add visible height');assert(nextVertices>vertices,'upgrade must add actual geometry');assert(model.meshes.length<=8,'stronghold material batching budget');height=nextHeight;vertices=nextVertices;}});
test('woodland collector task variants preserve animated rigs and emissive eyes',()=>{for(const name of ['cov-worker','cov-worker-pick','cov-worker-hammer','cov-worker-carry','cov-worker-logs']){const model=readModel(name);assert(model.skins[0].joints.length>100,name+' detailed geometry must remain attached to the rig');assert(model.animations.some(a=>a.name==='walk'),name);assert(model.animations.some(a=>a.name==='attack'),name);assert(model.materials.some(m=>m.emissiveFactor?.[1]>.1),name+' luminous green eyes');assert(model.meshes.length<=8,name+' material batch budget');}});
test('iron beast and wind elemental have animated rigs and distinct physical surface effects',()=>{for(const name of ['cov-beetle','cov-weaver']){const model=readModel(name);assert(model.skins[0].joints.length>100,name);assert(model.animations.some(a=>a.name==='walk'),name);assert(model.animations.some(a=>a.name==='attack'),name);assert(model.meshes.length<=8,name);}const wind=readModel('cov-weaver');assert(wind.materials.filter(m=>m.alphaMode==='BLEND').length>=2,'layered translucent air');const iron=readModel('cov-beetle');assert(iron.materials.some(m=>m.pbrMetallicRoughness.metallicFactor>=.5),'iron armor');const trap=readModel('world-trap-covenant'),resin=readModel('world-trap-resin');assert(trap.materials.some(m=>m.alphaMode==='BLEND'));assert(!resin.materials.some(m=>m.alphaMode==='BLEND'),'Dominion retains solid resin trap');});
test('Dawnward peasants retain straw hats on all articulated tool and delivery variants',()=>{for(const name of ['worker','worker-pick','worker-hammer','worker-carry','worker-logs']){const model=readModel(name);assert(model.nodes.some(n=>n.extras?.farmerHat),name+' hat must survive export');const straw=model.materials.find(m=>m.name==='farmer-straw');assert(straw?.pbrMetallicRoughness.baseColorTexture,name+' textured straw');assert.equal(straw.pbrMetallicRoughness.metallicFactor,0);assert(model.skins.length&&model.animations.some(a=>a.name==='walk')&&model.animations.some(a=>a.name==='attack'));}});
test('Dawnward stronghold tiers retain individual masonry blocks and 512px surface maps within the batch budget',()=>{let blocks=0;for(const tier of ['','-level2','-level3','-level4']){const name='world-base'+tier,model=readModel(name),detail=model.nodes.find(n=>n.extras?.masonryDetail)?.extras.masonryDetail;assert(detail?.blocks>blocks,name+' upgrade wings must add real stone blocks');blocks=detail.blocks;assert(model.meshes.length<=12,name+' preserve batched rendering');const material=model.materials.find(m=>m.name==='stronghold-cut-stone');assert(material?.normalTexture,name+' surface normals');const data=fs.readFileSync(path.join(assets,'model-'+name+'.glb')),binaryOffset=20+data.readUInt32LE(12)+8;for(const texture of [material.pbrMetallicRoughness.baseColorTexture,material.normalTexture]){const source=model.images[model.textures[texture.index].source],view=model.bufferViews[source.bufferView],png=data.subarray(binaryOffset+view.byteOffset,binaryOffset+view.byteOffset+view.byteLength);assert.equal(png.toString('ascii',1,4),'PNG');assert.equal(png.readUInt32BE(16),512,name+' retain full surface resolution');}}});

test('phoenix has layered feather geometry, articulated wings and varied warm plumage',()=>{const model=readModel('phoenix');assert.equal(model.skins[0].joints.length,3,'individual feather vanes share the body and two wing bones');assert(model.animations.some(a=>a.name==='walk')&&model.animations.some(a=>a.name==='attack'));assert(model.materials.some(m=>m.emissiveFactor?.[0]>.1),'warm flame tips');const primitives=model.meshes.flatMap(m=>m.primitives);assert(primitives.every(p=>p.attributes.COLOR_0!==undefined),'varied plumage shades survive batching');assert(model.meshes.length<=8);});
test('all factions have open and closed gate models with distinct doorway geometry',()=>{for(const faction of ['','-dominion','-covenant']){const closed=readModel('world-gate'+faction),open=readModel('world-gate-open'+faction);assert(closed.meshes.length>0&&open.meshes.length>0);const bounds=m=>m.meshes.flatMap(mesh=>mesh.primitives.map(p=>m.accessors[p.attributes.POSITION].max[2]));assert(Math.max(...bounds(open))>Math.max(...bounds(closed)),'open leaves swing aside');}});

test('all factions have supply houses with physical textured surfaces',()=>{for(const suffix of ['', '-dominion', '-covenant']){const model=readModel('world-house'+suffix);assert(model.materials.some(m=>m.pbrMetallicRoughness.baseColorTexture));assert(!model.skins);assert(model.meshes.length<=8);}});
test('Dominion fortress tiers retain timber, tusks and emissive fire as they grow',()=>{let vertices=0,height=0;for(const level of ['', '-level2', '-level3', '-level4']){const model=readModel('world-base'+level+'-dominion');assert(model.nodes.some(n=>n.extras?.dominionFortress));assert(model.materials.some(m=>m.emissiveFactor?.[0]>.5));const positions=model.meshes.flatMap(m=>m.primitives.map(p=>model.accessors[p.attributes.POSITION])),nextVertices=positions.reduce((n,p)=>n+p.count,0),nextHeight=Math.max(...positions.map(p=>p.max[1]));assert(nextVertices>vertices);assert(nextHeight>=height);assert(model.meshes.length<=12);vertices=nextVertices;height=nextHeight;}});
