'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const {createEngine}=require('../multiplayer/engine.cjs'),{LobbyService}=require('../multiplayer/lobbies.cjs');
const players=[{name:'You',faction:'human',color:'#53c9eb',ai:false,team:1},{name:'Enemy',faction:'horde',color:'#ef685a',ai:false,team:2},{name:'Ally',faction:'covenant',color:'#b88af0',ai:false,team:1}];
function flat(rules){const engine=createEngine(players,'highlands',rules),s=engine.state;s.count=0;s.ai=999;s.posts=[];s.resources=[];s.mountains=[];s.plateaus=[];s.rivers=[];s.wallVersion++;return {engine,s};}
test('income forecasts count delivered earnings rather than starting resources or spending',()=>{const {engine,s}=flat();s.players[0].gold=600;for(let i=0;i<61;i++){s.players[0].stats.goldGained=i*2;s.players[0].stats.woodGained=i;engine.step(1);}const h=s.players[0].incomeHistory;assert.equal(h.length,61);assert.equal(h.at(-1).gold-h[0].gold,120);assert.equal(h.at(-1).wood-h[0].wood,60);s.players[0].gold=0;engine.step(1);assert.equal(s.players[0].incomeHistory.at(-1).gold,120);});
test('teammate pings preserve fog, expire, are rate-limited and never reach opponents',()=>{const {engine,s}=flat(),before=Array.from(engine.snapshot(0).seen);assert.equal(engine.ping(0,'danger',3000,3000),null);assert.match(engine.ping(0,'help',1,2),/two seconds/);assert.match(engine.ping(1,'danger',Infinity,2),/valid/);assert.equal(engine.snapshot(0).pings.length,1);assert.equal(engine.snapshot(2).pings.length,1);assert.equal(engine.snapshot(2).pings[0].owner,2);assert.equal(engine.snapshot(1).pings.length,0);assert.deepEqual(Array.from(engine.snapshot(0).seen),before);s.time+=9;engine.step(.05);assert.equal(engine.snapshot(2).pings.length,0);});
test('spectators cannot send pings and lobby rules validate convoy mode',()=>{const service=new LobbyService(),host=service.create({...players[0],map:'highlands',rules:{victory:'convoy'}}),guest=service.join(host.room.code,players[1]),viewer=service.join(host.room.code,{...players[2],spectator:true});service.act(host.room.code,guest.token,{action:'profile',...players[1],ready:true});service.act(host.room.code,host.token,{action:'start'});const room=service.get(host.room.code);room.engine.state.count=0;assert.throws(()=>service.act(host.room.code,viewer.token,{action:'ping',kind:'help',x:10,y:20}),/Spectators/);assert.equal(service.act(host.room.code,host.token,{action:'ping',kind:'help',x:10,y:20}).ok,true);assert.equal(room.rules.victory,'convoy');});
test('convoys score allied deliveries, reject manual orders, and win at three',()=>{const {engine,s}=flat({victory:'convoy'});s.time=12;engine.step(.05);let wagon=s.entities.find(e=>e.owner===0&&e.convoy),destination=s.convoyRace.destinations.find(d=>d.owner===0);assert(wagon);assert.equal(wagon.type,'convoy');assert.match(engine.apply(0,{kind:'order',id:wagon.id,order:{kind:'move',x:10,y:10}}),/assigned route/);for(let i=0;i<3;i++){wagon.x=destination.x;wagon.y=destination.y;engine.step(.05);assert.equal(s.convoyRace.scores['team:1'],i+1);if(i<2){s.time+=31;engine.step(.05);wagon=s.entities.find(e=>e.owner===0&&e.convoy);assert(wagon);}}assert.equal(s.ended,true);assert.equal(engine.snapshot(2).result,'VICTORY');assert.equal(engine.snapshot(1).result,'DEFEAT');});
test('a destroyed convoy respawns without awarding delivery credit; checkpoints preserve the race',()=>{const {engine,s}=flat({victory:'convoy'});s.time=12;engine.step(.05);const wagon=s.entities.find(e=>e.owner===0&&e.convoy);wagon.hp=0;engine.step(.05);assert.equal(s.convoyRace.scores['team:1'],0);s.time=60;engine.step(.05);assert(s.entities.some(e=>e.owner===0&&e.convoy&&e.hp>0));const copy=createEngine(players,'highlands',{victory:'convoy'});copy.restore(engine.checkpoint());assert.deepEqual(copy.snapshot(0).convoyRace,engine.snapshot(0).convoyRace);});
test('AI scouts visible forces, trains anti-air counters and forgets stale hidden observations',()=>{const {engine,s}=flat();s.players[1].ai=true;s.players[1].difficulty='hard';s.players[1].gold=s.players[1].wood=5000;const base=s.entities.find(e=>e.owner===1&&e.type==='base');base.x=1000;base.y=1000;base.level=3;for(const e of s.entities.filter(e=>e.owner===1&&!e.building)){e.x=1000;e.y=1100;}
 const template=s.entities.find(e=>e.owner===0&&!e.building);for(let i=0;i<3;i++)s.entities.push({...template,id:700+i,type:'air2',x:1100+i*20,y:1000,hp:400,max:400,order:{kind:'stop'},queue:[],tasks:[]});s.entities.push({...template,id:850,owner:1,type:'scout',x:950,y:950,queue:[],tasks:[],order:null});s.entities.push({...base,id:900,type:'barracks',x:900,y:1000,queue:[],research:null});engine.step(.1);assert.equal(s.players[1].counterPlan,'air');assert.equal(s.entities.find(e=>e.id===900).queue[0].type,'ranged');for(const e of s.entities.filter(e=>e.owner!==1)){e.x=3500;e.y=3500;}s.time+=32;s.players[1].nextAI=0;engine.step(.1);assert.equal(s.players[1].counterPlan,'balanced');assert.equal(Object.keys(s.players[1].scouted).length,0);});
test('formation followers pass a narrow river bridge and restore their final slots',()=>{const {engine,s}=flat();s.rivers=[{width:44,points:Array.from({length:168},(_,i)=>({x:1200,y:i*24})),bridges:[1000]}];const template=s.entities.find(e=>e.owner===0&&!e.building),troops=[];for(let i=0;i<12;i++){const e={...template,id:500+i,type:i<6?'melee':'ranged',x:750+(i%3)*35,y:900+Math.floor(i/3)*45,hp:1000,max:1000,size:9,order:null,queue:[],tasks:[]};s.entities.push(e);troops.push(e);}const leader=troops[0];for(let i=0;i<troops.length;i++){const x=1600-Math.floor(i/6)*35,y=900+(i%6)*35;assert.equal(engine.apply(0,{kind:'order',id:troops[i].id,order:{kind:'move',x,y,formation:{key:'test-squad',leaderId:leader.id,dx:x-1600,dy:y-900,finalX:x,finalY:y}}}),null);}for(let i=0;i<1000;i++){engine.step(.05);for(const e of troops)assert(!(Math.abs(e.x-1200)<22&&Math.abs(e.y-1000)>58),'Ground unit entered unbridged river');}assert(troops.every(e=>e.x>1450),'Squad did not cross bridge');assert(troops.every(e=>Math.hypot(e.x-e.order?.formation?.finalX||0,e.y-e.order?.formation?.finalY||0)<80||!e.order));});
for(const map of ['highlands','frontier','canyon'])test(map+' convoys have distant ground relays and complete a real routed delivery',()=>{const engine=createEngine(players.slice(0,2),map,{victory:'convoy'}),s=engine.state;s.count=0;s.convoyRace.scores['team:1']=s.convoyRace.scores['team:2']=-100;for(const d of s.convoyRace.destinations){const base=s.entities.find(e=>e.owner===d.owner&&e.type==='base');assert(Math.hypot(d.x-base.x,d.y-base.y)>550);}for(let i=0;i<3600&&Object.values(s.convoyRace.scores).some(n=>n===-100);i++)engine.step(.05);assert(Object.values(s.convoyRace.scores).every(n=>n>-100),'A convoy failed to reach its depot through stock terrain');});
test('outnumbered AI troops retreat from a losing fight and retain a short fallback order',()=>{const {engine,s}=flat();const p=s.players[1];p.ai=true;p.difficulty='hard';p.gold=p.wood=0;const base=s.entities.find(e=>e.owner===1&&e.type==='base');base.x=400;base.y=400;const template=s.entities.find(e=>e.owner===0&&!e.building),soldier={...template,id:950,owner:1,type:'melee',x:1400,y:1400,hp:1000,max:1000,queue:[],tasks:[],order:null};s.entities.push(soldier);for(let i=0;i<6;i++)s.entities.push({...template,id:960+i,type:'melee',x:1450+i*20,y:1400,hp:1000,max:1000,queue:[],tasks:[],order:{kind:'stop'}});engine.step(.1);assert.equal(soldier.order.kind,'move');assert(soldier.fallbackUntil>s.time);assert(Math.hypot(soldier.order.x-base.x,soldier.order.y-base.y)<300);});
test('AI raiders target recently scouted collectors while keeping a larger force available',()=>{const {engine,s}=flat();const p=s.players[1];p.ai=true;p.personality='balanced';p.difficulty='hard';p.gold=p.wood=0;const base=s.entities.find(e=>e.owner===1&&e.type==='base');base.x=400;base.y=400;const template=s.entities.find(e=>e.owner===0&&!e.building);for(let i=0;i<6;i++)s.entities.push({...template,id:1050+i,owner:1,type:'melee',x:1200+i*20,y:1200,hp:1000,max:1000,queue:[],tasks:[],order:null});const collector={...template,id:1090,type:'worker',x:1450,y:1200,queue:[],tasks:[],order:{kind:'stop'}};s.entities.push(collector);engine.step(.1);const raiders=s.entities.filter(e=>e.owner===1&&e.id>=1050&&e.id<1056&&e.order?.kind==='attackMove'&&Math.hypot(e.order.x-collector.x,e.order.y-collector.y)<170);assert(raiders.length>=1&&raiders.length<=2);assert(p.scouted[collector.id]);});
