/** Team-colored custom standards, shared by building flags and hand-held cloth. */
import * as THREE from 'three';
const textures=new Map();let playerTextures=new WeakMap();let weave=null;
function clothWeave(){if(weave)return weave;const c=document.createElement("canvas");c.width=c.height=64;const g=c.getContext("2d");g.fillStyle="#808080";g.fillRect(0,0,64,64);for(let i=0;i<64;i++){g.fillStyle=i%2?"#a0a0a0":"#606060";g.fillRect(i,0,1,64);g.fillStyle=i%2?"#ffffff33":"#00000033";g.fillRect(0,i,64,1);}weave=new THREE.CanvasTexture(c);weave.wrapS=weave.wrapT=THREE.RepeatWrapping;weave.repeat.set(5,8);return weave;}
// GPU cloth displacement pins the pole edge and sends ripples along the free edge.
function windCloth(material,entry,amplitude){entry.bannerWind??={value:0};material.bumpMap=clothWeave();material.bumpScale=.025;const before=material.onBeforeCompile;material.onBeforeCompile=shader=>{before(shader);shader.uniforms.bannerWindTime=entry.bannerWind;shader.vertexShader="uniform float bannerWindTime;\n"+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace("#include <begin_vertex>","#include <begin_vertex>\n transformed.z += sin(bannerWindTime*3.2+uv.x*9.0+uv.y*4.0)*pow(clamp(uv.x,0.0,1.0),1.5)*"+amplitude.toFixed(3)+";");};material.customProgramCacheKey=()=>"woven-banner-wind:"+amplitude;material.needsUpdate=true;}
export function clearBannerTextures(){for(const texture of textures.values())texture.dispose();textures.clear();weave?.dispose();weave=null;playerTextures=new WeakMap();}
function textureFor(player){const cached=playerTextures.get(player);if(cached&&cached.color===player.color&&cached.banner===player.banner)return cached.texture;const B=window.KawBanners;if(!B)return null;const design=B.normalize(player.banner),key=player.color+JSON.stringify(design);if(textures.has(key)){const texture=textures.get(key);playerTextures.set(player,{color:player.color,banner:player.banner,texture});return texture;}const canvas=document.createElement('canvas');canvas.width=128;canvas.height=192;B.draw(canvas.getContext('2d'),design,player.color,128,192);const g=canvas.getContext("2d");for(let i=0;i<canvas.width;i+=2){g.fillStyle=i%4?"#ffffff0c":"#00000012";g.fillRect(i,0,1,canvas.height);}for(let y=0;y<canvas.height;y+=3){g.fillStyle=y%6?"#ffffff09":"#00000012";g.fillRect(0,y,canvas.width,1);}const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;texture.anisotropy=4;textures.set(key,texture);playerTextures.set(player,{color:player.color,banner:player.banner,texture});return texture;}
export function updateBanner(entry,e,player,time){const texture=textureFor(player);if(!texture)return;entry.bannerWind??={value:time};entry.bannerWind.value=time;if(entry.name.startsWith('banner-')||entry.name==='world-tower-dominion'){if(!entry.standardMaterials){entry.standardMaterials=[];entry.model.traverse(mesh=>{if(!mesh.isMesh||!['banner-cloth','tower-banner-cloth'].includes(mesh.material.name))return;mesh.material=mesh.material.clone();mesh.material.vertexColors=false;mesh.material.color.set(0xffffff);mesh.material.normalMap=null;mesh.material.roughnessMap=null;windCloth(mesh.material,entry,entry.name.startsWith('banner-')?5.5:3.5);entry.standardMaterials.push(mesh.material);});}for(const material of entry.standardMaterials){material.map=texture;material.needsUpdate=!material.userData.bannerApplied;material.userData.bannerApplied=true;}}

 if(!e.building||e.construction||['wall','gate','trap','barricade'].includes(e.type))return;
 if(!entry.banner){const height=(entry.box.max.y-entry.box.min.y)*entry.factor,width=(entry.box.max.x-entry.box.min.x)*entry.factor,h=Math.max(1.1,Math.min(3,height*.28)),group=new THREE.Group(),pole=new THREE.Mesh(new THREE.CylinderGeometry(.04,.05,h*1.6,6),new THREE.MeshStandardMaterial({color:0x80603e,roughness:.85})),cloth=new THREE.Mesh(new THREE.PlaneGeometry(h*.65,h,12,16),new THREE.MeshStandardMaterial({map:texture,roughness:.93,side:THREE.DoubleSide}));windCloth(cloth.material,entry,.18);pole.position.y=h*.7;cloth.position.set(h*.32,h,0);group.position.set(-width*.32,height*.66,0);group.add(pole,cloth);entry.root.add(group);entry.banner={group,cloth};}
 entry.banner.cloth.material.map=texture;entry.banner.cloth.rotation.y=Math.sin(time*1.6+e.id)*.12;
}
export function disposeBanner(entry){entry.standardMaterials?.forEach(m=>m.dispose());entry.banner?.group.traverse(m=>{if(m.isMesh){m.geometry.dispose();m.material.dispose();}});}
