/* Shared, bounded banner data. No uploaded code or external images are needed. */
(function(root){'use strict';
 const patterns=['plain','quartered','diagonal','stripes','cross','chevron'],symbols=['sun','skull','tree','spear','crown','spiral','custom'];
 const shapeTypes=['circle','square','triangle','diamond','star','bar'];
 const clamp=(n,min,max,fallback)=>Number.isFinite(n)?Math.max(min,Math.min(max,n)):fallback;
 function normalize(value){value=value&&typeof value==='object'?value:{};return {name:String(value.name||'New banner').slice(0,32),pattern:patterns.includes(value.pattern)?value.pattern:'plain',symbol:symbols.includes(value.symbol)?value.symbol:'sun',shapes:Array.isArray(value.shapes)?value.shapes.slice(0,32).filter(s=>s&&shapeTypes.includes(s.type)).map(s=>({type:s.type,x:clamp(s.x,.05,.95,.5),y:clamp(s.y,.05,.95,.5),size:clamp(s.size,.025,.5,.15),rotation:clamp(s.rotation,-360,360,0),tone:['gold','light','dark'].includes(s.tone)?s.tone:'gold'})):[],cells:Array.isArray(value.cells)?[...new Set(value.cells.filter(n=>Number.isInteger(n)&&n>=0&&n<256))].slice(0,256):[]};}
 function draw(g,design,color,w=128,h=192){const d=normalize(design);g.clearRect(0,0,w,h);g.fillStyle=/^#[0-9a-f]{6}$/i.test(color)?color:'#53c9eb';g.fillRect(0,0,w,h);g.fillStyle='#111c284d';if(d.pattern==='quartered'){g.fillRect(0,0,w/2,h/2);g.fillRect(w/2,h/2,w/2,h/2);}if(d.pattern==='stripes')for(let x=0;x<w;x+=w/3)g.fillRect(x,0,w/7,h);if(d.pattern==='cross'){g.fillRect(w*.4,0,w*.2,h);g.fillRect(0,h*.4,w,h*.15);}if(d.pattern==='diagonal'||d.pattern==='chevron'){g.beginPath();g.moveTo(0,0);g.lineTo(w,h*.6);g.lineTo(w,h*.85);g.lineTo(0,h*.25);g.fill();if(d.pattern==='chevron'){g.beginPath();g.moveTo(w,0);g.lineTo(0,h*.6);g.lineTo(0,h*.85);g.lineTo(w,h*.25);g.fill();}}
 g.strokeStyle='#e2c788';g.lineWidth=Math.max(1,w*.018);g.strokeRect(w*.04,h*.03,w*.92,h*.94);g.save();g.translate(w/2,h*.46);g.scale(w/100,w/100);g.fillStyle='#f0dfad';g.strokeStyle='#f0dfad';g.lineWidth=4;g.lineCap='round';g.lineJoin='round';
 if(d.symbol==='custom'){for(const cell of d.cells)g.fillRect((cell%16-8)*4,(Math.floor(cell/16)-8)*4,4,4);}else if(d.symbol==='sun'){g.beginPath();g.arc(0,0,15,0,Math.PI*2);g.fill();for(let i=0;i<12;i++){g.rotate(Math.PI/6);g.fillRect(-2,20,4,10);}}else if(d.symbol==='skull'){g.beginPath();g.ellipse(0,-3,22,25,0,0,Math.PI*2);g.fill();g.fillRect(-15,15,30,12);g.fillStyle='#27352e';g.fillRect(-14,-7,10,9);g.fillRect(4,-7,10,9);for(let x=-10;x<=10;x+=10)g.fillRect(x,19,3,8);}else if(d.symbol==='tree'){g.beginPath();g.moveTo(0,29);g.lineTo(0,-23);for(const side of [-1,1])for(let i=0;i<3;i++){g.moveTo(0,10-i*12);g.lineTo(side*(25-i*4),-8-i*12);}g.stroke();for(let i=0;i<7;i++){g.beginPath();g.ellipse(Math.sin(i*2.4)*24,-13+Math.cos(i*2.4)*16,6,4,i,0,Math.PI*2);g.fill();}}else if(d.symbol==='spiral'){g.beginPath();for(let i=0;i<100;i++){const a=i*.16,r=i*.28;i?g.lineTo(Math.cos(a)*r,Math.sin(a)*r):g.moveTo(0,0);}g.stroke();}else if(d.symbol==='crown'){g.beginPath();g.moveTo(-28,-18);g.lineTo(-16,0);g.lineTo(0,-28);g.lineTo(16,0);g.lineTo(28,-18);g.lineTo(22,22);g.lineTo(-22,22);g.closePath();g.fill();}else{g.fillRect(-2,-20,4,53);g.beginPath();g.moveTo(0,-36);g.lineTo(-12,-14);g.lineTo(12,-14);g.closePath();g.fill();}g.restore();for(const s of d.shapes){g.save();g.translate(s.x*w,s.y*h);g.rotate(s.rotation*Math.PI/180);g.fillStyle={gold:'#e7c778',light:'#fff2cf',dark:'#182922'}[s.tone];const r=s.size*w;g.beginPath();if(s.type==='circle')g.arc(0,0,r,0,Math.PI*2);else if(s.type==='square'||s.type==='bar')g.rect(-r,-r*(s.type==='bar'?.18:1),r*2,r*(s.type==='bar'?.36:2));else{const count=s.type==='star'?10:s.type==='triangle'?3:4;for(let i=0;i<count;i++){const a=-Math.PI/2+i*Math.PI*2/count,rr=s.type==='star'&&i%2?r*.45:r;i?g.lineTo(Math.cos(a)*rr,Math.sin(a)*rr):g.moveTo(Math.cos(a)*rr,Math.sin(a)*rr);}g.closePath();}g.fill();g.restore();}for(let x=0;x<w;x+=2){g.fillStyle=x%4?'#ffffff0a':'#0000000e';g.fillRect(x,0,1,h);}for(let y=0;y<h;y+=3){g.fillStyle=y%6?'#ffffff08':'#0000000e';g.fillRect(0,y,w,1);}}
 const api={patterns,symbols,shapeTypes,normalize,draw};if(typeof module!=='undefined')module.exports=api;else root.KawBanners=api;
})(typeof window==='undefined'?globalThis:window);
