/* Authoritative army commands, bounded history, faction tradeoffs and destruction.
 * Runs in both the browser and server VM. Presentation lives in battlefield-hud.js. */
(() => {
 const now=()=>globalThis.performance?.now?.()??Date.now();
 const profiler={enabled:false,samples:{},calls:{},reset(){this.samples={};this.calls={};},measure(key,fn){if(!this.enabled)return fn();const start=now();try{return fn();}finally{this.samples[key]=(this.samples[key]||0)+now()-start;this.calls[key]=(this.calls[key]||0)+1;}}};
 const profiles={human:{name:'The Dawnward',strength:'Armored infantry formations and defended sieges.',weakness:'Slower infantry are vulnerable to flanking and kiting.',counter:'Split their formations; raid the economy and use armor-piercing ranged troops.'},horde:{name:'The Dominion',strength:'Fast assault troops build momentum through sustained combat.',weakness:'Assault infantry trade some protection for speed.',counter:'Use chokepoints, ranged fire and retreats to break their momentum.'},covenant:{name:'The Verdant Council',strength:'Holding ground strengthens roots, venom and area control.',weakness:'Rootward takes time to establish and protects less against artillery.',counter:'Force them to move; use artillery or flyers against entrenched ground troops.'}};
 const originalQueue=queueTask;queueTask=function(e,o,append=false){if(!append)e.tactical=null;return originalQueue(e,o,append);};
 const originalStop=stopUnit;stopUnit=function(e){e.tactical=null;return originalStop(e);};
 function command(e,kind,p){if(!e||e.building||e.hp<=0||!['patrol','guard','retreat'].includes(kind))return false;
  if(kind==='guard'){const ally=state.entities.find(t=>t.id===p?.targetId&&t.hp>0&&!t.hiddenInMine&&sameTeam(t.owner,e.owner));if(!ally||ally===e)return false;queueTask(e,{kind:'attackMove',x:ally.x,y:ally.y});e.tactical={kind,guardId:ally.id};}
  else if(kind==='patrol'){if(!Number.isFinite(p?.x)||!Number.isFinite(p?.y)||p.x<10||p.y<10||p.x>SIZE-10||p.y>SIZE-10)return false;const a={x:e.x,y:e.y},b={x:p.x,y:p.y};queueTask(e,{kind:'attackMove',...b});e.tactical={kind,a,b,destination:'b'};}
  else{const homes=state.entities.filter(b=>b.owner===e.owner&&b.hp>0&&!b.construction&&['base','depot'].includes(b.type)).sort((a,b)=>Math.hypot(a.x-e.x,a.y-e.y)-Math.hypot(b.x-e.x,b.y-e.y));if(!homes.length)return false;const home=homes[0],a=Math.atan2(e.y-home.y,e.x-home.x),goal=openMovePoint(e,{x:home.x+Math.cos(a)*(home.size+70),y:home.y+Math.sin(a)*(home.size+70)});queueTask(e,{kind:'move',...goal});}
  return true;
 }
 function before(){if(!state.resourceMaxRecorded){for(const r of state.resources)r.initialAmount??=r.amount;state.resourceMaxRecorded=true;}const byId=new Map(state.entities.map(e=>[e.id,e]));for(const e of state.entities){const t=e.tactical;if(!t||e.hp<=0)continue;if(t.kind==='guard'){const ally=byId.get(t.guardId);if(!ally||ally.hp<=0){e.tactical=null;originalQueue(e,{kind:'hold'});continue;}const gap=Math.hypot(e.x-ally.x,e.y-ally.y);if(gap>90){const a=Math.atan2(e.y-ally.y,e.x-ally.x);if(!e.order||!['attackMove','attack'].includes(e.order.kind))originalQueue(e,{kind:'attackMove',x:ally.x,y:ally.y});if(e.order.kind==='attackMove'){e.order.x=ally.x+Math.cos(a)*65;e.order.y=ally.y+Math.sin(a)*65;}}else if(e.order?.kind==='attackMove')originalQueue(e,{kind:'hold'});}
   else if(t.kind==='patrol'){let dest=t[t.destination];if(Math.hypot(e.x-dest.x,e.y-dest.y)<30){t.destination=t.destination==='a'?'b':'a';dest=t[t.destination];}if(!e.order||!['attackMove','attack'].includes(e.order.kind))originalQueue(e,{kind:'attackMove',...dest});else if(e.order.kind==='attackMove'){e.order.x=dest.x;e.order.y=dest.y;}}
  }}
 const statsBase=matchStats;matchStats=function(owner){const s=statsBase(owner);for(const key of ['goldSpent','woodSpent','unitsLost','unitsKilled','buildingsLost','armyValue'])s[key]??=0;s.economy??=[];return s;};
 const originalPay=pay;pay=function(owner,g,w){const paid=originalPay(owner,g,w);if(paid&&!(owner===0&&state.adminResources)){const s=matchStats(owner);s.goldSpent+=g;s.woodSpent+=w;}return paid;};
 const originalRefund=refundResearch;refundResearch=function(b,r){originalRefund(b,r);const s=matchStats(b.owner);s.goldSpent=Math.max(0,s.goldSpent-(r.gold||0));s.woodSpent=Math.max(0,s.woodSpent-(r.wood||0));};
 const originalDeaths=resolveCombatDeaths;resolveCombatDeaths=function(){state.ruins??=[];for(const e of state.entities)if(e.hp<=0&&!e.deathResolved){const s=matchStats(e.owner);if(e.building)s.buildingsLost++;else s.unitsLost++;if(Number.isInteger(e.lastDamageOwner)&&!sameTeam(e.lastDamageOwner,e.owner)&&!e.building)matchStats(e.lastDamageOwner).unitsKilled++;if(!['trap','barricade'].includes(e.type))state.ruins.push({id:e.id,type:e.type,owner:e.owner,x:e.x,y:e.y,size:e.size,level:e.level,building:e.building,at:state.time,facing:e.facing});}if(state.ruins.length>80)state.ruins.splice(0,state.ruins.length-80);return originalDeaths();};
 function after(){state.ruins=(state.ruins||[]).filter(r=>state.time-r.at<(r.building?120:2.4));if(!state.ended&&(state.reportAt??-5)>state.time-5)return;state.reportAt=state.time;const values=Array(state.players.length).fill(0);for(const e of state.entities)if(!e.building&&e.type!=='worker'&&e.hp>0)values[e.owner]+=(units[e.type].gold||0)+(units[e.type].wood||0);for(let i=0;i<state.players.length;i++){const s=matchStats(i);s.armyValue=values[i];s.economy.push({time:state.time,gold:state.players[i].gold,wood:state.players[i].wood,earned:s.goldGained+s.woodGained,spent:s.goldSpent+s.woodSpent,army:values[i],lost:s.unitsLost});if(s.economy.length>720)s.economy.splice(1,s.economy.length-720);}}
 const oldTick=tick;tick=function(dt){return profiler.measure('simulation',()=>{before();oldTick(dt);after();});};
 const oldAI=ai;ai=function(...a){return profiler.measure('ai',()=>oldAI(...a));};
 const oldRoute=wallRoute;wallRoute=function(...a){return profiler.measure('pathfinding',()=>oldRoute(...a));};
 const oldMove=move;move=function(...a){return profiler.measure('movement',()=>oldMove(...a));};
 const oldSpeed=effectiveSpeed;effectiveSpeed=function(e){const f=state.players[e.owner].faction;return oldSpeed(e)*(f==='human'&&['melee','cavalier','shieldwarden'].includes(e.type)?.94:f==='horde'&&['melee','devoured','bogbreaker'].includes(e.type)?1.08:1);};
 const oldArmor=armorMultiplier;armorMultiplier=function(e){const f=state.players[e.owner].faction;return Math.max(.3,Math.min(1,oldArmor(e)+(f==='human'&&['melee','cavalier','shieldwarden'].includes(e.type)?-.04:f==='horde'&&['melee','devoured','bogbreaker'].includes(e.type)?.04:0)));};
 const oldDamage=KawTactics.damage;KawTactics.damage=function(e,t){return oldDamage(e,t)*(state.players[t.owner].faction==='covenant'&&t.rootward&&['siege','bastion'].includes(e.type)?1.12:1);};
 const clearOld=clearWallLine;clearWallLine=function(...a){return profiler.measure('collision',()=>clearOld(...a));};const trafficOld=trafficNeighbors;trafficNeighbors=function(...a){return profiler.measure('traffic',()=>trafficOld(...a));};const sepOld=separateUnits;separateUnits=function(...a){return profiler.measure('separation',()=>sepOld(...a));};const effOld=effectiveSpeed;effectiveSpeed=function(...a){return profiler.measure('speed',()=>effOld(...a));};
 globalThis.KawBattle={command,profiles,profiler,before,after};
})();
