/* Optional tactical information and accessible controls. All game rules remain shared. */
(() => {
 const make=(tag,text,parent)=>{const e=document.createElement(tag);if(text)e.textContent=text;parent?.append(e);return e;};
 const button=(text,parent,fn)=>{const e=make('button',text,parent);e.type='button';e.onclick=fn;return e;};
 const defaults={ranges:false,rallies:false,resources:false,idleProduction:false,preview:true,profiler:false,colorblind:false,reduced:false,largeUI:false,textScale:1};
 let settings={...defaults};try{Object.assign(settings,JSON.parse(localStorage.getItem('kaw-accessibility')||'{}'));}catch{}
 settings.textScale=Math.max(1,Math.min(1.5,Number(settings.textScale)||1));
 function apply(){document.body.classList.toggle('large-interface',!!settings.largeUI);document.body.classList.toggle('reduced-effects',!!settings.reduced);document.body.style.setProperty('--text-scale',settings.textScale);KawBattle.profiler.enabled=!!settings.profiler;scheduleViewportResize();}
 function save(){try{localStorage.setItem('kaw-accessibility',JSON.stringify(settings));}catch{}apply();}
 const box=make('fieldset',null,$('keySettings'));box.id='accessibilitySettings';make('legend','Readability & tactical overlays',box);
 for(const [key,label]of Object.entries({largeUI:'Larger command interface',colorblind:'Team symbols and patterns',reduced:'Reduced motion and battle effects',ranges:'Selected attack ranges',rallies:'All friendly rally points',resources:'Resource depletion bars',idleProduction:'Idle production markers',preview:'Formation preview before moving',profiler:'Performance breakdown'})){const l=make('label',label,box),input=make('input',null,l);input.type='checkbox';input.checked=!!settings[key];input.dataset.option=key;input.onchange=()=>{settings[key]=input.checked;save();};}
 const tl=make('label','Text size',box),ts=make('select',null,tl);ts.id='textScale';for(const [v,label]of [[1,'Standard'],[1.2,'Large'],[1.4,'Extra large']]){const o=make('option',label,ts);o.value=v;}ts.value=String(settings.textScale);ts.onchange=()=>{settings.textScale=Number(ts.value);save();};
 const pf=make('aside',null,document.querySelector('#game main'));pf.id='performancePanel';pf.hidden=!settings.profiler;pf.setAttribute('aria-live','off');
 const menu=make('details',null,$('battleTools'));menu.id='battleInformation';make('summary','Battle information',menu);button('Tactical overlays',menu,()=>{openKeySettings();box.scrollIntoView({block:'nearest'});});
 Object.assign(defaultKeys,{patrol:'Shift+P',guard:'Shift+G',retreat:'Shift+R'});
 const oldIssue=issueCommand;issueCommand=function(p,append=false,allowMove=true){if(!['patrol','guard'].includes(commandMode))return oldIssue(p,append,allowMove);if(append){toast('Patrol and guard are persistent orders. Issue them without Shift.');return;}const mode=commandMode,troops=selected.filter(e=>e.owner===0&&!e.building&&e.hp>0),target=mode==='guard'?state.entities.filter(t=>t.hp>0&&sameTeam(t.owner,0)&&hitFriendly(t,p)&&!troops.includes(t)).sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y))[0]:null;if(mode==='guard'&&!target){toast('Choose another friendly unit or building to guard.');return;}for(const e of troops){const payload={kind:'tactical',mode,id:e.id,x:p.x,y:p.y,targetId:target?.id};if(!multiplayerCommand(payload))KawBattle.command(e,mode,payload);}commandMode=null;orderMarker={...p,left:1};updateUI();};
 function choose(mode){if(!state||paused||state.replay||state.spectating)return;placement=null;setTouchMode('order');commandMode=mode;toast(mode==='guard'?'Right-click a friendly unit to guard it.':'Right-click the far end of the patrol route.');}
 const oldUI=updateUI;updateUI=function(...a){oldUI(...a);if(!state||!selected.some(e=>e.owner===0&&!e.building)||$('advancedArmyCommands'))return;const p=make('section',null,$('actions'));p.id='advancedArmyCommands';make('h3','ARMY CONTROL',p);for(const [label,mode]of [['Patrol','patrol'],['Guard ally','guard'],['Retreat','retreat']]){const b=button(label,p,()=>{if(mode==='retreat'){for(const e of selected.filter(e=>e.owner===0&&!e.building)){if(!multiplayerCommand({kind:'tactical',mode,id:e.id}))KawBattle.command(e,mode);}commandMode=null;toast('Retreating to the nearest friendly Stronghold or Outpost.');}else choose(mode);});registerCommand(b,label,b.onclick,{commandId:mode});}};
 const manual=make('details',null,$('keySettings'));make('summary','Army control guide',manual);make('p','Patrol fights while traveling back and forth between the starting point and your destination. Guard follows an ally and fights nearby enemies. Retreat returns to your nearest completed Stronghold or Outpost without stopping to attack. A new ordinary order or Stop cancels patrol or guard. Choose a formation, then hover the battlefield to preview the destination; ranged troops stay behind melee troops. Use right-click on PC, or tap in Order mode on a phone.',manual);
 const factions=make('dialog',null,document.body);factions.id='factionGuide';button('Faction strategies',$('campaignMenu'),()=>{factions.replaceChildren();make('h2','Faction strategies and counters',factions);for(const p of Object.values(KawBattle.profiles)){make('h3',p.name,factions);make('p','Strength: '+p.strength,factions);make('p','Weakness: '+p.weakness,factions);make('p','Counterplay: '+p.counter,factions);}make('p','Dawnward armored infantry: 4 percentage points more protection, 6% less speed. Dominion assault infantry: 8% more speed, 4 percentage points less protection. Entrenched Verdant troops take 12% more artillery damage. Existing Standfast, Surge and Rootward bonuses still apply.',factions);button('Close',factions,()=>factions.close());factions.showModal();});
 // Reports use bounded simulation history and plain DOM text; never HTML from player names.
 const report=make('dialog',null,document.body);report.id='battleReport';
 function rows(){if(state.networkMatch&&!state.ended&&!state.spectating)return[{name:state.players[0].name||'You',faction:state.players[0].faction,stats:state.players[0].stats}];return state.matchStats||state.players.map((p,i)=>({name:p.name||'Commander '+(i+1),faction:p.faction,stats:p.stats}));}
 function showReport(){if(!state)return;if(!state.networkMatch)KawBattle.after();report.replaceChildren();make('h2','Battle report',report);const data=rows(),scroll=make('div',null,report);scroll.className='results-scroll';const table=make('table',null,scroll),head=make('tr',null,make('thead',null,table));for(const label of ['Commander','Army value','Gold spent','Lumber spent','Units lost','Units defeated','Buildings lost'])make('th',label,head);const body=make('tbody',null,table);for(const p of data){const s=p.stats||{},row=make('tr',null,body);make('th',p.name,row);for(const key of ['armyValue','goldSpent','woodSpent','unitsLost','unitsKilled','buildingsLost'])make('td',String(Math.round(s[key]||0)),row);}
 const caption=make('p','Economy graph: cumulative resources earned, resources spent, and army value. Spending excludes refunded production. Army value is the original gold + lumber cost of surviving fighters; starting fighters are included.',report),choice=make('select',null,report);choice.setAttribute('aria-label','Graph commander');data.forEach((p,i)=>{const o=make('option',p.name,choice);o.value=i;});const chart=make('canvas',null,report);chart.width=900;chart.height=300;chart.id='economyChart';chart.setAttribute('role','img');chart.setAttribute('aria-label','Economy over battle time');const summary=make('p',null,report);
 function plot(){const samples=data[+choice.value]?.stats?.economy||[],c=chart.getContext('2d');c.fillStyle='#12251e';c.fillRect(0,0,900,300);c.strokeStyle='#718477';c.lineWidth=1;c.strokeRect(55,25,810,230);const last=samples.at(-1),max=Math.max(1,...samples.flatMap(p=>[p.earned,p.spent,p.army])),duration=Math.max(1,last?.time||state.time);c.font='13px system-ui';c.fillStyle='#e6ddc6';c.fillText('0',30,255);c.fillText(String(Math.ceil(max)),10,25);c.fillText('0s',55,278);c.fillText(Math.floor(duration)+'s',815,278);for(const [key,color,label,y,dashed]of [['earned','#7fdbd2','Earned',35,false],['spent','#efbd79','Spent',55,true],['army','#d2b5fa','Army',75,false]]){c.strokeStyle=color;c.lineWidth=2;c.setLineDash(dashed?[7,4]:[]);c.beginPath();samples.forEach((p,i)=>{const x=55+p.time/duration*810,y=255-(p[key]||0)/max*230;i?c.lineTo(x,y):c.moveTo(x,y);});c.stroke();c.setLineDash([]);c.fillStyle=color;c.fillText(label,65,y);}summary.textContent=last?`At ${Math.floor(last.time)} seconds: earned ${Math.round(last.earned)}, spent ${Math.round(last.spent)}, army value ${Math.round(last.army)}.`:'History samples appear every five seconds of battle time.';}choice.onchange=plot;plot();button('Download report JSON',report,()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({version:1,map:state.map,time:state.time,commanders:data},null,2)],{type:'application/json'})),a=make('a',null);a.href=url;a.download='kingdoms-battle-report.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});button('Close',report,()=>report.close());report.showModal();}
 button('Battle report',menu,showReport);const oldResults=showMatchResults;showMatchResults=function(...a){oldResults(...a);button('Detailed battle report',document.querySelector('.match-results'),showReport);};
 // Public discovery is opt-in. Protected lobbies are never listed.
 const pl=make('label','List my open lobby publicly',$('mpSetup')),publicToggle=make('input',null,pl);publicToggle.type='checkbox';publicToggle.id='mpPublic';const oldProfile=multiplayerProfile;multiplayerProfile=function(){return{...oldProfile(),public:publicToggle.checked};};
 const lobbyList=make('section',null,$('mpSetup'));lobbyList.id='publicLobbies';button('Browse public lobbies',$('mpSetup'),async()=>{lobbyList.replaceChildren();try{const result=await multiplayerRequest('/api/lobbies',null,{server:multiplayerServer()});if(!result.lobbies.length)make('p','No public waiting lobbies. Host one and enable public listing.',lobbyList);for(const r of result.lobbies){const row=make('div',null,lobbyList);make('span',`${r.host} · ${r.map} · ${r.players}/${r.maxPlayers}${r.teams?' · Teams':''}`,row);button('Join',row,()=>{$('mpJoinCode').value=r.code;$('mpPasscode').value='';enterMultiplayer('join');});}}catch(e){make('p',e.message,lobbyList);}});
 // Measure graphics submission separately; simulation includes nested AI and route work.
 const oldRender=render;render=function(...a){return KawBattle.profiler.measure('graphics',()=>oldRender(...a));};let scan=0,frames=0,frameAt=performance.now(),frameSum=0,worst=0,lastTime=0;const oldFrame=KawExperience.frame;KawExperience.frame=function(dt,t){oldFrame(dt,t);if(lastTime){const ms=t-lastTime;frameSum+=ms;worst=Math.max(worst,ms);frames++;}lastTime=t;scan+=dt;if(scan<.5)return;scan=0;pf.hidden=!settings.profiler;if(settings.profiler){const p=KawBattle.profiler,seconds=Math.max(.001,(performance.now()-frameAt)/1000),r=KawBattlefield.stats,avg=frames?frameSum/frames:0;pf.textContent=`${avg?Math.round(1000/avg):0} FPS · Frame ${avg.toFixed(1)} ms · Worst ${worst.toFixed(1)} ms\nSimulation ${((p.samples.simulation||0)/Math.max(1,p.calls.simulation||0)).toFixed(1)} ms/tick (includes AI/routes)\nAI ${(p.samples.ai||0).toFixed(1)} ms · Pathfinding ${(p.samples.pathfinding||0).toFixed(1)} ms / ${p.calls.pathfinding||0} routes\nGraphics ${((p.samples.graphics||0)/Math.max(1,p.calls.graphics||0)).toFixed(1)} ms/frame (CPU submission)\n${r?`${r.drawCalls} draw calls · ${Math.round(r.triangles/1000)}k triangles`:'Classic renderer'} · ${state?.entities?.length||0} entities\nLargest CPU category: ${Object.entries({graphics:p.samples.graphics||0,simulation:p.samples.simulation||0}).sort((a,b)=>b[1]-a[1])[0][0]} · ${seconds.toFixed(1)}s sample`;}
 if(performance.now()-frameAt>=2000){KawBattle.profiler.reset();frameAt=performance.now();frames=frameSum=worst=0;}};
 const oldBurst=burst;burst=function(...a){const prior=state?.effects?.length||0;oldBurst(...a);if(settings.reduced&&state)state.effects=state.effects.filter((_,i)=>i<prior||(i-prior)%3===0);};
 const symbols=['●','▲','■','◆','✚','★'];function teamSymbol(owner){const p=state.players[owner];return symbols[((p.team||owner+1)-1)%6];}
 function draw(c){if(!state)return;c.save();c.font=Math.round(11*settings.textScale)+'px system-ui';c.textAlign='center';
  if(settings.preview&&selected.length>1&&!placement&&['move','attackMove',null].includes(commandMode)){const troops=selected.filter(e=>!e.building&&e.owner===0).slice(0,200),slots=formationSlots(troops,mouse,state.formation||'box');c.setLineDash([3,4]);c.strokeStyle='#ddedb7bb';for(const slot of slots.values()){if(!inViewport(slot.x,slot.y)||!visible(slot.x,slot.y))continue;c.beginPath();c.ellipse(slot.x,slot.y-terrainHeight(slot.x,slot.y),7,4,0,0,7);c.stroke();}c.setLineDash([]);}
  for(const e of state.entities){if(!inViewport(e.x,e.y)||!sameTeam(e.owner,0)&&!visible(e.x,e.y)||e.hiddenInMine)continue;const y=e.y-renderAltitude(e);
   if(settings.ranges&&selected.includes(e)){const d=e.building?buildings[e.type]:units[e.type],radius=(d.range||0)*(e.deployed?1.25:1);if(radius){c.strokeStyle='#e9ce77aa';c.setLineDash([6,6]);c.beginPath();c.arc(e.x,e.y-terrainHeight(e.x,e.y),radius,0,Math.PI*2);c.stroke();c.setLineDash([]);}}
   if(settings.rallies&&e.owner===0&&e.rally){c.strokeStyle=state.players[0].color;c.beginPath();c.moveTo(e.x,y);c.lineTo(e.rally.x,e.rally.y-terrainHeight(e.rally.x,e.rally.y));c.stroke();c.fillStyle='#fff';c.fillText('⚑',e.rally.x,e.rally.y-terrainHeight(e.rally.x,e.rally.y));}
   if(settings.idleProduction&&e.owner===0&&e.building&&['base','barracks','forge','roost','altar'].includes(e.type)&&!e.construction&&!e.queue.length&&!e.research){c.fillStyle='#f2d58e';c.fillText('◇ IDLE',e.x,y-82);}
   if(settings.colorblind){c.fillStyle='#111c18';c.fillRect(e.x-12,y-98,24,17);c.fillStyle='#fff';c.fillText(teamSymbol(e.owner),e.x,y-85);}
   if(e.building&&!e.construction&&e.hp/e.max<.7){c.strokeStyle='#292721';c.lineWidth=e.hp/e.max<.35?3:1.5;for(let i=0;i<3;i++){const x=e.x-e.size*.6+i*e.size*.55;c.beginPath();c.moveTo(x,y-25);c.lineTo(x+7,y-15);c.lineTo(x+2,y-7);c.lineTo(x+10,y+3);c.stroke();}c.fillStyle=e.hp/e.max<.35?'#ffab7c':'#e8c88b';c.fillText(e.hp/e.max<.35?'CRITICAL DAMAGE':'DAMAGED',e.x,y-76);}
  }
  if(settings.resources)for(const r of state.resources){if(!visible(r.x,r.y)||!inViewport(r.x,r.y))continue;const initial=r.initialAmount||(r.type==='wood'?240:Math.max(6000,r.amount)),f=Math.max(0,Math.min(1,r.amount/initial)),y=r.y-terrainHeight(r.x,r.y);c.fillStyle='#17201b';c.fillRect(r.x-20,y+12,40,5);c.fillStyle=r.type==='gold'?'#edcf72':'#a3c482';c.fillRect(r.x-20,y+12,40*f,5);if(r.type==='gold'){c.fillStyle='#f4deb5';c.fillText(Math.ceil(r.amount)+' gold',r.x,y+31);}}
  for(const r of state.ruins||[]){if(!visible(r.x,r.y)||!inViewport(r.x,r.y))continue;const age=state.time-r.at,y=r.y-terrainHeight(r.x,r.y);if(!r.building){c.save();c.translate(r.x,y);c.rotate(r.facing||0);c.globalAlpha=Math.max(0,1-age/2.4);c.rotate(Math.min(.7,age/.5));c.scale(1,1-.8*Math.min(1,age/.5));if(!window.KawBattlefield.active)drawUnit3D({...r,hp:1,max:1,walkUntil:0,action:null,order:null},state.players[r.owner],state.players[r.owner].faction==='horde');c.restore();}else if(!window.KawBattlefield.active){c.fillStyle='#767263';c.strokeStyle='#282820';for(let i=0;i<7;i++){const a=i*2.399,x=r.x+Math.cos(a)*r.size*.6,y1=y+Math.sin(a)*r.size*.35,h=Math.max(4,(1-Math.min(1,age/4))*35);c.beginPath();c.moveTo(x-6,y1);c.lineTo(x+1,y1-h);c.lineTo(x+8,y1+1);c.closePath();c.fill();c.stroke();}}}
 c.restore();}
 function drawMini(){if(settings.colorblind){mc.save();mc.font='12px system-ui';mc.textAlign='center';for(const e of state.entities)if(e.type==='base'&&(sameTeam(e.owner,0)||visible(e.x,e.y))){mc.fillStyle='#fff';mc.fillText(teamSymbol(e.owner),e.x/SIZE*210,e.y/SIZE*150-5);}mc.restore();}}
 window.KawHUD={settings,draw,drawMini,showReport,apply};apply();
})();
