/* Original quality-of-life layer. Simulation rules live separately in tactics.js. */
(() => {
 const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f;}catch{return f;}};
 const settings=read('kaw-experience',{sound:true,volume:.25,fps:false,grass:true,shadows:true,fire:true,models:true});
 let objectives=true,current=null,groups={},alerts=[],previous=new Map(),scan=0,saveAt=0,recordAt=0,frames=[],frameBytes=0,replay=null,audio,voices=0,fps=60,lastFrame=0,finished=false,orderSignature='',alertSignature='';
 const make=(tag,text,parent)=>{const n=document.createElement(tag);if(text)n.textContent=text;parent?.append(n);return n;};
 const button=(text,parent,fn)=>{const b=make('button',text,parent);b.type='button';b.onclick=fn;return b;};
 // IndexedDB avoids the small localStorage quota; retain three bounded replays.
 const dbPromise=new Promise((resolve,reject)=>{const r=indexedDB.open('kaw-campaign',1);r.onupgradeneeded=()=>r.result.createObjectStore('records');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});dbPromise.catch(()=>{});
 async function store(key,value){const db=await dbPromise;return new Promise((resolve,reject)=>{const t=db.transaction('records','readwrite');t.objectStore('records').put(value,key);t.oncomplete=resolve;t.onerror=()=>reject(t.error);});}
 async function get(key){const db=await dbPromise;return new Promise((resolve,reject)=>{const r=db.transaction('records').objectStore('records').get(key);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
 const tools=make('section',null,document.querySelector('#game main'));tools.id='battleTools';
 button('Idle fighters',tools,()=>{selected=state.entities.filter(e=>e.owner===0&&!e.building&&e.type!=='worker'&&units[e.type]?.damage>0&&(!e.order||['hold','stop'].includes(e.order.kind)));updateUI();});
 button('Save game',tools,()=>save('manual'));
 button('Save replay',tools,()=>saveReplay());
 const groupBar=make('span',null,tools);let storing=false;const storeButton=button('Store group',groupBar,()=>{storing=!storing;storeButton.setAttribute('aria-pressed',storing);});
 function group(n,append=false){if(storing){groups[n]=selected.filter(e=>e.owner===0).map(e=>e.id);storing=false;storeButton.setAttribute('aria-pressed','false');toast('Group '+n+' stored');}else if(groups[n]){const members=state.entities.filter(e=>groups[n].includes(e.id)&&e.hp>0&&e.owner===0);selected=append?[...new Set([...selected,...members])]:members;updateUI();}}
 for(let n=1;n<=9;n++)button(String(n),groupBar,()=>group(n));
 const alertBox=make('aside',null,document.querySelector('#game main'));alertBox.id='attackAlerts';alertBox.setAttribute('aria-live','polite');
 const orders=make('section',null,document.querySelector('#game main'));orders.id='orderOverview';orders.hidden=true;
 const tacticalText=make('p',null,document.querySelector('.selection'));tacticalText.id='tacticalDescription';
 const fpsBox=make('span',null,tools);fpsBox.id='fpsReadout';
 const settingsBox=make('fieldset',null,$('keySettings'));make('legend','Battlefield & sound',settingsBox);
 for(const [key,label]of Object.entries({sound:'Original battle sounds',fps:'Show FPS',grass:'Wind grass',shadows:'Dynamic shadows',fire:'Detailed fire',models:'Full building model detail'})){const l=make('label',label,settingsBox),input=make('input',null,l);input.type='checkbox';input.checked=settings[key];input.onchange=()=>{settings[key]=input.checked;localStorage.setItem('kaw-experience',JSON.stringify(settings));};}
 const volumeLabel=make('label','Sound volume',settingsBox),volume=make('input',null,volumeLabel);volume.type='range';volume.min=0;volume.max=1;volume.step=.05;volume.value=settings.volume;volume.oninput=()=>{settings.volume=+volume.value;localStorage.setItem('kaw-experience',JSON.stringify(settings));};
 const manual=make('details',null,settingsBox);make('summary','New army controls & tactical rules',manual);make('p','Ctrl + 1–9 stores a group; 1–9 recalls it; Shift adds the group. Three nearby Dawnward infantry gain 5% damage and 10% protection. Dominion hits build up to five 2% damage stacks, lost after four seconds without hitting. Verdant ground troops holding for three seconds protect nearby allies by 5% and slow ground enemies by 15%. Troll spears deal 40% extra damage to flying units. Artillery deals 40% extra damage to buildings. Nearby paired ranged troops deal 15% extra damage to heavy infantry. Signal Stones take eight uncontested seconds to capture, reveal nearby terrain, and provide 7.2 gold and 4.8 lumber per minute.',manual);
 const menuTools=make('section',null,$('menu'));menuTools.id='campaignMenu';button('Saved games',menuTools,()=>list(false));button('Match replays',menuTools,()=>list(true));const ol=make('label','Neutral Signal Stones ',menuTools),oi=make('input',null,ol);oi.type='checkbox';oi.checked=true;oi.onchange=()=>objectives=oi.checked;
 const dialog=make('dialog',null,document.body);dialog.id='campaignDialog';
 async function save(slot,quiet=false){if(!state||state.networkMatch||state.replay){if(!quiet)toast('Saving is available in single-player battles.');return;}try{await store('save-'+slot,{at:Date.now(),map:state.map,time:state.time,data:KawCampaign.pack(state),uid,camera:{...cam},groups});if(!quiet)toast('Game saved on this device.');}catch{toast('Could not save: device storage is unavailable or full.');}}
 function restore(record){const s=KawCampaign.unpack(record.data);if(!s.players?.length||s.networkMatch||s.entities.some(e=>!units[e.type]&&!buildings[e.type]||!Number.isFinite(e.x)||!Number.isFinite(e.y)))throw Error('Invalid battle save.');state=s;uid=Math.max(Number.isSafeInteger(record.uid)?record.uid:1,...state.entities.flatMap(e=>[e.id,...(e.queue||[]).map(q=>q.id||0),e.research?.id||0,...(e.researchQueue||[]).map(q=>q.id||0)]));selected=[];placement=null;commandMode=null;combatIndex=null;movementIndex=null;tickObstacles=null;clearTerrainCache();actionUISignature=null;state.wallVersion++;state.blockCache={};cam.x=record.camera?.x||0;cam.y=record.camera?.y||0;paused=false;$('pause').textContent='Ⅱ Pause';$('menu').hidden=true;$('game').hidden=false;$('end').hidden=!state.ended;$('countdown').textContent='';resize();clampCam();window.KawBattlefield?.stop();current=state;previous.clear();alerts=[];frames=[];frameBytes=0;saveAt=recordAt=state.time;groups=record.groups||{};fog();updateUI();}
 async function list(isReplay){dialog.replaceChildren();make('h2',isReplay?'Saved match reviews':'Saved single-player battles',dialog);try{const keys=isReplay?['replay-0','replay-1','replay-2']:['save-manual','save-auto'];let count=0;for(const k of keys){const r=await get(k);if(!r)continue;count++;button(`${r.map} · ${Math.floor(r.time/60)} min · ${new Date(r.at).toLocaleString()}`,dialog,()=>{if(state&& !$('game').hidden&&!confirm('Load this battle? Current progress will be lost.'))return;try{if(isReplay)openReplay(r);else restore(r);dialog.close();}catch(e){toast(e.message);}});}if(!count)make('p','Nothing saved yet on this device.',dialog);}catch{make('p','Device storage is unavailable.',dialog);}button('Close',dialog,()=>dialog.close());dialog.showModal();}
 // Replays are sampled visual reviews, not a second simulation. No orders are run.
 async function saveReplay(quiet=false){if(!frames.length)return;try{for(let i=2;i>0;i--){const old=await get('replay-'+(i-1));if(old)await store('replay-'+i,old);}await store('replay-0',{at:Date.now(),map:state.map,time:state.time,frames:frames.slice()});if(!quiet)toast('Visual replay saved.');}catch{toast('Could not save replay to this device.');}}
 const replayBar=make('section',null,$('game'));replayBar.id='replayBar';replayBar.hidden=true;const play=button('Play',replayBar,()=>{replay.playing=!replay.playing;play.textContent=replay.playing?'Pause':'Play';});const speed=make('select',null,replayBar);for(const v of [.5,1,2,4]){const o=make('option',v+'×',speed);o.value=v;o.selected=v===1;}const seek=make('input',null,replayBar);seek.type='range';seek.min=0;seek.step=.1;seek.oninput=()=>{replay.time=+seek.value;applyReplay();};const reviewStats=make('span',null,replayBar);button('Exit replay',replayBar,()=>{replay=null;replayBar.hidden=true;state=null;paused=false;$('game').hidden=true;$('menu').hidden=false;});
 function openReplay(r){if(state?.networkMatch&&!$('game').hidden)throw Error('Leave the multiplayer battle before opening a replay.');if(!r.frames?.length)throw Error('Replay has no frames.');restore({data:structuredClone(r.frames[0].data),camera:{x:0,y:0}});replay={frames:r.frames,time:r.frames[0].time,playing:false};seek.min=replay.time;seek.max=r.frames.at(-1).time;replayBar.hidden=false;paused=true;applyReplay();}
 function applyReplay(){let index=0;while(index+1<replay.frames.length&&replay.frames[index+1].time<=replay.time)index++;if(replay.index!==index){Object.assign(state,KawCampaign.unpack(structuredClone(replay.frames[index].data)));replay.index=index;combatIndex=null;movementIndex=null;tickObstacles=null;}const first=replay.frames[index],second=replay.frames[index+1],alpha=second?Math.max(0,Math.min(1,(replay.time-first.time)/(second.time-first.time))):0,right=new Map((second?.data.state.entities||[]).map(e=>[e.id,e]));for(let i=0;i<state.entities.length;i++){const e=state.entities[i],left=first.data.state.entities[i],next=right.get(e.id);if(left&&next&&!e.building){e.x=left.x+(next.x-left.x)*alpha;e.y=left.y+(next.y-left.y)*alpha;}}state.time=replay.time;state.replay=true;paused=true;selected=[];state.count=0;state.ended=false;seek.value=replay.time;const p=state.players[0],stats=p.stats||{};reviewStats.textContent=`${Math.floor(replay.time)}s · Gold ${Math.round(p.gold)} · Lumber ${Math.round(p.wood)} · Army ${state.entities.filter(e=>e.owner===0&&!e.building&&e.type!=='worker').length} · Worker idle ${Math.round(stats.workerIdle||0)}s`;}
 // Browser-generated timbres: no third-party recordings or samples.
 function tone(kind,e){if(window.KawBattleAudio)return window.KawBattleAudio.play(kind,e);if(!settings.sound||!audio||audio.state!=='running'||voices>=12)return;voices++;const now=audio.currentTime,osc=audio.createOscillator(),gain=audio.createGain();const pitches={attack:130,gather:250,build:330,step:75,alert:650,destroy:45};const weapon=e?.type,spell=weapon&&['hero','hero2','hero3','air2','air3','trapper'].includes(weapon);osc.type=kind==='attack'?(spell?'sine':weapon==='ranged'?'triangle':'sawtooth'):'triangle';osc.frequency.setValueAtTime(kind==='attack'?(spell?420:weapon==='sniper'?85:weapon==='siege'?45:weapon==='ranged'?520:130):pitches[kind]||220,now);osc.frequency.exponentialRampToValueAtTime(35,now+.12);gain.gain.setValueAtTime(settings.volume*.12,now);gain.gain.exponentialRampToValueAtTime(.001,now+.15);osc.connect(gain).connect(audio.destination);osc.start(now);osc.stop(now+.16);osc.onended=()=>{voices--;osc.disconnect();gain.disconnect();};}
 document.addEventListener('pointerdown',()=>{if(!audio&&settings.sound){const C=window.AudioContext||window.webkitAudioContext;if(C)audio=new C();}audio?.resume().catch(()=>{});},{passive:true});
 const oldQueue=queueTask;queueTask=function(...args){if(state?.replay)return;return oldQueue(...args);};const oldTrain=train;train=function(...args){if(state?.replay)return;return oldTrain(...args);};const oldUpgrade=upgrade;upgrade=function(...args){if(state?.replay)return;return oldUpgrade(...args);};const oldBuild=build;build=function(...args){if(state?.replay)return false;return oldBuild(...args);};
 const oldExit=$('exit').onclick;$('exit').onclick=()=>{const result=oldExit();if(result!==false){replay=null;replayBar.hidden=true;}return result;};
 const oldKey=window.onkeydown;window.onkeydown=e=>{if(!['INPUT','TEXTAREA','SELECT'].includes(e.target?.tagName)&&!$('keySettings').open&&state&&!state.replay&&/^[1-9]$/.test(e.key)&&!e.altKey&&!e.metaKey){if(e.ctrlKey){e.preventDefault();storing=true;group(+e.key);return;}if(groups[e.key]){e.preventDefault();group(+e.key,e.shiftKey);return;}}oldKey?.(e);};
 function addAlert(e){const prior=alerts.find(a=>Math.hypot(a.x-e.x,a.y-e.y)<250&&state.time-a.at<6);if(prior)return;alerts.push({x:e.x,y:e.y,at:state.time,label:e.building?'Building under attack':'Troops under attack'});alerts=alerts.slice(-3);tone('alert',e);}
 function updateAlerts(){const signature=alerts.map(a=>a.at+':'+a.x).join('|');if(signature===alertSignature)return;alertSignature=signature;alertBox.replaceChildren();for(const a of alerts)button(a.label,alertBox,()=>{cam.x=a.x-viewport.width/2;cam.y=a.y-viewport.height/2;clampCam();});}
 function frame(dt,t){if(lastFrame)fps=fps*.92+(1000/Math.max(1,t-lastFrame))*.08;lastFrame=t;fpsBox.hidden=!settings.fps;fpsBox.textContent=Math.round(fps)+' FPS';if(replay){paused=true;if(replay.playing){replay.time=Math.min(+seek.max,replay.time+dt*+speed.value);applyReplay();if(replay.time>=+seek.max){replay.playing=false;play.textContent='Play';}}return;}if(!state)return;const session=state.networkMatch?'online:'+multiplayer.session?.code:state;if(current!==session){current=session;previous.clear();alerts=[];frames=[];frameBytes=0;groups={};recordAt=state.time;saveAt=state.time;finished=false;}scan+=dt;if(scan<.25)return;scan=0;let sounds=0;const next=new Map();for(const e of state.entities){if(e.owner===0){const old=previous.get(e.id);if(old&&old.hp>e.hp)addAlert(e);next.set(e.id,{hp:e.hp,x:e.x,y:e.y,building:e.building});}if((e.owner===0||visible(e.x,e.y))&&inViewport(e.x,e.y)&&sounds<4){const old=previous.get('sound-'+e.id),action=e.action?.until;if(action&&old!==action){tone(e.action.kind,e);sounds++;}if(!action&&e.walkUntil>state.time&&e.owner===0&&sounds<2&&Math.floor(state.time*2)!==previous.get('step-'+e.id)){tone('step',e);sounds++;}next.set('step-'+e.id,Math.floor(state.time*2));next.set('sound-'+e.id,action);}}for(const [id,e]of previous)if(typeof id==='number'&&!next.has(id)){addAlert(e);tone('destroy');}previous=next;alerts=alerts.filter(a=>state.time-a.at<12);updateAlerts();
 tacticalText.textContent=selected.length===1?globalThis.KawTactics?.description(selected[0])||'':'';orders.hidden=selected.length<2;const signature=selected.map(e=>e.id+':'+e.order?.kind+':'+(e.tasks||[]).map(t=>t.kind).join(',')).join('|');if(signature!==orderSignature){orderSignature=signature;orders.replaceChildren();if(!orders.hidden){make('strong','Selected orders',orders);for(const e of [...selected].sort((a,b)=>a.type.localeCompare(b.type)).slice(0,24))make('span',`${names[state.players[e.owner].faction]?.[e.type]||e.type}: ${({move:'↗',attackMove:'⚔↗',attack:'⚔',gather:'⛏',deliver:'▣',build:'⚒',hold:'⏸',stop:'■'})[e.order?.kind]||'○'} ${e.order?.kind||'idle'}${e.tasks?.length?' → '+e.tasks.slice(0,4).map(o=>o.kind).join(' → '):''}`,orders);if(selected.length>24)make('span',`+ ${selected.length-24} additional units`,orders);}}
 if(!state.networkMatch&&state.time-saveAt>=60&&!state.ended){saveAt=state.time;save('auto',true);}if(!state.networkMatch&&state.time-recordAt>=5){recordAt=state.time;const data=KawCampaign.pack(state),bytes=JSON.stringify(data).length;frames.push({time:state.time,data,bytes});frameBytes+=bytes;while(frames.length>180||frameBytes>8000000){frameBytes-=frames.shift().bytes;}}if(state.ended&&!finished){finished=true;saveReplay(true);}
 }
 function drawMini(c){for(const a of alerts){c.strokeStyle='#ff695c';c.lineWidth=2;c.beginPath();c.arc(a.x/SIZE*210,a.y/SIZE*150,4+(state.time-a.at)%1*6,0,Math.PI*2);c.stroke();}}
 window.KawExperience={frame,drawMini,settings,get objectives(){return objectives;}};
})();
