'use strict';
// All sprites use the same Frontier mesh renderer, PBR light rig, and painted material maps.
const ART_VERSION='20261009-stone-and-web',WORLD_ART_VERSION=ART_VERSION;
const frontierSheets={},frontierWorld={},frontierSheetUsage=new Map();let frontierCleanupTime=0;
// Wider framing prevents weapons/wings being clipped; restore their world scale.
const frontierFramingScale={shieldwarden:320/205,trapper:300/205,'cov-shellguard':350/205,'cov-archer':270/205,'cov-resin':350/205,'cov-captain':280/205,'cov-burrower':250/205,bogbreaker:330/205,carrion:340/205,'cov-moth':340/205,'cov-wasp':1,'cov-wasp-venom':1,'cov-centipede':1,knight:280/205,marksman:280/205,witch:280/205,devoured:370/255,shaman:285/205,gryphon:340/205,wyvern:340/205,phoenix:340/270,dragon:340/270,pig:280/205};
function getFrontierSheet(name){if(!name)return null;const now=Date.now();frontierSheetUsage.set(name,now);if(now>frontierCleanupTime){frontierCleanupTime=now+5000;for(const [key,last]of frontierSheetUsage)if(now-last>45000){delete frontierSheets[key];frontierSheetUsage.delete(key);}}if(!frontierSheets[name]){const img=new Image();img.src='assets/frontier-'+name+'.webp?v='+ART_VERSION;frontierSheets[name]=img;}return frontierSheets[name];}
for(const name of ['gold','tree','pine','mountain','construction1','construction2','construction3','wall','tower','bastion','base','base-level2','base-level3','base-level4','barracks','forge','roost','altar','mill','armory','foundry','depot'])for(const horde of ['gold','tree','pine','mountain','construction1','construction2','construction3'].includes(name)?[false]:[false,true]){const key=name+(horde?'-dominion':''),img=new Image();img.onload=()=>{if(typeof terrainLayer!=='undefined')terrainLayer=null;};img.src='assets/world-'+key+'.webp?v='+WORLD_ART_VERSION;frontierWorld[key]=img;}
function frontierAppearance(type,race,owner){return unitAppearance(type,race,owner);}
function drawFrontierUnit(e,p,horde){
 if(e.burrowUntil>state.time){ctx.fillStyle='#806842';ctx.beginPath();ctx.ellipse(0,0,28,14,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#bca77a';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(0,0,21,9,0,0,Math.PI*2);ctx.stroke();return true;}
 let name=e.type==='air2'&&p.faction==='covenant'&&e.venomStinger?'cov-wasp-venom':frontierAppearance(e.type,p.faction,e.owner);
 if(e.type==='worker'){if(e.cargoGold>0)name+='-carry';else if(e.cargoWood>0&&e.order?.kind==='deliver')name+='-logs';else if(['repair','build'].includes(e.order?.kind))name+='-hammer';else if(e.order?.target?.type==='gold')name+='-pick';}
 const img=getFrontierSheet(name);if(!img?.complete||!img.naturalWidth)return false;
 const {action,progress,phase,dir,frame}=frontierFrame(e,state.time),baseWidth=p.faction==='covenant'&&e.type==='melee'?64:p.faction==='covenant'&&e.type==='sniper'?78:p.faction==='covenant'&&e.type==='ranged'?50:e.type==='beetle'?82:e.type==='bogbreaker'?70:e.type==='scout'&&p.faction!=='human'?70:e.type==='shieldwarden'?54:e.type==='pig'?84:e.type==='air2'?92:e.type==='air'?76:e.type==='siege'?68:e.type==='hero3'&&horde?96:isHeroType(e.type)?58:e.type==='ranged'&&horde?54:e.type==='cavalier'?82:e.type==='devoured'?64:e.type==='melee'?48:44,width=baseWidth*(frontierFramingScale[name]||1)*unitVisualScale(e),height=width*4/3,displayHeight=baseWidth*4/3*unitVisualScale(e);
 ctx.save();if(e.type==='air2'&&p.faction==='human'){ctx.shadowColor='#ff9846';ctx.shadowBlur=7;}
 if(e.type==='air2'&&p.faction==='human'){for(let i=0;i<8;i++){const a=state.time*7+i;ctx.fillStyle=i%2?'#e93624':'#ff6b32';ctx.beginPath();ctx.moveTo(Math.sin(a)*22,6);ctx.lineTo(Math.sin(a)*22+4,-12-Math.sin(a*1.2)*8);ctx.lineTo(Math.sin(a)*22+8,6);ctx.fill();}}ctx.drawImage(img,frame*144,(phase*8+dir)*192,144,192,-width/2,-(height+displayHeight)/2+13,width,height);ctx.restore();
 // Equipment is part of the hand hierarchy in every frame, with no flat tool/weapon overlays.
 ctx.fillStyle=p.color;ctx.strokeStyle='#10212a';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(-5,-displayHeight+11);ctx.lineTo(5,-displayHeight+11);ctx.lineTo(0,-displayHeight+18);ctx.closePath();ctx.fill();ctx.stroke();
 if(isHeroType(e.type)){ctx.strokeStyle='#edcf82';ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(-7,-displayHeight+23);ctx.lineTo(-7,-displayHeight+15);ctx.lineTo(-3,-displayHeight+20);ctx.lineTo(0,-displayHeight+14);ctx.lineTo(3,-displayHeight+20);ctx.lineTo(7,-displayHeight+15);ctx.lineTo(7,-displayHeight+23);ctx.closePath();ctx.stroke();}if(e.hitUntil>state.time){ctx.strokeStyle='#fff0b1';ctx.beginPath();ctx.ellipse(0,-displayHeight*.48,13,displayHeight*.3,0,0,Math.PI*2);ctx.stroke();}
 if(action&&['melee','worker','devoured','cavalier','beetle','bogbreaker','shieldwarden'].includes(e.type)){ctx.save();ctx.rotate(e.facing||0);ctx.globalAlpha=Math.max(0,Math.sin(progress*Math.PI));ctx.strokeStyle=horde?'#ffba80':'#fff0aa';ctx.lineWidth=2;ctx.beginPath();ctx.arc(2,-8,23,-1.2+progress*2.8,-.4+progress*2.8);ctx.stroke();ctx.restore();}
 return true;
}
function frontierFrame(e,time){const action=e.action&&e.action.until>time?e.action:null,walking=e.walkUntil>time,phase=action?2:walking?1:0,dir=(Math.round((e.facing||0)/(Math.PI/4))+8)%8;const progress=action?1-(action.until-time)/action.duration:(time+(e.id%8)*.07)*(walking?1.7:.4);return {action,progress,phase,dir,frame:action?Math.min(15,Math.max(0,Math.floor(progress*16))):Math.floor(progress*16)%16};}
function worldSprite(name,width,height=width,g=ctx){const img=frontierWorld[name];if(!img?.complete||!img.naturalWidth)return false;g.drawImage(img,-width/2,-height*.64,width,height);return true;}
function drawFrontierBuilding(e,p,horde){if(['trap','barricade'].includes(e.type))return worldSprite(e.type+'-covenant',e.type==='trap'?44:70);const level=Math.min(4,e.level||1),asset=e.type==='base'&&level>1?'base-level'+level:e.type;const width=e.type==='base'?(level===1?210:240+level*15):e.type==='wall'?58:['tower','roost','altar'].includes(e.type)?145:135;if(!worldSprite(asset+worldFactionSuffix(p.faction),width))return false;
 ctx.fillStyle=p.color;ctx.strokeStyle='#163039';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(-6,-width*.65);ctx.lineTo(8,-width*.65+4);ctx.lineTo(-6,-width*.65+10);ctx.closePath();ctx.fill();ctx.stroke();
 if(['forge','foundry'].includes(e.type)){ctx.save();for(let i=0;i<3;i++){const t=(state.time*.25+i/3)%1;ctx.globalAlpha=(1-t)*.25;ctx.fillStyle='#d2d7cb';ctx.beginPath();ctx.ellipse(-22+t*12,-width*.48-t*30,5+t*9,5+t*7,0,0,Math.PI*2);ctx.fill();}ctx.restore();}return true;
}
function drawFrontierResource(r){ctx.save();ctx.translate(r.x,r.y);ctx.fillStyle='#13271e55';ctx.beginPath();ctx.ellipse(4,8,r.type==='gold'?27:17,9,0,0,Math.PI*2);ctx.fill();const result=worldSprite(r.type==='gold'?'gold':Math.floor(r.x+r.y)%3?'pine':'tree',r.type==='gold'?114:104);if(r.type==='gold'&&result){const miners=state.entities.filter(w=>w.hp>0&&w.hiddenInMine&&w.order?.target===r).length;ctx.fillStyle='#17281de8';ctx.fillRect(-27,14,54,14);ctx.fillStyle=miners>=5?'#ffd487':'#d8e1c7';ctx.font='9px system-ui';ctx.textAlign='center';ctx.fillText(miners+'/5 miners',0,24);}ctx.restore();return result;}
function drawFrontierMountain(g,m){g.save();g.translate(m.x,m.y);const result=worldSprite('mountain',m.half*4,m.half*4,g);g.restore();return result;}
function drawFrontierConstruction(e){const progress=1-e.construction.left/e.construction.total,race=state.players[e.owner].faction,width=e.type==='base'?210:e.type==='wall'?58:135;if(!frontierWorld['construction1']?.naturalWidth)return false;
 ctx.save();ctx.globalAlpha=.18+progress*.65;worldSprite(e.type+worldFactionSuffix(race),width);ctx.restore();worldSprite('construction'+(progress<.33?1:progress<.7?2:3),width);
 ctx.fillStyle='#172a24';ctx.fillRect(-e.size,-width*.65,e.size*2,6);ctx.fillStyle='#e1c17d';ctx.fillRect(-e.size,-width*.65,e.size*2*progress,6);ctx.fillStyle='#e6d4ac';ctx.font='10px system-ui';ctx.textAlign='center';ctx.fillText(buildingName(e.type,e.owner)+' · '+Math.ceil(e.construction.left)+'s'+(e.construction.active?'':' · waiting'),0,25);return true;
}

function worldFactionSuffix(race){return race==='horde'?'-dominion':race==='covenant'?'-covenant':'';}
for(const name of ['wall','tower','bastion','base','base-level2','base-level3','base-level4','barracks','forge','roost','altar','mill','armory','foundry','depot','trap','barricade']){const key=name+'-covenant',img=new Image();img.src='assets/world-'+key+'.webp?v='+WORLD_ART_VERSION;frontierWorld[key]=img;}
