/* Browser presentation and device-local settings. No external services or assets. */
(() => {
 const make=(tag,text,parent)=>{const n=document.createElement(tag);if(text)n.textContent=text;parent?.append(n);return n;};
 const button=(text,parent,fn)=>{const b=make('button',text,parent);b.type='button';b.onclick=fn;return b;};
 const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))||fallback;}catch{return fallback;}};
 const save=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value));}catch{}};
 const options={resources:[[100,'100 each · standard'],[300,'300 each'],[600,'600 each']],speed:[[.75,'Slow · 0.75×'],[1,'Normal · 1×'],[1.5,'Fast · 1.5×']],supply:[[50,'50'],[100,'100'],[200,'200']],victory:[['strongholds','Destroy opposing Strongholds'],['elimination','Eliminate all opposing units and buildings'],['domination','Hold every Signal Stone for 120 seconds'],['convoy','Escort three supply convoys to their depots']]};
 const labels={resources:'Starting gold and lumber',speed:'Game speed',supply:'Maximum supply',victory:'Victory condition'};
 function select(id,label,parent,choices,value){const l=make('label',label,parent),s=make('select',null,l);s.id=id;for(const [v,text]of choices){const o=make('option',text,s);o.value=v;}s.value=value;return s;}
 $('menu').append($('bannerWorkshop'));$('bannerWorkshop').style.position='static';
 const settings=KawRules.normalize(read('kaw-skirmish',KawRules.defaults));
 window.KawSkirmish={settings};
 const dialog=make('dialog',null,document.body);dialog.id='skirmishSetup';make('h2','Skirmish setup',dialog);make('p','Configure your next battle. Supply Houses still raise supply up to the selected maximum. Domination also ends when only one side has a Stronghold. Convoy race: escort automatic wagons to their marked depots; three deliveries win.',dialog);
 for(const key of Object.keys(options)){const s=select('skirmish-'+key,labels[key],dialog,options[key],settings[key]);s.onchange=()=>{settings[key]=key==='victory'?s.value:+s.value;save('kaw-skirmish',settings);};}
 const teams=make('fieldset',null,dialog);make('legend','Single-player teams',teams);const teamChoices=[[0,'Free for all'],[1,'Team 1'],[2,'Team 2'],[3,'Team 3'],[4,'Team 4'],[5,'Team 5'],[6,'Team 6']],savedTeams=read('kaw-skirmish-teams',{});
 for(let i=0;i<6;i++){const s=select('skirmish-team-'+i,i?'Opponent '+i:'Your team',teams,teamChoices,savedTeams[i]||0);s.onchange=()=>{savedTeams[i]=+s.value;save('kaw-skirmish-teams',savedTeams);};}
 button('Done',dialog,()=>dialog.close());button('Skirmish setup',$('menu'),()=>dialog.showModal()).id='openSkirmish';
 const roster=singlePlayerRoster;singlePlayerRoster=function(){return roster().map((p,i)=>({...p,team:savedTeams[i?Number(p.name?.match(/\d+/)?.[0])||i:0]||0}));};
 const startBattle=start;start=function(o){const players=o?.players||singlePlayerRoster();if(new Set(players.map((p,i)=>p.team?'team:'+p.team:'player:'+i)).size<2){toast('Choose at least two opposing teams in Skirmish setup.');return;}return startBattle(o);};
 const mpFields=make('fieldset',null,$('mpSetup'));make('legend','Host match settings',mpFields);const mpInputs={};
 for(const key of Object.keys(options))mpInputs[key]=select('mp-rule-'+key,labels[key],mpFields,options[key],KawRules.defaults[key]);
 const takeoverLabel=make('label','Let AI temporarily control disconnected players after 15 seconds',mpFields),takeover=make('input',null,takeoverLabel);takeover.type='checkbox';takeover.id='mpAiTakeover';
 const mpRules=()=>Object.fromEntries(Object.keys(options).map(key=>[key,key==='victory'?mpInputs[key].value:+mpInputs[key].value]));
 const profile=multiplayerProfile;multiplayerProfile=function(){return {...profile(),rules:mpRules(),aiTakeover:takeover.checked};};
 const roomInfo=make('p',null,$('mpRoom'));roomInfo.id='mpRulesSummary';
 const check=button('Request ready check · 30s',document.querySelector('#mpRoom .mp-buttons'),async()=>{try{const data=await multiplayerRequest('/api/lobbies/'+multiplayer.session.code,{action:'readyCheck'});renderMultiplayerLobby(data.room,multiplayer.you);}catch(e){multiplayerStatus(e.message);}});check.id='mpReadyCheck';
 const lobby=renderMultiplayerLobby;renderMultiplayerLobby=function(room,you){lobby(room,you);const me=room.members.find(m=>m.id===you),rules=room.rules||KawRules.defaults;roomInfo.textContent=`${rules.resources} gold/lumber · ${rules.speed}× speed · ${rules.supply} max supply · ${options.victory.find(o=>o[0]===rules.victory)?.[1]}${room.aiTakeover?' · Temporary AI control enabled':''}`;check.hidden=!me?.host||room.phase!=='waiting';if(room.readyCheckDeadline)multiplayerStatus('Ready check: '+Math.max(0,Math.ceil((room.readyCheckDeadline-Date.now())/1000))+'s remaining. Confirm using Ready.');const rows=$('mpMembers').children;room.members.forEach((m,i)=>{if(m.aiControl&&rows[i])make('small',' · AI temporarily controlling this player',rows[i]);});};
 const connection=make('div',null,document.querySelector('#game main'));connection.id='connectionWarning';connection.hidden=true;connection.setAttribute('role','status');
 const objective=make('div',null,document.querySelector('#game main'));objective.id='dominationStatus';objective.hidden=true;
 // Draw only gameplay-visible statuses; selection reveals friendly aura boundaries.
 function conditions(e){const out=[];if(e.burn?.left>0)out.push({label:e.burn.poison?'VENOM':'FIRE',color:e.burn.poison?'#a7e380':'#ffc180',left:e.burn.left});if(e.slowUntil>state.time||e.webSlowUntil>state.time)out.push({label:'SLOW',color:'#ade0f3',left:Math.max(e.slowUntil||0,e.webSlowUntil||0)-state.time});if(e.shieldUntil>state.time||e.standfast||e.rootward)out.push({label:'GUARD',color:'#f4e1a0',left:e.shieldUntil>state.time?e.shieldUntil-state.time:0});if(e.stunUntil>state.time)out.push({label:'STUN',color:'#eee',left:e.stunUntil-state.time});return out;}
 const hudDraw=KawHUD.draw;KawHUD.draw=function(c){hudDraw(c);c.save();c.font='bold 10px system-ui';c.textAlign='center';for(const e of state.entities){if(e.hp<=0||e.hiddenInMine||!visible(e.x,e.y)||!inViewport(e.x,e.y,80))continue;const statuses=conditions(e);for(let i=0;i<Math.min(3,statuses.length);i++){c.fillStyle='#102018e8';c.fillRect(e.x-13+i*12,e.y-renderAltitude(e)-48,11,14);c.fillStyle=statuses[i].color;c.fillText(statuses[i].label[0],e.x-7+i*12,e.y-renderAltitude(e)-37);}}for(const e of selected){if(e.owner!==0||e.building)continue;const radius=isHeroType(e.type)?190:isBannerBearer(e)?BANNER_AURA_RADIUS:e.type==='shieldwarden'?100:e.type==='medic'?150:0;if(radius){c.strokeStyle=state.players[e.owner].color+'aa';c.setLineDash([6,5]);c.beginPath();c.arc(e.x,e.y-terrainHeight(e.x,e.y),radius,0,Math.PI*2);c.stroke();}}c.restore();};
 const register=registerCommand;registerCommand=function(b,label,fn,opts){register(b,label,fn,opts);if(opts.commandId)b.dataset.command=opts.commandId;};
 const statusBox=make('section',null,$('selectionStats'));statusBox.id='frontlineConditions';
 const ui=updateUI;updateUI=function(){ui();const e=selected[0];const current=$('frontlineConditions')||make('section',null,$('selectionStats'));current.id='frontlineConditions';current.replaceChildren();if(!e||!state)return;for(const status of conditions(e)){const n=make('span',status.label+(status.left?' '+Math.ceil(status.left)+'s':''),current);n.style.borderColor=status.color;}for(const [id,ready,total]of [['unitAbility',e.unitAbilityReady,abilityDefinition(e)?.cooldown||20],['basePower',e.abilityReady,20]]){const b=document.querySelector('#actions [data-command="'+id+'"]');if(!b)continue;let meter=b.querySelector('progress');if(!meter)meter=make('progress',null,b);meter.max=total;meter.value=Math.max(0,total-Math.max(0,(ready||0)-state.time));meter.setAttribute('aria-label',Math.max(0,Math.ceil((ready||0)-state.time))+' seconds until ready');}};
 // Bounded device-local balance data; never transmitted automatically.
 let records=read('kaw-balance-history',[]),recorded=new Set();if(!Array.isArray(records))records=[];
 const report=make('dialog',null,document.body);report.id='balanceReport';make('h2','Balance notebook',report);make('p','Completed matches on this device only. Win rates are descriptive, not proof of faction balance. Human commanders and AI are reported separately. No data is uploaded.',report);const table=make('div',null,report);
 function renderBalance(){table.replaceChildren();const t=make('table',null,table),head=make('tr',null,t);for(const label of ['Faction / control','Matches','Win rate','Average length','Most trained fighters'])make('th',label,head);for(const faction of Object.keys(KawBattle.profiles))for(const ai of [false,true]){const rows=records.flatMap(r=>r.players.map(p=>({...p,duration:r.duration}))).filter(p=>p.faction===faction&&p.ai===ai);if(!rows.length)continue;const usage={};for(const p of rows)for(const [type,n]of Object.entries(p.trained||{}))if(type!=='worker')usage[type]=(usage[type]||0)+n;const tr=make('tr',null,t);for(const v of [factionName(faction)+' / '+(ai?'AI':'Human'),rows.length,Math.round(rows.filter(r=>r.won).length/rows.length*100)+'%',formatGameTime(rows.reduce((n,r)=>n+r.duration,0)/rows.length),Object.entries(usage).sort((a,b)=>b[1]-a[1]).slice(0,3).map(([type,n])=>(names[faction][type]||type)+' '+n).join(', ')||'None'])make('td',String(v),tr);}if(!records.length)make('p','Finish a skirmish to record your first match.',table);}
 button('Export balance data',report,()=>download('kingdoms-balance.json',{version:1,matches:records}));button('Clear local history',report,()=>{if(confirm('Clear the balance notebook on this device?')){records=[];save('kaw-balance-history',records);renderBalance();}});button('Close',report,()=>report.close());button('Balance notebook',$('menu'),()=>{renderBalance();report.showModal();}).id='openBalance';
 function download(filename,data){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=make('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 let session=null,completed=false,scan=0,oldEntities=new Map();
 const frame=KawExperience.frame;KawExperience.frame=function(dt,t){frame(dt,t);if(!state){connection.hidden=objective.hidden=true;return;}const key=state.networkMatch?'online:'+multiplayer.session?.code:state;if(session!==key){session=key;completed=false;oldEntities=new Map(state.entities.map(e=>[e.id,{construction:!!e.construction,owner:e.owner}]));}
  connection.hidden=!multiplayer.active||!multiplayer.errors&&!multiplayer.room?.members.some(m=>!m.ai&&!m.connected&&!m.left);if(!connection.hidden){const elapsed=(performance.now()-(state.networkReceivedAt||performance.now()))/1000;connection.textContent=multiplayer.errors?'Connection lost · reconnecting · approximately '+Math.max(0,Math.ceil(300-elapsed))+'s left to recover your seat.':multiplayer.room.members.filter(m=>!m.ai&&!m.connected&&!m.left).map(m=>m.name+': '+m.reconnectSeconds+'s to reconnect'+(m.aiControl?' · AI control':'')).join(' · ');}
  objective.hidden=state.rules?.victory!=='domination';if(!objective.hidden)objective.textContent=state.domination?.team?'Signal Stones held · '+Math.floor(state.domination.held)+' / 120s':'Domination: hold every Signal Stone for 120 seconds';
  scan+=dt;if(scan>=.25){scan=0;for(const e of state.entities){const old=oldEntities.get(e.id);if(e.owner===0){if(old?.construction&&!e.construction)KawBattleAudio.play('complete',e);else if(!old&&!e.building)KawBattleAudio.play('ready',e);}oldEntities.set(e.id,{construction:!!e.construction,owner:e.owner});}if(oldEntities.size>state.entities.length+250){const ids=new Set(state.entities.map(e=>e.id));for(const id of oldEntities.keys())if(!ids.has(id))oldEntities.delete(id);}}
  if(state.ended&&!completed&&!state.replay&&!state.tutorial&&!state.campaign&&!state.spectating){completed=true;const id=state.networkMatch?multiplayer.session?.code:Date.now()+':'+Math.random();if(recorded.has(id)||records.some(record=>record.id===id))return;recorded.add(id);const rows=state.networkMatch?state.matchStats:state.players.map(p=>({name:p.name,faction:p.faction,stats:p.stats}));const players=state.players.map((p,i)=>{const stats=rows?.[i]?.stats||p.stats||{};return{faction:p.faction,ai:!!(p.initialAI??p.ai),won:state.winnerKeys?state.winnerKeys.includes(p.team?'team:'+p.team:'player:'+i):i===0&&state.result==='VICTORY',trained:stats.trainedByType||{},lost:stats.lostByType||{}};});if(state.networkMatch&&!state.winnerKeys)players.splice(1);records.push({id,map:state.map,duration:state.time,rules:state.rules,players});records=records.slice(-50);save('kaw-balance-history',records);}
 };
 // Layered, original synthesized effects with faction timbres and stereo placement.
 let audio,noise,voices=0,lastCue=0,lastAck=0;
 function initAudio(){if(!KawExperience.settings.sound)return;const C=window.AudioContext||window.webkitAudioContext;if(!C)return;if(!audio){audio=new C();noise=audio.createBuffer(1,audio.sampleRate*.3,audio.sampleRate);const d=noise.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*(1-i/d.length);}audio.resume().catch(()=>{});}
 document.addEventListener('pointerdown',initAudio,{passive:true});
 function play(kind,e){if(kind==='ack'&&read('kaw-atmosphere',{}).acks===false)return;if(!audio||audio.state!=='running'||!KawExperience.settings.sound||voices>=12)return;if(['ready','complete'].includes(kind)&&performance.now()-lastCue<500)return;if(['ready','complete'].includes(kind))lastCue=performance.now();const faction=state?.players[e?.owner||0]?.faction||'human',pitch=faction==='horde'?100:faction==='covenant'?280:190,duration=kind==='alert'?.4:kind==='destroy'?.32:.18,at=audio.currentTime,gain=audio.createGain();gain.gain.setValueAtTime(Math.max(.001,KawExperience.settings.volume*.16),at);gain.gain.exponentialRampToValueAtTime(.001,at+duration);let output=gain;if(audio.createStereoPanner){const pan=audio.createStereoPanner();pan.pan.value=e?Math.max(-.8,Math.min(.8,(e.x-cam.x)/viewport.width*1.6-.8)):0;gain.connect(pan);pan.connect(audio.destination);output=pan;}else gain.connect(audio.destination);const oscillator=audio.createOscillator();oscillator.type=faction==='horde'?'sawtooth':faction==='covenant'?'sine':'triangle';let frequency=kind==='alert'?e?.type==='worker'?820:620:kind==='attack'?['siege','bastion'].includes(e?.type)?45:e?.type==='sniper'?75:pitch:kind==='destroy'?45:kind==='gather'?pitch*1.3:kind==='ack'?pitch:kind==='ready'||kind==='complete'?pitch*2:pitch;oscillator.frequency.setValueAtTime(frequency,at);oscillator.frequency.exponentialRampToValueAtTime(Math.max(30,frequency*(kind==='ready'||kind==='complete'?1.5:.55)),at+duration);oscillator.connect(gain);oscillator.start();oscillator.stop(at+duration);voices++;const noisy=['attack','gather','destroy'].includes(kind);let source,filter;if(noisy){source=audio.createBufferSource();source.buffer=noise;filter=audio.createBiquadFilter();filter.type='lowpass';filter.frequency.value=e?.type==='siege'?180:kind==='gather'?1100:faction==='horde'?800:1800;source.connect(filter).connect(gain);source.start();source.stop(at+duration);}oscillator.onended=()=>{voices--;oscillator.disconnect();source?.disconnect();filter?.disconnect();gain.disconnect();if(output!==gain)output.disconnect();};}
 window.KawBattleAudio={play};const queue=queueTask;queueTask=function(e,o,append){if(e.owner===0&&selected.includes(e)&&!state?.replay&&performance.now()-lastAck>450){lastAck=performance.now();play('ack',e);}return queue(e,o,append);};
 const mapInfo=make('p',null,$('mapMenu'));mapInfo.id='mapStrategyInfo';mapInfo.textContent='Additional crossings allow flanking. Raised-terrain expansions favor defense; cleared forest lanes keep approach routes open.';
 button('Check map fairness and routes',$('mapMenu'),()=>{const result=KawMaps.validate(KawRules.plan(mapChoice));mapInfo.textContent=result.errors.length?'Map issues: '+result.errors.join(' '):'All six starting positions have connected ground routes. '+(result.warnings.length?result.warnings.join(' '):'Nearby resource access checks pass.');}).id='checkMapFairness';
 renderMapPreviews();
 // Extend guided practice with real gameplay checks and prepared training targets.
 tutorialLessons.push(['Increase supply','Build a Supply House with a collector and finish it. Each completed house adds 10 supply, up to your match maximum.','supply'],['Use a unit counter','An artillery unit and practice wall are provided. Select the artillery and attack the wall. Artillery deals 40% extra damage to buildings; Dominion spears deal 40% extra against flyers.','counter'],['Use a ramp','A training hill and infantry are provided. Move infantry up the log ramp onto the elevated ground. Ground units need ramps; flying units can cross cliff edges.','elevation'],['Attack while moving','Select infantry, choose Attack move, then right-click a destination (tap in Order mode on a phone). Troops engage enemies they encounter.','attackMove'],['Retreat safely','Select a fighter and choose Retreat. It cancels attacks and moves toward your nearest completed Stronghold or Resource Outpost.','retreat']);
 let prepared=-1,counterTarget=null;const renderGuide=renderTutorial;renderTutorial=function(){if(tutorial.active&&prepared!==tutorial.step){prepared=tutorial.step;const lesson=tutorialLessons[tutorial.step]?.[2];if(['supply','counter','elevation'].includes(lesson))state.players[0].gold=state.players[0].wood=1200;if(lesson==='counter'){const site=tutorialSite('wall'),base=state.entities.find(e=>e.owner===0&&e.type==='base');if(site&&base){base.level=Math.max(2,base.level||1);const target=entity('wall',1,site.x,site.y,true);target.hp=target.max=3000;counterTarget=target.id;entity('siege',0,site.x+100,site.y+100);fog();}}if(lesson==='elevation'){const base=state.entities.find(e=>e.owner===0&&e.type==='base'),x=base.x<SIZE/2?base.x+250:base.x-600,y=base.y<SIZE/2?base.y+300:base.y-650,p={x:Math.max(80,Math.min(SIZE-500,x)),y:Math.max(80,Math.min(SIZE-500,y)),w:360,h:240,height:32};p.rampX=p.x+180;state.plateaus.push(p);state.resources=state.resources.filter(r=>r.x<p.x-80||r.x>p.x+p.w+80||r.y<p.y-80||r.y>p.y+p.h+100);state.mountains=state.mountains.filter(m=>m.x<p.x-80||m.x>p.x+p.w+80||m.y<p.y-80||m.y>p.y+p.h+100);state.wallVersion++;state.blockCache={};const u=entity('melee',0,p.rampX,p.y+p.h+110);selected=[u];cam.x=p.x-viewport.width/2+180;cam.y=p.y-viewport.height/2+240;clampCam();clearTerrainCache();KawBattlefield.stop();fog();}}renderGuide();};
 const advance=tutorialAdvance;tutorialAdvance=function(){if(tutorial.active){const lesson=tutorialLessons[tutorial.step]?.[2];if(lesson==='supply'&&state.entities.some(e=>e.owner===0&&e.type==='house'&&!e.construction))tutorial.events.add('supply');if(lesson==='counter'&&state.entities.find(e=>e.id===counterTarget)?.hp<3000)tutorial.events.add('counter');if(lesson==='elevation'&&state.entities.some(e=>e.owner===0&&!e.building&&!isFlying(e)&&terrainHeight(e.x,e.y)>25))tutorial.events.add('elevation');}return advance();};
 const task=queueTask;queueTask=function(e,o,append){const result=task(e,o,append);if(tutorial.active&&e.owner===0&&o.kind==='attackMove')tutorial.events.add('attackMove');return result;};
 const army=KawBattle.command;KawBattle.command=function(e,kind,p){const result=army(e,kind,p);if(result&&tutorial.active&&e.owner===0&&kind==='retreat')tutorial.events.add('retreat');return result;};
 window.KawFrontline={conditions,renderBalance,get balance(){return records;},play};
})();
