/* Original campaign, combat readouts, lobby controls and procedural audio. */
(() => {
 const make=(tag,text,parent)=>{const e=document.createElement(tag);if(text)e.textContent=text;parent?.append(e);return e;},button=(text,parent,fn)=>{const e=make('button',text,parent);e.type='button';e.onclick=fn;return e;},select=(id,label,parent,options)=>{const l=make('label',label,parent),s=make('select',null,l);s.id=id;for(const [v,t]of options){const o=make('option',t,s);o.value=v;}return s;};
 const teamOptions=[['0','Free for all'],['1','Team 1'],['2','Team 2'],['3','Team 3'],['4','Team 4'],['5','Team 5'],['6','Team 6']];select('mpTeam','Your team',document.querySelector('#multiplayerLobby .mp-profile'),teamOptions);select('mpBotTeam','AI team',$('mpBotControls'),teamOptions);select('mpBotPersonality','AI strategy',$('mpBotControls'),[['balanced','Balanced commander'],['fortifier','Fortifier'],['raider','Raider']]);const sl=make('label','Join as spectator (passcode required for protected lobbies)',$('mpSetup')),sc=make('input',null,sl);sc.type='checkbox';sc.id='mpSpectator';
 const meTeam=$('mpTeam');meTeam.onchange=async()=>{if(!multiplayer.session||multiplayer.active||multiplayer.spectating)return;try{await multiplayerRequest('/api/lobbies/'+multiplayer.session.code,{action:'profile',...multiplayerProfile(),ready:false});await pollMultiplayer();}catch(e){multiplayerStatus(e.message);}};
 const oldLobby=renderMultiplayerLobby;renderMultiplayerLobby=function(room,you){oldLobby(room,you);const me=room.members.find(m=>m.id===you);if(me&&document.activeElement!==meTeam)meTeam.value=String(me.team||0);sc.disabled=!!multiplayer.session;};const oldBot=chooseMultiplayerBot;chooseMultiplayerBot=function(){oldBot();const bot=multiplayer.room?.members.find(m=>m.id===$('mpBotSlot').value);$('mpBotTeam').value=String(bot?.team||0);$('mpBotPersonality').value=bot?.personality||'balanced';};
 // Manual reconnect retries the existing seat credential, never creates a new player.
 button('Reconnect now',$('multiplayerLobby'),()=>{multiplayer.retryAt=0;pollMultiplayer();});make('p','A dropped connection reserves your seat for five minutes. Reloading this tab resumes using its saved session. Server checkpoints recover battles after process restarts when retained storage is configured. Spectators cannot issue orders.',$('multiplayerLobby'));
 const info=make('section',null,document.querySelector('.selection'));info.id='combatStatus';info.setAttribute('aria-live','polite');const battleTools=$('battleTools');
 button('Deploy artillery',battleTools,()=>selected.filter(e=>e.type==='siege'&&e.owner===0).forEach(e=>{if(!multiplayerCommand({kind:'deploy',id:e.id}))KawWarfront.deploy(e);}));let bridgeMode=null;button('Bombard bridge',battleTools,()=>{bridgeMode='bombard';toast('Right-click a bridge with artillery selected. On phone, tap the bridge.');});button('Repair bridge',battleTools,()=>{bridgeMode='repair';toast('Right-click a broken bridge with collectors selected. On phone, tap the bridge.');});
 canvas.addEventListener('pointerdown',event=>{if(state?.spectating){selected=[];event.stopImmediatePropagation();return;}if(!bridgeMode||!state||paused||state.replay)return;if(event.button!==2&&!(window.matchMedia('(pointer:coarse)').matches&&event.button===0))return;const p=point(event),bridge=(state.siegeBridges||[]).find(b=>Math.hypot(b.x-p.x,b.y-p.y)<90);if(!bridge){toast('Choose a bridge crossing.');return;}event.preventDefault();event.stopImmediatePropagation();const repair=bridgeMode==='repair',troops=selected.filter(e=>e.owner===0&&e.type===(repair?'worker':'siege'));if(!troops.length){toast(repair?'Select collectors to repair the bridge.':'Select artillery to bombard the bridge.');return;}for(const e of troops)if(!multiplayerCommand({kind:'bridge',id:e.id,bridgeId:bridge.id,repair}))KawWarfront.bridgeOrder(e,bridge.id,repair);bridgeMode=null;},{capture:true});
 // All acknowledgments, ambience and music are generated locally from original synthesis.
 let audio,noise,windGain,windSource,ambientEnabled=true,musicEnabled=true,ackEnabled=true,volume=.15,voices=0,lastAck=0,nextNote=0,note=0;
 try{const s=JSON.parse(localStorage.getItem('kaw-atmosphere')||'{}');ambientEnabled=s.ambient??true;musicEnabled=s.music??true;ackEnabled=s.acks??true;volume=s.volume??.15;}catch{}
 const audioSettings=make('fieldset',null,$('keySettings'));make('legend','Original atmosphere',audioSettings);const persist=()=>{try{localStorage.setItem('kaw-atmosphere',JSON.stringify({ambient:ambientEnabled,music:musicEnabled,acks:ackEnabled,volume}));}catch{}};
 for(const [label,get,set]of [['Wind & river ambience',()=>ambientEnabled,v=>ambientEnabled=v],['Adaptive original music',()=>musicEnabled,v=>musicEnabled=v],['Unit acknowledgment tones',()=>ackEnabled,v=>ackEnabled=v]]){const l=make('label',label,audioSettings),i=make('input',null,l);i.type='checkbox';i.checked=get();i.onchange=()=>{set(i.checked);persist();};}const vl=make('label','Atmosphere volume',audioSettings),vi=make('input',null,vl);vi.type='range';vi.min=0;vi.max=.5;vi.step=.01;vi.value=volume;vi.oninput=()=>{volume=+vi.value;persist();};
 function play(freq,duration=.2,amount=.2,type='sine',bend=1){if(!audio||audio.state!=='running'||voices>=12||!KawExperience.settings.sound)return;voices++;const o=audio.createOscillator(),g=audio.createGain(),at=audio.currentTime;o.type=type;o.frequency.setValueAtTime(freq,at);o.frequency.exponentialRampToValueAtTime(Math.max(25,freq*bend),at+duration);g.gain.setValueAtTime(.001,at);g.gain.linearRampToValueAtTime(volume*amount,at+.025);g.gain.exponentialRampToValueAtTime(.001,at+duration);o.connect(g).connect(audio.destination);o.start();o.stop(at+duration);o.onended=()=>{voices--;o.disconnect();g.disconnect();};}
 document.addEventListener('pointerdown',()=>{if(!KawExperience.settings.sound)return;if(!audio){const C=window.AudioContext||window.webkitAudioContext;if(!C)return;audio=new C();noise=audio.createBuffer(1,audio.sampleRate*2,audio.sampleRate);const data=noise.getChannelData(0);let last=0;for(let i=0;i<data.length;i++){last=last*.98+(Math.random()*2-1)*.02;data[i]=last*3;}windSource=audio.createBufferSource();windSource.buffer=noise;windSource.loop=true;const filter=audio.createBiquadFilter();filter.type='lowpass';filter.frequency.value=850;windGain=audio.createGain();windGain.gain.value=0;windSource.connect(filter).connect(windGain).connect(audio.destination);windSource.start();}audio.resume().catch(()=>{});},{passive:true});
 const queued=queueTask;queueTask=function(e,order,append){if(ackEnabled&&e.owner===0&&selected.includes(e)&&performance.now()-lastAck>350&&!state?.replay&&!state?.spectating){lastAck=performance.now();const pitch=e.type==='worker'?190:formationRole(e)>=1?310:110;play(pitch,.13,.45,'triangle',1.2);setTimeout(()=>play(pitch*1.5,.13,.3,'triangle',.85),100);}return queued(e,order,append);};
 const missions=[{id:'first-light',name:'First Light',faction:'human',text:'Learn the Dawnward economy: deliver 18 gold and 14 lumber, complete an Infantry Lodge, then train three fighters.'},{id:'ember-road',name:'Ember Road',faction:'horde',text:'Escort an armored supply convoy across the meadow. Protect it from three raiding waves; its destruction loses the mission.'},{id:'living-crossing',name:'Living Crossing',faction:'covenant',text:'Capture the river Signal Stone and hold it continuously for 90 seconds against waves. Use roots, venom and wind to control the crossing.'}];
 const campaignMenu=make('dialog',null,document.body);campaignMenu.id='campaignMissions';make('h2','Borderlands · Original campaign',campaignMenu);const progress=()=>{try{return JSON.parse(localStorage.getItem('kaw-campaign-progress')||'{}');}catch{return{};}};
 const hud=make('section',null,document.querySelector('#game main'));hud.id='missionHud';hud.hidden=true;const missionTitle=make('strong',null,hud),missionText=make('p',null,hud),begin=button('Begin convoy',hud,()=>{if(state?.campaign?.id==='ember-road')state.campaign.started=true;});
 function missionMap(id){const starts=id==='living-crossing'?[{x:400,y:2000},{x:3600,y:2000}]:[{x:400,y:600},{x:3500,y:3400}],resources=[];for(const p of starts){const sign=p.x<2000?1:-1;resources.push({x:p.x+sign*280,y:p.y+150,type:'gold',amount:12000,noOutcrop:true});for(let i=0;i<21;i++)resources.push({x:p.x+sign*(220+i%7*38),y:p.y-220+Math.floor(i/7)*38,type:'wood',amount:240});}const rivers=[];if(id==='living-crossing'){const points=[];for(let y=200;y<3800;y+=24)points.push({x:2000,y});rivers.push({points,width:48,bridges:[2000]});}return{version:1,size:4000,name:id,starts,resources,mountains:[],plateaus:[],rivers};}
 function launch(id){if(multiplayer.active)return toast('Leave the multiplayer battle before starting a campaign mission.');const mission=missions.find(m=>m.id===id),map=missionMap(id),validation=KawMaps.validate(map);if(validation.errors.length)return toast(validation.errors.join(' '));setFaction(mission.faction);KawMaps.apply(map,[{name:'Commander',faction:mission.faction,color:$('color').value,ai:false},{name:'Border Raiders',faction:mission.faction==='horde'?'human':'horde',color:$('color').value==='#ef685a'?'#b88af0':'#ef685a',ai:false}]);state.campaign={id,stage:0,started:false,nextWave:id==='ember-road'?8:18,waves:0,held:0,lastTime:0};state.players[0].gold=450;state.players[0].wood=300;if(id!=='first-light'){const base=state.entities.find(e=>e.owner===0&&e.type==='base');base.level=3;base.max=buildings.base.hp*1.3;base.hp=base.max;for(let i=0;i<8;i++)entity(i<4?'melee':'ranged',0,base.x+100+(i%4)*40,base.y+120+Math.floor(i/4)*45);if(id==='living-crossing'){state.posts=[{id:0,x:2000,y:2000,owner:-1,claimant:-1,progress:0}];entity('hero',0,base.x+150,base.y+230);state.players[0].heroChoice='hero';entity('trapper',0,base.x+200,base.y+230);}else{const convoy=entity('siege',0,base.x+120,base.y);convoy.convoy=true;convoy.hp=convoy.max=650;convoy.cool=999;convoy.order={kind:'hold'};state.campaign.convoyId=convoy.id;state.campaign.destination={x:1800,y:600};}}fog();updateUI();campaignMenu.close();}
 // Called from the simulation tick, so pausing, saving, or slowing rendering is safe.
 function campaignTick(dt){const c=state?.campaign;if(!c||c.done||state.networkMatch)return;if(state.ended){return finishMission(state.entities.some(e=>e.owner===0&&e.type==='base'&&e.hp>0));}if(c.id==='first-light'){const stats=matchStats(0);c.stage=stats.goldGained>=18&&stats.woodGained>=14?1:0;if(c.stage&&state.entities.some(e=>e.owner===0&&e.type==='barracks'&&!e.construction))c.stage=2;if(c.stage===2&&stats.fightersBuilt>=3)finishMission(true);}
 else if(c.id==='ember-road'){const convoy=state.entities.find(e=>e.id===c.convoyId&&e.hp>0);if(!convoy)return finishMission(false);if(c.started){if(Math.hypot(convoy.x-c.destination.x,convoy.y-c.destination.y)<30&&c.waves===3)return finishMission(true);if(convoy.order?.kind!=='move')queueTask(convoy,{kind:'move',...c.destination});convoy.cool=999;if(state.time>=c.nextWave&&c.waves<3){c.nextWave=state.time+8;c.waves++;for(let i=0;i<2+c.waves;i++){const x=Math.min(SIZE-80,convoy.x+350+i*35),y=convoy.y+250+i*35,u=entity(i%3?'melee':'ranged',1,x,y);queueTask(u,{kind:'attack',target:convoy});}}}}
 else{const p=state.posts?.[0];c.held=p?.owner===0?c.held+dt:0;if(c.held>=90)return finishMission(true);if(state.time>=c.nextWave&&c.waves<8){c.waves++;c.nextWave=state.time+24;for(let i=0;i<3;i++){const u=entity(i===2?'ranged':'melee',1,2500+i*40,2000+i*40);queueTask(u,{kind:'attackMove',x:2000,y:2000});}}}
 if(!state.entities.some(e=>e.owner===0&&e.type==='base'&&e.hp>0))finishMission(false);
 }
 function finishMission(won){const c=state.campaign;if(c.done)return;c.done=true;c.won=won;state.ended=true;showMatchResults(won?'MISSION COMPLETE':'MISSION FAILED');if(won){const p=progress();p[c.id]=true;try{localStorage.setItem('kaw-campaign-progress',JSON.stringify(p));}catch{}}}
 const originalTick=tick;tick=function(dt){originalTick(dt);if(!multiplayer.active)campaignTick(dt);};
 button('Original campaign',$('campaignMenu'),()=>{campaignMenu.replaceChildren();make('h2','Borderlands · Original campaign',campaignMenu);for(const m of missions){make('p',m.text,campaignMenu);button((progress()[m.id]?'✓ ':'')+m.name,campaignMenu,()=>launch(m.id));}button('Close',campaignMenu,()=>campaignMenu.close());campaignMenu.showModal();});
 // Per-opponent strategy changes decisions, not resource multipliers.
 const strategy=make('fieldset',null,$('menu'));strategy.id='aiPersonalities';make('legend','AI strategies',strategy);for(let i=1;i<=5;i++)select('aiStrategy'+i,'Opponent '+i,strategy,[['balanced','Balanced'],['fortifier','Fortifier'],['raider','Raider']]);const oldRoster=singlePlayerRoster;singlePlayerRoster=function(){return oldRoster().map((p,i)=>({...p,personality:i?$('aiStrategy'+i).value:'balanced'}));};
 let timer=0,signature='';const originalFrame=KawExperience.frame;KawExperience.frame=function(dt,t){originalFrame(dt,t);timer+=dt;if(timer<.2)return;timer=0;if(audio&&windGain){const enabled=ambientEnabled&&KawExperience.settings.sound;const nearWater=state?.rivers?.some(r=>Math.abs((riverCenter(r,cam.y+viewport.height/2)??-10000)-(cam.x+viewport.width/2))<400);windGain.gain.setTargetAtTime(enabled?volume*(nearWater?.15:.07):0,audio.currentTime,.4);if(musicEnabled&&KawExperience.settings.sound&&audio.currentTime>=nextNote){const combat=state?.entities?.some(e=>e.owner===0&&e.action?.kind==='attack'&&e.action.until>state.time&&inViewport(e.x,e.y)),motif=[0,7,3,10,5,7,2,3,0,5,10,7],semitone=motif[note++%motif.length];play(110*2**(semitone/12),combat?.22:.65,.2,combat?'triangle':'sine');if(note%4===0)play(55,.8,.12,'sine');nextNote=audio.currentTime+(combat?.32:.65);}}
 if(!state){hud.hidden=true;return;}const e=selected[0];let text='';if(e&&!e.building){const statuses=[];if(e.burn)statuses.push((e.burn.poison?'Poison':'Burning')+' '+e.burn.left.toFixed(1)+'s');if(e.webSlowUntil>state.time)statuses.push('Web slow '+Math.ceil(e.webSlowUntil-state.time)+'s');if(e.slowUntil>state.time)statuses.push('Slowed');if(e.stunUntil>state.time)statuses.push('Stunned');if(e.standfast)statuses.push('Standfast: +5% damage / 10% protection');if(e.surge)statuses.push('Battle Surge: +'+e.surge*2+'% damage');if(e.rootward)statuses.push('Rootward active');if(e.deployed)statuses.push('Deployed: +35% damage / +25% range');if(e.shieldUntil>state.time)statuses.push('Shielded');const dmg=units[e.type].damage*(e.deployed?1.35:1);text='Armor '+Math.round((1-armorMultiplier(e))*100)+'% · Base damage '+dmg.toFixed(0)+' · '+(statuses.join(' · ')||'No active conditions');}if(text!==signature){signature=text;info.textContent=text;}
 const c=state.campaign;hud.hidden=!c||!!state.replay;if(c){const m=missions.find(m=>m.id===c.id);missionTitle.textContent=m?.name||'Campaign';begin.hidden=c.id!=='ember-road'||c.started||c.done;missionText.textContent=c.done?(c.won?'Mission complete!':'Mission failed. Try again from the campaign menu.'):c.id==='first-light'?[`Deliver resources: ${Math.floor(matchStats(0).goldGained)}/18 gold · ${Math.floor(matchStats(0).woodGained)}/14 lumber`,'Complete an Infantry Lodge','Train three fighters: '+matchStats(0).fightersBuilt+'/3'][c.stage]:c.id==='ember-road'?'Convoy health '+Math.max(0,Math.ceil(state.entities.find(e=>e.id===c.convoyId)?.hp||0))+'/650 · Raiding waves '+c.waves+'/3':'Hold the river Signal Stone: '+Math.floor(c.held)+'/90 seconds';}}
 $('mpBotSlot').onchange=chooseMultiplayerBot;
 window.KawCampaignMissions={launch,tick:campaignTick,missions};
})();
