'use strict';
// Commands are authorized and simulated by the shared server; this browser renders its own view.
const multiplayer={active:false,session:null,room:null,busy:false,errors:0,queue:Promise.resolve(),timer:null,formation:'box',generation:0,connecting:false};
const mp=id=>document.getElementById(id);
function multiplayerStatus(message){mp('mpStatus').textContent=message;}
function multiplayerServer(){const value=mp('mpServer').value.trim().replace(/\/$/,'');if(!value)throw Error('Enter your multiplayer server address. Use Deploy server if you have not hosted one yet.');const url=new URL(value);if(!['http:','https:'].includes(url.protocol)||url.username||url.password||url.search||url.hash)throw Error('Enter an HTTP or HTTPS server address.');if(location.protocol==='https:'&&url.protocol!=='https:'&&!['localhost','127.0.0.1'].includes(url.hostname))throw Error('The multiplayer server must use HTTPS with this game.');return url.origin+url.pathname.replace(/\/$/,'');}
async function multiplayerRequest(path,body,session=multiplayer.session){const server=session?.server||multiplayerServer();const response=await fetch(server+path,{method:body?'POST':'GET',headers:{...(body?{'Content-Type':'application/json'}:{}),...(session?.token?{Authorization:'Bearer '+session.token}:{})},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(8000)});const data=await response.json();if(!response.ok)throw Object.assign(Error(data.error||'Multiplayer request failed.'),{status:response.status});return data;}
function multiplayerProfile(){return{name:mp('mpName').value,faction:mp('mpFaction').value,color:mp('mpColor').value};}
function saveMultiplayerSession(){try{if(multiplayer.session)sessionStorage.setItem('kingdoms-multiplayer-session',JSON.stringify(multiplayer.session));else sessionStorage.removeItem('kingdoms-multiplayer-session');}catch{}}
function renderMultiplayerLobby(room,you){multiplayer.room=room;mp('mpSetup').hidden=true;mp('mpRoom').hidden=false;mp('mpRoomCode').textContent=room.code;mp('mpPrivacy').textContent=room.protected?'Passcode protected · Share the passcode separately':'Open lobby · Anyone with the lobby code can join';const me=room.members.find(m=>m.id===you);if(multiplayer.you!==you&&me){mp('mpName').value=me.name;mp('mpFaction').value=me.faction;mp('mpColor').value=me.color;}multiplayer.you=you;const list=mp('mpMembers');list.replaceChildren();for(const member of room.members){const row=document.createElement('li'),banner=document.createElement('span'),text=document.createElement('span');banner.className='mp-banner';banner.style.background=member.color;text.textContent=member.name+' · '+factionName(member.faction)+(member.host?' · Host':'')+(member.ai?' · AI · '+member.difficulty:'')+(member.left?' · Left':!member.connected?' · Reconnecting':member.ready?' · Ready':' · Not ready');row.append(banner,text);list.append(row);}mp('mpReady').textContent=me?.ready?'Not ready':'Ready';mp('mpReady').disabled=room.phase!=='waiting';mp('mpStartBattle').hidden=!me?.host;mp('mpStartBattle').disabled=room.phase!=='waiting'||room.members.length<2||room.members.some(m=>!m.ready||!m.connected);renderMultiplayerBots(room,me);mp('mpLobbyMap').textContent={highlands:'Shattered Highlands',frontier:'Frostbound Frontier',canyon:'Ember Canyon'}[room.map];if(room.phase==='waiting')multiplayerStatus('Choose your faction and color, then mark yourself ready. Up to 6 human/AI players; the host can add AI opponents.');}
function renderMultiplayerBots(room,me){mp('mpBotControls').hidden=!me?.host||room.phase!=='waiting';const bots=room.members.filter(m=>m.ai),signature=JSON.stringify(bots.map(b=>[b.id,b.name,b.faction,b.color,b.difficulty]));if(signature!==multiplayer.botSignature){const value=mp('mpBotSlot').value;mp('mpBotSlot').replaceChildren();const add=document.createElement('option');add.value='';add.textContent='Add new AI';mp('mpBotSlot').append(add);for(const b of bots){const option=document.createElement('option');option.value=b.id;option.textContent=b.name+' · '+b.difficulty;mp('mpBotSlot').append(option);}mp('mpBotSlot').value=bots.some(b=>b.id===value)?value:'';multiplayer.botSignature=signature;if(!mp('mpBotSlot').value)chooseMultiplayerBot();}mp('mpSaveBot').disabled=!mp('mpBotSlot').value&&room.members.length>=6;mp('mpSaveBot').textContent=mp('mpBotSlot').value?'Save AI':'Add AI';mp('mpRemoveBot').disabled=!mp('mpBotSlot').value;}
function chooseMultiplayerBot(){const bot=multiplayer.room?.members.find(m=>m.ai&&m.id===mp('mpBotSlot').value);if(bot){mp('mpBotFaction').value=bot.faction;mp('mpBotDifficulty').value=bot.difficulty;mp('mpBotColor').value=bot.color;}else{const used=multiplayer.room?.members.map(m=>m.color)||[];mp('mpBotColor').value=['#53c9eb','#ef685a','#b88af0','#f2c45b','#81d186','#f19cd1'].find(c=>!used.includes(c))||'#f2c45b';}mp('mpSaveBot').textContent=bot?'Save AI':'Add AI';mp('mpSaveBot').disabled=!bot&&(multiplayer.room?.members.length||0)>=6;mp('mpRemoveBot').disabled=!bot;}
async function configureMultiplayerBot(remove=false){try{const id=mp('mpBotSlot').value,bot=multiplayer.room.members.find(m=>m.id===id);const response=await multiplayerRequest('/api/lobbies/'+multiplayer.session.code,{action:'bot',id,remove,name:bot?.name||'AI Commander '+(multiplayer.room.members.filter(m=>m.ai).length+1),faction:mp('mpBotFaction').value,color:mp('mpBotColor').value,difficulty:mp('mpBotDifficulty').value});renderMultiplayerLobby(response.room,multiplayer.you);}catch(error){multiplayerStatus(error.message);}}
function unpackMultiplayerState(data){const next={...data,entities:data.entities.map(e=>({...e})),resources:data.resources.map(r=>({...r})),visible:Uint8Array.from(data.visible),seen:Uint8Array.from(data.seen)};const entities=new Map(next.entities.map(e=>[e.id,e])),resources=new Map(next.resources.map(r=>[r.resourceId,r]));function decode(value){if(!value||typeof value!=='object')return value;if(Object.hasOwn(value,'$entity'))return entities.get(value.$entity)||null;if(Object.hasOwn(value,'$resource'))return resources.get(value.$resource)||null;if(Array.isArray(value))return value.map(decode);for(const key of Object.keys(value))value[key]=decode(value[key]);return value;}for(const e of next.entities)decode(e);for(const r of next.resources)decode(r);for(const e of next.entities){if(e.order?.target===null)e.order=null;e.jobs=(e.jobs||[]).filter(Boolean);e.tasks=(e.tasks||[]).filter(t=>!Object.hasOwn(t,'target')||t.target);}return next;}
function receiveMultiplayerState(snapshot){const first=!multiplayer.active,ids=selected.map(e=>e.id),previous=state;state=unpackMultiplayerState(snapshot);state.formation=multiplayer.formation;selected=state.entities.filter(e=>ids.includes(e.id)&&e.owner===0);for(const e of state.entities){const old=previous?.entities.find(p=>p.id===e.id);if(old&&!e.building&&!e.hiddenInMine){e.networkFrom={x:old.x,y:old.y};e.networkAt=performance.now();}}if(first){multiplayer.active=true;paused=false;selected=[];placement=null;commandMode=null;terrainLayer=null;keys={};$('menu').hidden=true;$('mapMenu').hidden=true;$('game').hidden=false;mp('multiplayerLobby').close();resize();const base=state.entities.find(e=>e.owner===0&&e.type==='base');cam={x:(base?.x||0)-viewport.width/2,y:(base?.y||0)-viewport.height/2};clampCam();mp('mpConnection').hidden=false;mp('mpConnection').textContent='Online · Lobby '+multiplayer.room.code;}
 $('pause').textContent='Online match';$('pause').disabled=true;$('end').hidden=!state.ended;if(state.ended&&(first||!previous?.ended||JSON.stringify(previous.matchStats)!==JSON.stringify(state.matchStats)))showMatchResults(state.result==='VICTORY'?'VICTORY':'DEFEAT',state.matchStats);if(state.count<=0)$('countdown').textContent='';if(first)actionUISignature=null;updateUI();}
async function pollMultiplayer(){if(!multiplayer.session||multiplayer.busy)return;const session=multiplayer.session;multiplayer.busy=true;try{const data=await multiplayerRequest('/api/lobbies/'+session.code,null,session);if(multiplayer.session!==session)return;multiplayer.errors=0;renderMultiplayerLobby(data.room,data.you);if(data.snapshot)receiveMultiplayerState(data.snapshot);mp('mpConnection').textContent='Online · Lobby '+data.room.code;}catch(error){if(multiplayer.session!==session)return;multiplayer.errors++;multiplayerStatus(error.status===401||error.status===404?error.message:'Connection lost. Retrying… '+error.message);if(multiplayer.active){mp('mpConnection').textContent='Reconnecting…';keys={};}if(error.status===401||error.status===404){clearInterval(multiplayer.timer);multiplayer.session=null;saveMultiplayerSession();if(multiplayer.active){state.ended=true;$('end').hidden=false;$('end').textContent='DISCONNECTED · Return to the main menu to rejoin.';}else{mp('mpSetup').hidden=false;mp('mpRoom').hidden=true;}}}finally{multiplayer.busy=false;}}
async function enterMultiplayer(kind){if(multiplayer.connecting||multiplayer.session)return;const generation=multiplayer.generation;multiplayer.connecting=true;mp('mpHost').disabled=mp('mpJoin').disabled=true;try{multiplayerStatus('Connecting…');const server=multiplayerServer();const health=await multiplayerRequest('/healthz',null,{server});if(generation!==multiplayer.generation)return;if(health.service!=='kingdoms-multiplayer'||health.protocol!==1)throw Error('This address is not a compatible Kingdoms multiplayer server.');if(!health.factions?.includes('covenant')||!health.unitAbilities)throw Error('The multiplayer server needs the Covenant update. On Render, choose Manual Deploy → Deploy latest commit.');if(health.maxPlayers!==6||!health.aiOpponents)throw Error('This server needs the latest update. On Render, deploy the latest main commit to enable 6 players and AI opponents.');try{localStorage.setItem('kingdoms-multiplayer-server',server);}catch{}const path=kind==='host'?'/api/lobbies':'/api/lobbies/'+mp('mpJoinCode').value.trim().toUpperCase()+'/join';const data=await multiplayerRequest(path,{...multiplayerProfile(),passcode:mp('mpPasscode').value,map:mp('mpMap').value},{server});if(generation!==multiplayer.generation){await multiplayerRequest('/api/lobbies/'+data.room.code,{action:'leave'},{server,token:data.token});return;}mp('mpPasscode').value='';multiplayer.session={server,code:data.room.code,token:data.token};saveMultiplayerSession();clearInterval(multiplayer.timer);multiplayer.timer=setInterval(pollMultiplayer,150);await pollMultiplayer();}catch(error){if(generation===multiplayer.generation)multiplayerStatus(error.message==='Failed to fetch'?'Could not connect. Check the server address and make sure the server is running.':error.message);}finally{multiplayer.connecting=false;mp('mpHost').disabled=mp('mpJoin').disabled=false;}}
function multiplayerCommand(command){if(!multiplayer.active)return false;if(multiplayer.errors){toast('Reconnecting. Wait before issuing orders.');return true;}const session=multiplayer.session;if(!session)return true;multiplayer.queue=multiplayer.queue.then(async()=>{if(multiplayer.session!==session)return;try{await multiplayerRequest('/api/lobbies/'+session.code,{action:'command',command},session);}catch(error){toast(error.message);}});return true;}
async function leaveMultiplayer(){multiplayer.generation++;const session=multiplayer.session;clearInterval(multiplayer.timer);multiplayer.session=null;multiplayer.room=null;multiplayer.active=false;multiplayer.errors=0;saveMultiplayerSession();mp('mpConnection').hidden=true;$('pause').disabled=false;mp('mpSetup').hidden=false;mp('mpRoom').hidden=true;if(session){try{await multiplayerRequest('/api/lobbies/'+session.code,{action:'leave'},session);}catch{}}}
const singleplayerTick=tick;tick=function(dt){if(!multiplayer.active)singleplayerTick(dt);};
const localQueueTask=queueTask;queueTask=function(e,order,append=false){if(!multiplayerCommand({kind:'order',id:e.id,append,order:{kind:order.kind,x:order.x,y:order.y,facing:order.facing,targetId:order.kind!=='gather'?order.target?.id:undefined,resourceId:order.kind==='gather'?order.target?.resourceId:undefined}}))return localQueueTask(e,order,append);};
const localStop=stopUnit;stopUnit=function(e){if(!multiplayerCommand({kind:'order',id:e.id,order:{kind:'stop'}}))return localStop(e);};
const localBuild=build;build=function(type,x,y,owner=0,append=false){if(multiplayerCommand({kind:'build',type,x,y,append,workers:selected.filter(e=>e.type==='worker').map(e=>e.id)}))return true;return localBuild(type,x,y,owner,append);};
const localTrain=train;train=function(e,type){if(!multiplayerCommand({kind:'train',id:e.id,type}))return localTrain(e,type);};
const localUpgrade=upgrade;upgrade=function(e,key){if(!multiplayerCommand({kind:'upgrade',id:e.id,key}))return localUpgrade(e,key);};
const localResearchHero=researchHero;researchHero=function(e,id){if(!multiplayerCommand({kind:'upgrade',id:e.id,key:'hero:'+id}))return localResearchHero(e,id);};
const localCancel=cancelProduction;cancelProduction=function(id,jobId){if(multiplayerCommand({kind:'cancel',id,jobId}))return true;return localCancel(id,jobId);};
const localAbility=heroAbility;heroAbility=function(e,aiControlled=false){if(multiplayerCommand({kind:'ability',id:e.id}))return true;return localAbility(e,aiControlled);};
const localPower=castHeroPower;castHeroPower=function(e,power){if(multiplayerCommand({kind:'power',id:e.id,power}))return true;return localPower(e,power);};
const localSpendHeroPoint=spendHeroPoint;spendHeroPoint=function(e,node){if(multiplayerCommand({kind:'heroSkill',id:e.id,node}))return true;return localSpendHeroPoint(e,node);};
const localChooseFormation=chooseFormation;chooseFormation=function(kind){if(multiplayer.active&&formationDefinitions[kind])multiplayer.formation=kind;return localChooseFormation(kind);};
const localRally=setRally;setRally=function(e,rally){if(!multiplayerCommand({kind:'rally',id:e.id,clear:!rally,x:rally?.x,y:rally?.y,resourceId:rally?.resource?.resourceId}))return localRally(e,rally);};
const originalDrawEntity=drawEntity;drawEntity=function(e){if(e.networkFrom&&!e.building){const t=Math.min(1,(performance.now()-e.networkAt)/150);ctx.save();ctx.translate((e.networkFrom.x-e.x)*(1-t),(e.networkFrom.y-e.y)*(1-t));originalDrawEntity(e);ctx.restore();}else originalDrawEntity(e);};
const originalAdmin=$('adminUnlock').onclick;$('adminUnlock').onclick=()=>{if(multiplayer.session){$('adminStatus').textContent='Administrative codes are available in single-player games only.';return;}originalAdmin();};
const originalExit=$('exit').onclick;$('exit').onclick=()=>{if(originalExit())leaveMultiplayer();};
const originalPause=$('pause').onclick;$('pause').onclick=()=>{if(!multiplayer.active)originalPause();};
mp('multiplayerMenu').onclick=()=>{mp('multiplayerLobby').showModal();if(!multiplayer.session){mp('mpFaction').value=faction;mp('mpColor').value=$('color').value;}};
mp('mpHost').onclick=()=>enterMultiplayer('host');mp('mpJoin').onclick=()=>enterMultiplayer('join');
mp('mpLeave').onclick=async()=>{await leaveMultiplayer();mp('multiplayerLobby').close();multiplayerStatus('');};
mp('multiplayerLobby').addEventListener('cancel',event=>{if(multiplayer.session){event.preventDefault();multiplayerStatus('Use Leave lobby to exit your room.');}});
mp('mpReady').onclick=async()=>{try{const me=multiplayer.room.members.find(m=>m.id===multiplayer.you);await multiplayerRequest('/api/lobbies/'+multiplayer.session.code,{action:'profile',...multiplayerProfile(),ready:!me.ready});await pollMultiplayer();}catch(e){multiplayerStatus(e.message);}};
mp('mpStartBattle').onclick=async()=>{try{await multiplayerRequest('/api/lobbies/'+multiplayer.session.code,{action:'start'});await pollMultiplayer();}catch(e){multiplayerStatus(e.message);}};
mp('mpCopyInvite').onclick=async()=>{const url=new URL(location.href);url.searchParams.set('lobby',multiplayer.session.code);url.searchParams.set('server',multiplayer.session.server);mp('mpInvite').value=url.href;try{await navigator.clipboard.writeText(url.href);multiplayerStatus('Invite copied. Share the passcode separately.');}catch{mp('mpInvite').select();multiplayerStatus('Copy the invitation link below. Share the passcode separately.');}};
mp('mpInvite').addEventListener('click',()=>mp('mpInvite').select());
try{const params=new URLSearchParams(location.search);mp('mpServer').value=params.get('server')||localStorage.getItem('kingdoms-multiplayer-server')||(!location.hostname.endsWith('github.io')?location.origin:'');mp('mpJoinCode').value=params.get('lobby')||'';const saved=JSON.parse(sessionStorage.getItem('kingdoms-multiplayer-session')||'null');if(saved?.server&&saved?.code&&saved?.token){multiplayer.session=saved;mp('mpServer').value=saved.server;multiplayer.timer=setInterval(pollMultiplayer,150);pollMultiplayer();}if(params.has('lobby')||saved)mp('multiplayerLobby').showModal();}catch{}

mp('mpBotSlot').onchange=chooseMultiplayerBot;mp('mpSaveBot').onclick=()=>configureMultiplayerBot();mp('mpRemoveBot').onclick=()=>configureMultiplayerBot(true);

const localUnitAbility=unitAbility;unitAbility=function(e,aiControlled=false){if(!multiplayerCommand({kind:'unitAbility',id:e.id}))return localUnitAbility(e,aiControlled);return true;};
