/* Shared route corridors and bounded route bursts keep large orders responsive.
 * Reuse is allowed only when the troop can safely join the cached corridor. */
(() => {
 let session,cache=new Map(),blockedLines=new Set(),obstacles=null,signature='',terrainRefs=[],budgetAt=-1,spent=0;
 const clock=()=>globalThis.performance?.now?.()??Date.now();
 const ground=groundObstacles;groundObstacles=function(){if(!inSimulationTick)return ground();const refs=[state.resources,state.mountains,state.rivers,state.plateaus],key=state.wallVersion+':'+state.entities.length;if(session!==state||signature!==key||refs.some((r,i)=>r!==terrainRefs[i])){session=state;signature=key;terrainRefs=refs;obstacles=ground();cache.clear();blockedLines.clear();}return obstacles;};
 const line=clearWallLine;clearWallLine=function(e,x,y,list){if(!inSimulationTick||state.entities.length<=300||Math.max(Math.abs(x-e.x),Math.abs(y-e.y))<=256)return line(e,x,y,list);const key=state.wallVersion+':'+e.size+':'+Math.floor(e.x/64)+':'+Math.floor(e.y/64)+':'+Math.floor(x/128)+':'+Math.floor(y/128);if(blockedLines.has(key))return false;const clear=line(e,x,y,list);if(!clear){blockedLines.add(key);if(blockedLines.size>2048)blockedLines.delete(blockedLines.values().next().value);}return clear;};
 const route=wallRoute;wallRoute=function(e,x,y){if(session!==state){session=state;cache.clear();blockedLines.clear();obstacles=null;signature='';}const key=e.size+':'+state.wallVersion+':'+state.entities.length+':'+Math.floor(e.x/96)+':'+Math.floor(e.y/96)+':'+Math.floor(x/128)+':'+Math.floor(y/128),prior=cache.get(key);if(prior){for(let i=0;i<Math.min(8,prior.length);i++)if(clearWallLine(e,prior[i].x,prior[i].y)){const points=prior.slice(i).map(p=>({...p}));const last=points.at(-1);if(last&&clearWallLine({...e,...last},x,y))points.push({x,y});return points;}}
  if(budgetAt!==state.time){budgetAt=state.time;spent=0;}if(inSimulationTick&&state.entities.length>300&&spent>14){const points=[];points.deferred=true;return points;}const start=clock(),points=route(e,x,y);spent+=clock()-start;if(points.length){cache.set(key,points.map(p=>({...p})));if(cache.size>512)cache.delete(cache.keys().next().value);}return points;};
})();
