'use strict';
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),zlib=require('node:zlib');
const {LobbyService,LobbyError}=require('./multiplayer/lobbies.cjs');
const root=__dirname;
function createServer({service=new LobbyService(),tick=true}={}){
 const limits=new Map(),expensiveLimits=new Map();
 function json(req,res,status,value){let body=Buffer.from(JSON.stringify(value));res.setHeader('Content-Type','application/json');res.setHeader('Cache-Control','no-store');if(body.length>1500&&String(req.headers['accept-encoding']).includes('gzip')){body=zlib.gzipSync(body);res.setHeader('Content-Encoding','gzip');res.setHeader('Vary','Accept-Encoding');}res.writeHead(status);res.end(body);}
 const server=http.createServer(async(req,res)=>{res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Methods','GET, POST, OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type, Authorization');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('X-Frame-Options','DENY');if(req.method==='OPTIONS'){res.writeHead(204);return res.end();}
 try{const url=new URL(req.url,'http://localhost'),pathname=url.pathname;if(pathname==='/healthz')return json(req,res,200,{ok:true,service:'kingdoms-multiplayer',protocol:1,maxPlayers:6,aiOpponents:true,factions:['human','horde','covenant'],unitAbilities:true,build:'20261008-covenant-creatures'});
 if(pathname.startsWith('/api/')){if(!['GET','POST'].includes(req.method))throw new LobbyError(405,'Method not allowed.');const ip=req.socket.remoteAddress,authToken=String(req.headers.authorization||'').replace(/^Bearer /,''),roomCode=pathname.split('/')[3]?.toUpperCase(),knownSession=service.rooms.get(roomCode)?.members.some(m=>!m.left&&m.token===authToken),limitKey=knownSession?'session:'+authToken:ip;let budget=limits.get(limitKey);if(!budget||Date.now()-budget.since>60000){budget={since:Date.now(),count:0};limits.set(limitKey,budget);}if(++budget.count>1800)throw new LobbyError(429,'Too many requests. Try again shortly.');if(req.method==='POST'&&(pathname==='/api/lobbies'||pathname.endsWith('/join'))){let heavy=expensiveLimits.get(ip);if(!heavy||Date.now()-heavy.since>60000){heavy={since:Date.now(),count:0};expensiveLimits.set(ip,heavy);}if(++heavy.count>12)throw new LobbyError(429,'Too many lobby creation or join requests. Try again in a minute.');}let data={};if(req.method==='POST'){if(!String(req.headers['content-type']).startsWith('application/json'))throw new LobbyError(415,'Use JSON requests.');let length=0,chunks=[];for await(const chunk of req){length+=chunk.length;if(length>16384)throw new LobbyError(413,'Request too large.');chunks.push(chunk);}try{data=JSON.parse(Buffer.concat(chunks).toString());}catch{throw new LobbyError(400,'Invalid JSON.');}if(!data||typeof data!=='object'||Array.isArray(data))throw new LobbyError(400,'Invalid request.');}
 if(pathname==='/api/lobbies'&&req.method==='POST')return json(req,res,201,service.create(data));const match=pathname.match(/^\/api\/lobbies\/([A-Z0-9]{7})(\/join)?$/i);if(!match)throw new LobbyError(404,'Endpoint not found.');const token=String(req.headers.authorization||'').replace(/^Bearer /,'');const result=match[2]&&req.method==='POST'?service.join(match[1],data,ip):!match[2]&&req.method==='GET'?service.poll(match[1],token):!match[2]&&req.method==='POST'?service.act(match[1],token,data):null;if(!result)throw new LobbyError(405,'Method not allowed.');return json(req,res,200,result);}
 if(req.method!=='GET'&&req.method!=='HEAD'){res.writeHead(405);return res.end();}const requested=pathname==='/'?'index.html':decodeURIComponent(pathname).slice(1);if(!['index.html','game.js','frontier-art.js','multiplayer.js','tutorial.js','style.css'].includes(requested)&&!/^licenses\/[a-zA-Z0-9_.-]+\.txt$/.test(requested)&&!/^assets\/[a-zA-Z0-9_.-]+\.(webp|png|jpg|svg|ttf)$/.test(requested)){res.writeHead(404);return res.end('Not found');}const file=path.join(root,requested);const body=await fs.promises.readFile(file);res.setHeader('Cache-Control','no-cache');res.setHeader('Content-Type',file.endsWith('.txt')?'text/plain; charset=utf-8':file.endsWith('.ttf')?'font/ttf':file.endsWith('.webp')?'image/webp':file.endsWith('.png')?'image/png':file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html');res.writeHead(200);res.end(req.method==='HEAD'?undefined:body);
 }catch(error){json(req,res,error.status|| (error.code==='ENOENT'?404:500),{error:error.status?error.message:'Server request failed.'});}});
 server.requestTimeout=10000;server.headersTimeout=15000;const timer=tick?setInterval(()=>{try{service.step();}catch(error){console.error('Match simulation failed:',error.message);}for(const map of [limits,expensiveLimits])for(const[ip,b]of map)if(Date.now()-b.since>60000)map.delete(ip);},50):null;timer?.unref();server.on('close',()=>clearInterval(timer));server.lobbies=service;return server;
}
if(require.main===module){const server=createServer();server.listen(process.env.PORT||3000,'0.0.0.0',()=>console.log('Kingdoms at War game and multiplayer server ready.'));}
module.exports={createServer};
