/* Original shared rules. Runs identically in the browser and authoritative server. */
(() => {
 const heavy=new Set(['devoured','cavalier','beetle','shieldwarden','bogbreaker']);
 let index=new Map(),stamp=-1,session;
 function nearby(e,r=90){const out=[];for(let y=Math.floor((e.y-r)/128);y<=Math.floor((e.y+r)/128);y++)for(let x=Math.floor((e.x-r)/128);x<=Math.floor((e.x+r)/128);x++)for(const u of index.get(x+':'+y)||[])if(Math.hypot(u.x-e.x,u.y-e.y)<r)out.push(u);return out;}
 function init(){state.posts=[];if(globalThis.KawExperience?.objectives===false&&!globalThis.KawExperience?.forceObjectives&&!state.networkMatch)return;for(let i=0;i<3;i++){let found;for(let n=0;n<100;n++){const x=SIZE*(.3+i*.2)+Math.cos(n*2.4)*n*7,y=SIZE*.5+Math.sin(n*2.4)*n*7;if(x>80&&y>80&&x<SIZE-80&&y<SIZE-80&&!riverAt(x,y)&&!state.entities.some(e=>Math.hypot(e.x-x,e.y-y)<250)&&!state.resources.some(r=>Math.hypot(r.x-x,r.y-y)<70)&&clearWallLine({x,y,size:14},x+20,y+20)){found={id:i,x,y,owner:-1,claimant:-1,progress:0};break;}}if(found)state.posts.push(found);}}
 function tick(dt){if(session!==state||state.time-stamp>.25){session=state;stamp=state.time;index=new Map();for(const e of state.entities)if(e.hp>0&&!e.building&&!e.hiddenInMine){const k=Math.floor(e.x/128)+':'+Math.floor(e.y/128);if(!index.has(k))index.set(k,[]);index.get(k).push(e);}for(const e of state.entities){e.standfast=false;e.rootward=false;if(e.building||e.type==='worker')continue;const race=state.players[e.owner].faction;if(race==='human')e.standfast=nearby(e,85).filter(u=>u.owner===e.owner&&['melee','ranged','sniper','cavalier','shieldwarden'].includes(u.type)).length>=3;if(race==='covenant'&&e.order?.kind==='hold'&&!isFlying(e)){e.rootSince??=state.time;e.rootward=state.time-e.rootSince>=3;}else e.rootSince=null;if(state.time-(e.surgeAt||0)>4)e.surge=0;}}
 for(const post of state.posts||[]){const owners=new Set(nearby(post,90).filter(u=>u.type!=='worker'&&units[u.type]?.damage>0).map(u=>u.owner));if(owners.size===1){const owner=[...owners][0];if(owner!==post.owner){if(post.claimant!==owner){post.claimant=owner;post.progress=0;}post.progress+=dt;if(post.progress>=8){post.owner=owner;post.progress=0;post.claimant=-1;}}else{post.progress=0;post.claimant=-1;}}else if(!owners.size){post.progress=Math.max(0,post.progress-dt);}if(post.owner>=0){const p=state.players[post.owner];p.gold+=dt*.12;p.wood+=dt*.08;matchStats(post.owner).goldGained+=dt*.12;matchStats(post.owner).woodGained+=dt*.08;}}
 // AI sends idle squads to contest objectives; never interrupts an active fight.
 if(Math.floor(state.time/12)!==state.postAITime){state.postAITime=Math.floor(state.time/12);for(let owner=0;owner<state.players.length;owner++)if(state.players[owner].ai===true){const post=(state.posts||[]).find(p=>p.owner!==owner);if(post)for(const e of state.entities.filter(e=>e.owner===owner&&!e.building&&e.type!=='worker'&&!e.order).slice(0,5))queueTask(e,{kind:'attackMove',x:post.x,y:post.y});}}
 }
 function damage(e,t){let m=1;if(['siege','bastion'].includes(e.type)&&t.building)m*=1.4;if(e.type==='ranged'&&state.players[e.owner].faction==='horde'&&isFlying(t))m*=1.4;if(['ranged','sniper'].includes(e.type)&&heavy.has(t.type)&&nearby(e,120).some(u=>u!==e&&u.owner===e.owner&&['ranged','sniper'].includes(u.type)))m*=1.15;if(e.standfast)m*=1.05;if(t.standfast)m*=.9;m*=1+(e.surge||0)*.02;if(nearby(t).some(u=>sameTeam(u.owner,t.owner)&&u.rootward))m*=.95;return m;}
 function onHit(e){if(state.players[e.owner].faction==='horde'){e.surge=Math.min(5,(e.surge||0)+1);e.surgeAt=state.time;}}
 function speed(e){return !isFlying(e)&&nearby(e).some(u=>!sameTeam(u.owner,e.owner)&&u.rootward)?.85:1;}
 function description(e){const p=state.players[e.owner];return (e.type==='siege'?'Artillery: +40% damage against buildings. ':e.type==='ranged'&&p.faction==='horde'?'Spears: +40% damage against flyers. ':['ranged','sniper'].includes(e.type)?'Coordinated ranged pair: +15% against heavy infantry. ':'')+(p.faction==='human'?'Standfast: group three infantry for +5% damage and 10% protection.':p.faction==='horde'?'Battle Surge: successful hits build up to +10% damage.':'Rootward: hold ground for three seconds to protect allies and slow enemies.');}
 function reveal(){for(const p of state.posts||[])if(p.owner>=0&&sameTeam(p.owner,0))for(let y=Math.max(0,Math.floor((p.y-180)/CELL));y<Math.min(N,Math.ceil((p.y+180)/CELL));y++)for(let x=Math.max(0,Math.floor((p.x-180)/CELL));x<Math.min(N,Math.ceil((p.x+180)/CELL));x++)if(Math.hypot(x*CELL-p.x,y*CELL-p.y)<180)state.seen[y*N+x]=state.visible[y*N+x]=1;}
 function drawWorld(c){for(const p of state.posts||[])if(visible(p.x,p.y)){c.save();c.translate(p.x,p.y-terrainHeight(p.x,p.y));c.fillStyle=p.owner<0?'#c4b98c':state.players[p.owner].color;c.strokeStyle='#25372e';c.lineWidth=3;c.beginPath();c.moveTo(-12,4);c.lineTo(-8,-25);c.lineTo(0,-34);c.lineTo(10,-25);c.lineTo(14,4);c.closePath();c.fill();c.stroke();c.font='12px sans-serif';c.textAlign='center';c.fillStyle='#fff';c.fillText('Signal Stone',0,22);if(p.progress){c.fillStyle='#94eac0';c.fillRect(-20,-44,40*p.progress/8,4);}c.restore();}}
 function drawMini(c){for(const p of state.posts||[])if(visible(p.x,p.y)){c.fillStyle=p.owner<0?'#ffdb8b':p.owner===0?state.players[0].color:'#ff514a';c.fillRect(p.x/SIZE*210-2,p.y/SIZE*150-2,4,4);}}
 globalThis.KawTactics={init,tick,damage,onHit,speed,description,reveal,drawWorld,drawMini};
})();
