'use strict';
// Guided practice uses the real selection, orders, production and delivery systems.
const tutorial={active:false,step:0,events:new Set(),target:null};
const tutorialLessons=[
 ['Select a collector','Left-click a Peasant or Peon near your Stronghold. On a phone, choose Select, then tap the collector.','select'],
 ['Move your collector','With the collector selected, right-click open ground. On a phone, choose Order, then tap the destination. Ordinary orders replace previous orders; Shift or the touch Queue button appends them.','move'],
 ['Deliver lumber','Right-click a nearby tree, or choose Gather and click the tree. On a phone, choose Order and tap a tree. The collector chops, fills a load, and returns it to your Stronghold. Resources count only after delivery.','wood'],
 ['Deliver gold','Send a collector to a gold mine. Up to five collectors can enter a mine. Your collector disappears inside, emerges with a gold sack, then delivers it to the Stronghold.','gold'],
 ['Recruit a collector','Select the Stronghold, then choose Train Peasant or Train Peon under Commands. Wait for the new collector to finish. Each building shows its own queue; queued work can be canceled.','worker'],
 ['Build your infantry lodge','Select a collector. In the separate Construction section, choose Infantry Lodge, then click clear ground nearby. On a phone, use the Build tab. Keep the collector working until construction finishes. Practice construction is accelerated.','barracks'],
 ['Train infantry','Select your completed Infantry Lodge and train its melee infantry. Both gold and lumber costs appear on the action. Use Rally point to send future recruits to a chosen location.','melee'],
 ['Research an upgrade','A completed Harvest Guild has been provided near your base. Select it and research Lumber harvesting 1. Each research building has three queue slots; higher ranks require completed Stronghold upgrades.','research'],
 ['Attack the practice enemy','Select your melee infantry and right-click the red practice enemy nearby. On a phone, choose Order and tap the enemy. Explore to reveal enemies; the minimap only shows enemies in sight and remembered buildings.','attack'],
 ['Stop your infantry','While your infantry attacks, choose Stop under Commands or use its shortcut shown on the button. On a phone, use Stop. A normal move order also interrupts combat; Shift appends the move instead.','stop']
];
function renderTutorial(){const box=$('tutorialGuide');if(!box)return;box.hidden=!tutorial.active;if(!tutorial.active)return;const lesson=tutorialLessons[tutorial.step];$('tutorialProgress').textContent=lesson?'LESSON '+(tutorial.step+1)+' / '+tutorialLessons.length:'PRACTICE COMPLETE';$('tutorialTitle').textContent=lesson?lesson[0]:'Your banner is ready';$('tutorialText').textContent=lesson?lesson[1]:'You have practiced gathering, construction, recruitment, upgrades and combat. Continue experimenting here, or return to the main menu to start a campaign.';$('tutorialNext').hidden=!!lesson;$('tutorialSkip').hidden=!lesson;}
function tutorialAdvance(){if(!tutorial.active||!state||state.networkMatch)return;const lesson=tutorialLessons[tutorial.step];if(!lesson)return;let done=tutorial.events.has(lesson[2]);if(lesson[2]==='select')done=selected.some(e=>e.owner===0&&e.type==='worker');if(lesson[2]==='worker'||lesson[2]==='melee')done=state.entities.filter(e=>e.owner===0&&e.type===lesson[2]&&!e.building).length>(lesson[2]==='worker'?4:0);if(lesson[2]==='barracks')done=state.entities.some(e=>e.owner===0&&e.type==='barracks'&&!e.construction);if(lesson[2]==='research')done=state.players[0].lumber>0;if(done){tutorial.step++;tutorial.events.clear();if(tutorialLessons[tutorial.step]?.[2]==='research')provideTutorialGuild();if(tutorialLessons[tutorial.step]?.[2]==='attack')provideTutorialEnemy();renderTutorial();}}
function tutorialSite(type){const b=state.entities.find(e=>e.owner===0&&e.type==='base');for(let radius=130;radius<400;radius+=40)for(let i=0;i<16;i++){const x=b.x+Math.cos(i*Math.PI/8)*radius,y=b.y+Math.sin(i*Math.PI/8)*radius;if(x>70&&y>70&&x<SIZE-70&&y<SIZE-70&&flatBuildingSite(x,y,buildings[type].size)&&!blockedGroundPoint(x,y,buildings[type].size+20)&&!state.entities.some(e=>e.building&&Math.hypot(x-e.x,y-e.y)<e.size+buildings[type].size+25))return {x,y};}return null;}
function provideTutorialGuild(){if(state.entities.some(e=>e.owner===0&&e.type==='mill'&&!e.construction))return;const site=tutorialSite('mill');if(site){entity('mill',0,site.x,site.y,true);fog();}}
function provideTutorialEnemy(){const u=state.entities.find(e=>e.owner===0&&e.type==='melee'),site=tutorialSite('wall');if(!u||!site)return;const e=entity('melee',1,site.x,site.y);e.hp=e.max=2000;e.cool=1e9;e.manualPassive=true;e.order={kind:'hold'};tutorial.target=e.id;cam.x=site.x-viewport.width/2;cam.y=site.y-viewport.height/2;clampCam();fog();toast('Practice enemy marked red near your Stronghold.');}
function closeTutorial(){tutorial.active=false;renderTutorial();}
function startTutorial(){if(typeof multiplayer!=='undefined'&&multiplayer.session){toast('Leave your multiplayer lobby before starting practice.');return;}closeTutorial();const options={players:[{faction,color:$('color').value,ai:false},{faction:faction==='human'?'horde':'human',color:$('color').value==='#ef685a'?'#b88af0':'#ef685a',ai:false}]};options.rules={resources:100,speed:1,supply:200,victory:'strongholds'};start(options);state.networkMatch=false;state.tutorial=true;state.ai=1e9;state.adminResources=false;state.players[0].gold=state.players[0].wood=1200;tutorial.active=true;tutorial.step=0;tutorial.events.clear();tutorial.target=null;renderTutorial();}
const tutorialStart=start;start=function(options){closeTutorial();return tutorialStart(options);};
const tutorialUI=updateUI;updateUI=function(){tutorialUI();tutorialAdvance();};
const tutorialOrder=queueTask;queueTask=function(e,order,append){const result=tutorialOrder(e,order,append);if(tutorial.active&&e.owner===0&&e.type==='worker'&&order.kind==='move')tutorial.events.add('move');return result;};
const tutorialDelivery=deliverGold;deliverGold=function(e,dt){const gold=e.cargoGold||0,wood=e.cargoWood||0,result=tutorialDelivery(e,dt);if(tutorial.active&&e.owner===0){if(gold&&!e.cargoGold)tutorial.events.add('gold');if(wood&&!e.cargoWood)tutorial.events.add('wood');}return result;};
const tutorialBuild=build;build=function(...args){const result=tutorialBuild(...args);if(result&&tutorial.active){const b=state.entities.at(-1);if(b.owner===0&&b.construction)b.construction.total=b.construction.left=Math.min(12,b.construction.total);}return result;};
const tutorialStop=stopUnit;stopUnit=function(e){const result=tutorialStop(e);if(tutorial.active&&e.owner===0&&e.type==='melee')tutorial.events.add('stop');return result;};
const tutorialTick=tick;tick=function(dt){if(state?.tutorial)state.ai=1e9;const result=tutorialTick(dt);if(tutorial.active&&tutorial.target){const e=state.entities.find(e=>e.id===tutorial.target);if(e&&e.hp<e.max)tutorial.events.add('attack');}return result;};
$('tutorialStart').onclick=startTutorial;$('tutorialSkip').onclick=()=>{tutorial.step++;tutorial.events.clear();if(tutorialLessons[tutorial.step]?.[2]==='research')provideTutorialGuild();if(tutorialLessons[tutorial.step]?.[2]==='attack')provideTutorialEnemy();renderTutorial();};$('tutorialNext').onclick=closeTutorial;$('tutorialExit').onclick=()=>{$('exit').onclick();closeTutorial();};
const tutorialExit=$('exit').onclick;$('exit').onclick=()=>{closeTutorial();tutorialExit();};
