/* Shared, original battlefield systems. Browser and lobby server run these rules. */
(() => {
 let sequence=0;
 function group(troops,destination,kind,append){if(troops.length<2||append)return;const front=troops.filter(e=>formationRole(e)===0),leader=(front.length?front:troops).slice().sort((a,b)=>Math.hypot(a.x-destination.x,a.y-destination.y)-Math.hypot(b.x-destination.x,b.y-destination.y))[0],slots=formationSlots(troops,destination,kind),anchor=slots.get(leader.id),key=leader.id+':'+(++sequence);for(const e of troops){const slot=slots.get(e.id);e.pendingFormation={key,leaderId:leader.id,dx:slot.x-anchor.x,dy:slot.y-anchor.y,finalX:slot.x,finalY:slot.y};}}
 const originalQueue=queueTask;queueTask=function(e,task,append=false){if(['move','attackMove'].includes(task.kind)){if(e.pendingFormation){task={...task,formation:e.pendingFormation};e.pendingFormation=null;}e.deployed=false;}else e.pendingFormation=null;return originalQueue(e,task,append);};
 const originalMove=move;move=function(e,x,y,dt,arrival){const distance=originalMove(e,x,y,dt,arrival);return e.order?.formation?.traveling?Math.max(8,distance):distance;};
 function init(){state.siegeBridges=[];for(let ri=0;ri<(state.rivers||[]).length;ri++){const r=state.rivers[ri];for(const y of r.bridges)state.siegeBridges.push({id:'bridge-'+ri+'-'+Math.round(y),river:ri,x:riverCenter(r,y),y,hp:900,max:900});}for(let i=0;i<state.players.length;i++)state.players[i].personality??=['balanced','raider','fortifier'][i%3];}
 function deploy(e){if(e.type!=='siege'||e.hp<=0)return false;e.deployed=!e.deployed;e.order={kind:'hold'};e.tasks=[];e.route=null;e.manualPassive=false;e.deployReady=state.time+1.5;return true;}
 function bridgeOrder(e,id,repair=false){const b=state.siegeBridges?.find(b=>b.id===id);if(!b||(repair?e.type!=='worker':e.type!=='siege'))return false;e.order={kind:repair?'repairBridge':'bombardBridge',bridgeId:id};e.tasks=[];e.route=null;e.manualPassive=false;return true;}
 function changedBridge(b,open){const r=state.rivers[b.river];r.bridges=r.bridges.filter(y=>y!==b.y);if(open)r.bridges.push(b.y);r.bridges.sort((a,b)=>a-b);state.wallVersion++;state.blockCache={};if(!open)for(const e of state.entities){if(e.building||isFlying(e)||Math.abs(e.y-b.y)>58||Math.abs(e.x-b.x)>r.width/2+e.size)continue;const sign=e.x<b.x?-1:1;for(let n=0;n<5;n++){const x=b.x+sign*(r.width/2+e.size+20+n*20);if(!blockedGroundPoint(x,e.y,e.size)){e.x=x;e.route=null;break;}}}clearTerrainCache();window.KawBattlefield?.stop();}
 function tick(dt){
  const living=new Map(state.entities.filter(e=>e.hp>0).map(e=>[e.id,e]));
  for(const e of state.entities){if(e.hp<=0||e.building)continue;const o=e.order,f=o?.formation;if(f){const leader=((u)=>u?.owner===e.owner?u:null)(living.get(f.leaderId)),moving=leader&&leader!==e&&leader.order?.formation?.key===f.key&&['move','attackMove'].includes(leader.order.kind)&&Math.hypot(leader.x-leader.order.formation.finalX,leader.y-leader.order.formation.finalY)>40;f.traveling=!!moving;if(moving){const desired={x:leader.x+f.dx,y:leader.y+f.dy};if(isFlying(e)||clearWallLine(e,desired.x,desired.y)){o.x=desired.x;o.y=desired.y;}else{const behind=(leader.breadcrumbs||[]).find(p=>Math.hypot(p.x-leader.x,p.y-leader.y)>Math.max(30,Math.hypot(f.dx,f.dy)));o.x=behind?.x??leader.x;o.y=behind?.y??leader.y;}}else{o.x=f.finalX;o.y=f.finalY;}if(leader===e){e.breadcrumbs??=[];if(!e.breadcrumbs.length||Math.hypot(e.x-e.breadcrumbs[0].x,e.y-e.breadcrumbs[0].y)>22){e.breadcrumbs.unshift({x:e.x,y:e.y});e.breadcrumbs.length=Math.min(30,e.breadcrumbs.length);}}}
   if(!o||!['repairBridge','bombardBridge'].includes(o.kind))continue;const b=state.siegeBridges?.find(b=>b.id===o.bridgeId);if(!b||o.kind==='bombardBridge'&&b.hp<=0||o.kind==='repairBridge'&&b.hp>=b.max){finishTask(e);continue;}const r=state.rivers[b.river],distance=Math.hypot(e.x-b.x,e.y-b.y),range=o.kind==='repairBridge'?r.width/2+45:units.siege.range*(e.deployed?1.25:1);if(distance>range){const sign=e.x<b.x?-1:1;move(e,b.x+sign*(r.width/2+35),b.y,dt);continue;}if(o.kind==='repairBridge'){b.hp=Math.min(b.max,b.hp+25*dt);e.action={kind:'repair',until:state.time+.4,duration:.4};if(b.hp===b.max)changedBridge(b,true);}else if(e.cool<=0&&(!e.deployReady||e.deployReady<=state.time)){b.hp=Math.max(0,b.hp-units.siege.damage*(e.deployed?1.35:1));e.cool=2.4;e.facing=Math.atan2(b.y-e.y,b.x-e.x);e.action={kind:'attack',until:state.time+.55,duration:.55};e.shot={rock:true,x:b.x,y:b.y,fromX:e.x,fromY:e.y,fromHeight:18,toHeight:0,left:.65,duration:.65};burst(b.x,b.y,'blast',e.owner,.65);if(!b.hp){changedBridge(b,false);finishTask(e);}}}
 }
 function personalityAI(){for(let owner=1;owner<state.players.length;owner++){const p=state.players[owner];if(p.ai===false)continue;const base=state.entities.find(e=>e.owner===owner&&e.type==='base'&&e.hp>0),army=state.entities.filter(e=>e.owner===owner&&!e.building&&e.type!=='worker'&&e.hp>0);if(!base)continue;if(p.personality==='fortifier'){for(const e of army.filter(e=>!e.aiEngaged&&e.hp/e.max>.5).slice(0,5))if(!e.order||e.order.kind==='attackMove'&&Math.hypot(e.order.x-base.x,e.order.y-base.y)>650)queueTask(e,{kind:'attackMove',x:base.x+(e.id%3-1)*80,y:base.y+190});const worker=state.entities.find(e=>e.owner===owner&&e.type==='worker'&&!['build','repair'].includes(e.order?.kind));if(worker&&!state.entities.some(e=>e.owner===owner&&e.construction)&&state.entities.filter(e=>e.owner===owner&&e.type==='tower').length<3&&p.gold>500&&p.wood>350){const angle=(state.time%3)*2.1;build('tower',base.x+Math.cos(angle)*230,base.y+Math.sin(angle)*230,owner);}}
 if(p.personality==='raider'){const scouts=army.filter(e=>['scout','ranged','air'].includes(e.type)&&!e.aiEngaged).slice(0,3),observed=state.entities.filter(e=>!sameTeam(e.owner,owner)&&e.hp>0&&canSee(owner,e.x,e.y)&&(e.type==='worker'||e.type==='depot'));for(const e of scouts){const target=observed.slice().sort((a,b)=>Math.hypot(e.x-a.x,e.y-a.y)-Math.hypot(e.x-b.x,e.y-b.y))[0];if(target)queueTask(e,{kind:'attack',target});}}
 }}
 const oldAI=ai;ai=function(){oldAI();personalityAI();};
 function drawConvoy(c,e,p){c.save();c.rotate((e.facing||0)*.12);const wood=c.createLinearGradient(-18,-26,18,4);wood.addColorStop(0,'#bd9863');wood.addColorStop(1,'#4a3323');c.fillStyle=wood;c.fillRect(-19,-24,38,20);c.strokeStyle='#ddbe82';c.lineWidth=1;for(let i=0;i<5;i++){c.beginPath();c.moveTo(-18,-22+i*4);c.lineTo(18,-22+i*4);c.stroke();}for(const x of [-16,16]){c.fillStyle='#483124';c.beginPath();c.ellipse(x,1,7,9,0,0,7);c.fill();c.strokeStyle='#b3a17b';c.stroke();for(let i=0;i<6;i++){const a=i*Math.PI/3+state.time*(e.walkUntil>state.time?3:0);c.beginPath();c.moveTo(x,1);c.lineTo(x+Math.cos(a)*6,1+Math.sin(a)*8);c.stroke();}}c.fillStyle=p.color;c.fillRect(-11,-37,23,13);c.strokeStyle='#e9d5ad';c.strokeRect(-11,-37,23,13);c.restore();}
 function draw(c){for(const e of state.entities)if(e.impactAt!==undefined&&state.time>=e.impactAt&&state.time<e.impactAt+.15&&(e.owner===0||visible(e.x,e.y))){const f=(state.time-e.impactAt)/.15;c.save();c.globalAlpha=1-f;c.strokeStyle='#fff2be';c.lineWidth=2;c.beginPath();c.arc(e.x,e.y-renderAltitude(e)-15,3+f*12,0,7);c.stroke();c.restore();}for(const b of state.siegeBridges||[])if(visible(b.x,b.y)){c.save();c.translate(b.x,b.y);c.font='11px sans-serif';c.textAlign='center';c.fillStyle=b.hp>0?'#ece2bb':'#e88372';c.fillText(b.hp>0?'Bridge '+Math.ceil(b.hp)+'/900':'Broken bridge · repairable',0,-16);if(!b.hp){c.strokeStyle='#685441';c.lineWidth=6;c.beginPath();c.moveTo(-28,-7);c.lineTo(-8,9);c.moveTo(8,-9);c.lineTo(28,7);c.stroke();}c.restore();}}
 globalThis.KawWarfront={init,tick,group,deploy,bridgeOrder,draw,drawConvoy};
})();
