'use strict';
const fs=require('node:fs'),vm=require('node:vm');
const source=['game.js','navigation.js','tactics.js','warfront.js','battle-systems.js','campaign-codec.js'].map(f=>fs.readFileSync(require.resolve('../'+f),'utf8')).join('\n');
const bridge=`
globalThis.matchEngine={
 get state(){return state;},
 get profiler(){return KawBattle.profiler;},
 init(members,map){mapChoice=map;start({players:members});state.players.forEach((p,i)=>{p.name=members[i].name;});state.resources.forEach((r,i)=>r.resourceId=i);state.adminResources=false;this.visions=members.map(()=>({seen:new Uint8Array(N*N),visible:new Uint8Array(N*N),enemyBuildings:{}}));},
 perspective(slot,fn){const oldPlayers=state.players,oldSpawns=state.spawns,oldSight=state.networkSight,oldVision={seen:state.seen,visible:state.visible,enemyBuildings:state.enemyBuildings};const swap=n=>n===0?slot:n===slot?0:n;
 if(slot){state.players=oldPlayers.slice();[state.players[0],state.players[slot]]=[state.players[slot],state.players[0]];if(oldSight){state.networkSight=oldSight.slice();[state.networkSight[0],state.networkSight[slot]]=[state.networkSight[slot],state.networkSight[0]];}state.spawns=oldSpawns.slice();[state.spawns[0],state.spawns[slot]]=[state.spawns[slot],state.spawns[0]];for(const e of state.entities){e.owner=swap(e.owner);if(Number.isInteger(e.lastDamageOwner))e.lastDamageOwner=swap(e.lastDamageOwner);if(Number.isInteger(e.burn?.owner))e.burn.owner=swap(e.burn.owner);}for(const e of state.effects)e.owner=swap(e.owner);for(const cloud of state.smoke||[])cloud.owner=swap(cloud.owner);for(const p of state.posts||[]){p.owner=swap(p.owner);p.claimant=swap(p.claimant);}}
 Object.assign(state,this.visions[slot]);try{fog();return fn();}finally{Object.assign(this.visions[slot],{seen:state.seen,visible:state.visible,enemyBuildings:state.enemyBuildings});if(slot){for(const e of state.entities){e.owner=swap(e.owner);if(Number.isInteger(e.lastDamageOwner))e.lastDamageOwner=swap(e.lastDamageOwner);if(Number.isInteger(e.burn?.owner))e.burn.owner=swap(e.burn.owner);}for(const e of state.effects)e.owner=swap(e.owner);for(const cloud of state.smoke||[])cloud.owner=swap(cloud.owner);for(const p of state.posts||[]){p.owner=swap(p.owner);p.claimant=swap(p.claimant);}}state.players=oldPlayers;state.spawns=oldSpawns;state.networkSight=oldSight;Object.assign(state,oldVision);selected=[];}},
 step(dt){if(state.ended)return;if(state.count>0){state.count=Math.max(0,state.count-dt);return;}state.networkSight=this.visions.map((v,slot)=>this.perspective(slot,()=>Uint8Array.from(state.visible)));const oldFog=fog,oldVisible=visible;fog=()=>{};visible=()=>true;try{tick(dt);}finally{fog=oldFog;visible=oldVisible;}const alive=state.players.map((p,i)=>state.entities.some(e=>e.owner===i&&e.type==='base'&&e.hp>0));state.ended=new Set(alive.flatMap((v,i)=>v?[state.players[i].team?'team:'+state.players[i].team:'player:'+i]:[])).size<=1;},
 apply(slot,c){return this.perspective(slot,()=>{globalThis.lastMatchMessage='';if(state.count>0||state.ended||!state.entities.some(e=>e.owner===0&&e.type==='base'&&e.hp>0))return 'Battle is not accepting orders.';const e=state.entities.find(e=>e.id===c.id&&e.owner===0&&e.hp>0),point=(x,y)=>Number.isFinite(x)&&Number.isFinite(y)&&x>=0&&y>=0&&x<=SIZE&&y<=SIZE;
 if(c.kind==='build'){if(!Object.hasOwn(buildings,c.type)||!point(c.x,c.y)||!Array.isArray(c.workers))return 'Invalid construction order.';selected=state.entities.filter(e=>c.workers.includes(e.id)&&e.owner===0&&e.type==='worker'&&e.hp>0);return build(c.type,c.x,c.y,0,!!c.append)?null:globalThis.lastMatchMessage||'Cannot build here or insufficient resources.';}
 if(!e)return 'You can only command your own living units or buildings.';
 if(c.kind==='order'){if(e.building)return 'Select a troop.';const o=c.order;if(!o||!['move','attackMove','attack','gather','repair','build','hold','stop','deliver'].includes(o.kind))return 'Invalid order.';let task={kind:o.kind};if(['move','attackMove'].includes(o.kind)){if(!point(o.x,o.y))return 'Invalid destination.';task.x=o.x;task.y=o.y;if(o.formation){const f=o.formation,leader=state.entities.find(u=>u.id===f.leaderId&&u.owner===0&&!u.building);if(!leader||typeof f.key!=='string'||f.key.length>64||![f.dx,f.dy].every(v=>Number.isFinite(v)&&Math.abs(v)<=1000)||!point(f.finalX,f.finalY))return 'Invalid formation.';task.formation={key:f.key,leaderId:f.leaderId,dx:f.dx,dy:f.dy,finalX:f.finalX,finalY:f.finalY};}if(Number.isFinite(o.facing))task.facing=o.facing;}
 if(['attack','repair','build'].includes(o.kind)){const target=state.entities.find(t=>t.id===o.targetId&&t.hp>0);if(!target||o.kind==='attack'&&(sameTeam(target.owner,0)||target.hiddenInMine||!visible(target.x,target.y))||o.kind!=='attack'&&(e.type!=='worker'||target.owner!==0)||o.kind==='build'&&!target.construction||o.kind==='repair'&&(!['base','gate','wall','tower','bastion'].includes(target.type)||target.construction))return 'Invalid target.';task.target=target;}
 if(o.kind==='deliver'){if(e.type!=='worker'||!(e.cargoGold>0||e.cargoWood>0))return 'Select a collector carrying resources.';if(o.targetId!==undefined){const target=state.entities.find(t=>t.id===o.targetId&&t.hp>0&&t.owner===0&&!t.construction&&['base','depot'].includes(t.type));if(!target)return 'Choose your completed Stronghold or Resource Outpost.';task.target=target;}task.mine=e.mineResume;}
 if(o.kind==='gather'){const target=state.resources.find(r=>r.resourceId===o.resourceId&&r.amount>0);if(e.type!=='worker'||!target||!visible(target.x,target.y))return 'Choose a visible resource with a collector.';task.target=target;}
 if(o.kind==='stop')stopUnit(e);else if(o.kind==='build')assignBuilder(e,task.target,!!c.append);else queueTask(e,task,!!c.append);return null;}
 if(c.kind==='tactical'){if(c.mode==='guard'){const target=state.entities.find(t=>t.id===c.targetId);if(!target||!visible(target.x,target.y))return 'Choose a visible allied unit.';}return KawBattle.command(e,c.mode,c)?null:'Invalid army command.';}
 if(c.kind==='deploy'){return KawWarfront.deploy(e)?null:'Select artillery.';}
 if(c.kind==='bridge'){const bridge=state.siegeBridges?.find(b=>b.id===c.bridgeId);if(!bridge||!visible(bridge.x,bridge.y))return 'Choose a visible bridge.';return KawWarfront.bridgeOrder(e,c.bridgeId,!!c.repair)?null:'Choose artillery to bombard or a collector to repair a bridge.';}
 if(c.kind==='train'){const options=troopOptions(e.type,state.players[0].faction);if(!e.building||!options.includes(c.type))return 'Invalid troop for this building.';train(e,c.type);return globalThis.lastMatchMessage||null;}
 if(c.kind==='upgrade'){const options={tower:state.players[0].faction==='horde'?['towerFire']:[],base:['stronghold','bannerDamageAura','bannerHealthAura','bannerHarvestAura'],mill:['lumber','goldMining','capacity'],armory:['meleeTraining','rangedTraining','sniperTraining','devouredTraining','cavalierTraining','beetleTraining','fire'],foundry:['artillery'],forge:state.players[0].faction==='covenant'?['stickyWebs']:[],roost:state.players[0].faction==='covenant'?['waspVenom']:state.players[0].faction==='horde'?['dragonFlame']:[]};if(!e.building||typeof c.key!=='string'||!(options[e.type]?.includes(c.key)))return 'Invalid research for this building.';upgrade(e,c.key);return globalThis.lastMatchMessage||null;}
 if(c.kind==='addGate')return convertWallToGate(e)?null:globalThis.lastMatchMessage||'Select your completed wall.';
 if(c.kind==='toggleGate')return toggleGate(e)?null:globalThis.lastMatchMessage||'Select your completed gate.';
 if(c.kind==='cancel'){if(!e.building)return 'Select a building.';return cancelProduction(e.id,String(c.jobId))?null:'This work has already finished or was canceled.';}
 if(c.kind==='bannerAura')return setBannerAura(e,c.mode)?null:'Invalid or locked banner aura.';
 if(c.kind==='unitAbility'){if(!abilityDefinition(e))return 'This unit has no active ability.';return unitAbility(e)?null:globalThis.lastMatchMessage||'Ability needs a valid target, clear space, or its cooldown to finish.';}
 if(c.kind==='ability'){if(!isHeroType(e.type))return 'Select a hero.';return heroAbility(e)?null:'Hero ability is not ready.';}
 if(c.kind==='power'){if(!isHeroType(e.type)||typeof c.power!=='string')return 'Invalid hero power.';return castHeroPower(e,c.power)?null:globalThis.lastMatchMessage||'Hero power is not ready.';}
 if(c.kind==='heroSkill'){if(!isHeroType(e.type)||typeof c.node!=='string')return 'Invalid hero skill.';return spendHeroPoint(e,c.node)?null:globalThis.lastMatchMessage||'Cannot learn this skill.';}
 if(c.kind==='rally'){if(!e.building||!['base','barracks','forge','roost','altar'].includes(e.type))return 'Invalid rally building.';if(c.clear)e.rally=null;else{if(!point(c.x,c.y))return 'Invalid rally point.';e.rally={x:c.x,y:c.y,resource:state.resources.find(r=>r.resourceId===c.resourceId&&visible(r.x,r.y))||null};}return null;}
 return 'Unknown command.';});},
 spectatorSnapshot(){const originalVision=this.visions[0];this.visions[0]={seen:new Uint8Array(N*N),visible:new Uint8Array(N*N),enemyBuildings:{}};const oldFog=fog,oldVision={seen:state.seen,visible:state.visible,enemyBuildings:state.enemyBuildings};fog=()=>{state.seen.fill(1);state.visible.fill(1);};try{const result=this.snapshot(0);result.spectating=true;result.ended=state.ended;result.result=state.ended?'MATCH COMPLETE':null;result.players=state.players.map(p=>({...p}));result.matchStats=state.players.map(p=>({name:p.name,faction:p.faction,stats:p.stats}));return result;}finally{fog=oldFog;this.visions[0]=originalVision;Object.assign(state,oldVision);}},
 snapshot(slot){return this.perspective(slot,()=>{const entities=state.entities.filter(e=>e.owner===0||!e.hiddenInMine&&visible(e.x,e.y)),resources=state.resources.filter(r=>state.seen[Math.floor(r.y/CELL)*N+Math.floor(r.x/CELL)]),es=new Set(state.entities),rs=new Set(state.resources);const encode=v=>{if(v===null||typeof v!=='object')return v;if(es.has(v))return {$entity:v.id};if(rs.has(v))return {$resource:v.resourceId};if(Array.isArray(v))return v.map(encode);const result={};for(const [k,value] of Object.entries(v)){if(k==='route')continue;result[k]=encode(value);}return result;};const root=v=>{const result={};for(const [k,value] of Object.entries(v)){if(k==='route')continue;result[k]=encode(value);}return result;};const alive=state.entities.some(e=>sameTeam(e.owner,0)&&e.type==='base'&&e.hp>0);return {ruins:(state.ruins||[]).filter(r=>visible(r.x,r.y)),siegeBridges:state.siegeBridges,networkMatch:true,posts:(state.posts||[]).filter(p=>visible(p.x,p.y)).map(root),smoke:(state.smoke||[]).filter(s=>visible(s.x,s.y)).map(root),matchStats:state.ended?state.players.map((p,i)=>({name:p.name,faction:p.faction,stats:p.stats})): [{name:state.players[0].name,faction:state.players[0].faction,stats:state.players[0].stats}],map:state.map,mountains:state.mountains,plateaus:state.plateaus,rivers:state.rivers,wallVersion:state.wallVersion,blockCache:{},entities:entities.map(e=>e.owner===0?root(e):root({...e,queue:[],research:null,researchQueue:[],rally:null,order:null,tasks:[],jobs:[],route:null})),resources:resources.map(root),players:state.players.map((p,i)=>i?{name:p.name,team:p.team,personality:p.personality,faction:p.faction,color:p.color,banner:p.banner,gold:0,wood:0}:p),effects:state.effects.filter(f=>visible(f.x,f.y)).map(root),seen:Array.from(state.seen),visible:Array.from(state.visible),enemyBuildings:state.enemyBuildings,time:state.time,count:state.count,ended:state.ended||!alive,result:!alive?'DEFEAT':state.ended?'VICTORY':null,adminResources:false,formation:'box'};});},
 checkpoint(){return {version:1,uid,data:KawCampaign.pack(state),visions:this.visions.map(v=>({seen:Array.from(v.seen),visible:Array.from(v.visible),enemyBuildings:v.enemyBuildings}))};},
 restore(record){if(record.version!==1)throw Error('Unsupported match checkpoint.');state=KawCampaign.unpack(record.data);uid=record.uid;this.visions=record.visions.map(v=>({...v,seen:Uint8Array.from(v.seen),visible:Uint8Array.from(v.visible)}));state.wallVersion++;state.blockCache={};selected=[];},
 eliminate(slot){for(const e of state.entities)if(e.owner===slot)e.hp=0;}
};
`;
function createEngine(members,map='highlands'){
 const elements={},element=id=>elements[id]??={value:({color:'#53c9eb',c1:'#ef685a',c2:'#b88af0',ai1:'horde',ai2:'off'})[id],style:{},dataset:{},classList:{toggle(){}},clientWidth:1200,clientHeight:650,getContext(){return{};},appendChild(){},getBoundingClientRect(){return{left:0,top:0,width:210,height:150};}};
 const context=vm.createContext({document:{getElementById:element,querySelectorAll(){return[];},createElement(){return element(Math.random());}},window:{addEventListener(){}},requestAnimationFrame(){},alert(){},console,Math,performance:require('node:perf_hooks').performance});
 vm.runInContext(source+'\nupdateUI=()=>{};toast=message=>{globalThis.lastMatchMessage=message;};resize=()=>{};\n'+bridge,context);context.matchEngine.init(members,map);return context.matchEngine;
}
module.exports={createEngine};
