'use strict';
const fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync(require.resolve('../game.js'),'utf8');
const bridge=`
globalThis.matchEngine={
 get state(){return state;},
 init(members,map){mapChoice=map;start({players:members});state.players.forEach((p,i)=>{p.name=members[i].name;});state.resources.forEach((r,i)=>r.resourceId=i);state.adminResources=false;this.visions=members.map(()=>({seen:new Uint8Array(N*N),visible:new Uint8Array(N*N),enemyBuildings:{}}));},
 perspective(slot,fn){const oldPlayers=state.players,oldSpawns=state.spawns,oldSight=state.networkSight,oldVision={seen:state.seen,visible:state.visible,enemyBuildings:state.enemyBuildings};const swap=n=>n===0?slot:n===slot?0:n;
 if(slot){state.players=oldPlayers.slice();[state.players[0],state.players[slot]]=[state.players[slot],state.players[0]];if(oldSight){state.networkSight=oldSight.slice();[state.networkSight[0],state.networkSight[slot]]=[state.networkSight[slot],state.networkSight[0]];}state.spawns=oldSpawns.slice();[state.spawns[0],state.spawns[slot]]=[state.spawns[slot],state.spawns[0]];for(const e of state.entities){e.owner=swap(e.owner);if(Number.isInteger(e.lastDamageOwner))e.lastDamageOwner=swap(e.lastDamageOwner);if(Number.isInteger(e.burn?.owner))e.burn.owner=swap(e.burn.owner);}for(const e of state.effects)e.owner=swap(e.owner);}
 Object.assign(state,this.visions[slot]);try{fog();return fn();}finally{Object.assign(this.visions[slot],{seen:state.seen,visible:state.visible,enemyBuildings:state.enemyBuildings});if(slot){for(const e of state.entities){e.owner=swap(e.owner);if(Number.isInteger(e.lastDamageOwner))e.lastDamageOwner=swap(e.lastDamageOwner);if(Number.isInteger(e.burn?.owner))e.burn.owner=swap(e.burn.owner);}for(const e of state.effects)e.owner=swap(e.owner);}state.players=oldPlayers;state.spawns=oldSpawns;state.networkSight=oldSight;Object.assign(state,oldVision);selected=[];}},
 step(dt){if(state.ended)return;if(state.count>0){state.count=Math.max(0,state.count-dt);return;}state.networkSight=this.visions.map((v,slot)=>this.perspective(slot,()=>Uint8Array.from(state.visible)));const oldFog=fog,oldVisible=visible;fog=()=>{};visible=()=>true;try{tick(dt);}finally{fog=oldFog;visible=oldVisible;}const alive=state.players.map((p,i)=>state.entities.some(e=>e.owner===i&&e.type==='base'&&e.hp>0));state.ended=alive.filter(Boolean).length<=1;},
 apply(slot,c){return this.perspective(slot,()=>{globalThis.lastMatchMessage='';if(state.count>0||state.ended||!state.entities.some(e=>e.owner===0&&e.type==='base'&&e.hp>0))return 'Battle is not accepting orders.';const e=state.entities.find(e=>e.id===c.id&&e.owner===0&&e.hp>0),point=(x,y)=>Number.isFinite(x)&&Number.isFinite(y)&&x>=0&&y>=0&&x<=SIZE&&y<=SIZE;
 if(c.kind==='build'){if(!Object.hasOwn(buildings,c.type)||!point(c.x,c.y)||!Array.isArray(c.workers))return 'Invalid construction order.';selected=state.entities.filter(e=>c.workers.includes(e.id)&&e.owner===0&&e.type==='worker'&&e.hp>0);return build(c.type,c.x,c.y,0,!!c.append)?null:globalThis.lastMatchMessage||'Cannot build here or insufficient resources.';}
 if(!e)return 'You can only command your own living units or buildings.';
 if(c.kind==='order'){if(e.building)return 'Select a troop.';const o=c.order;if(!o||!['move','attack','gather','repair','build','hold','stop','deliver'].includes(o.kind))return 'Invalid order.';let task={kind:o.kind};if(o.kind==='move'){if(!point(o.x,o.y))return 'Invalid destination.';task.x=o.x;task.y=o.y;if(Number.isFinite(o.facing))task.facing=o.facing;}
 if(['attack','repair','build'].includes(o.kind)){const target=state.entities.find(t=>t.id===o.targetId&&t.hp>0);if(!target||o.kind==='attack'&&(target.owner===0||target.hiddenInMine||!visible(target.x,target.y))||o.kind!=='attack'&&(e.type!=='worker'||target.owner!==0)||o.kind==='build'&&!target.construction||o.kind==='repair'&&(target.type!=='base'||target.construction))return 'Invalid target.';task.target=target;}
 if(o.kind==='deliver'){if(e.type!=='worker'||!(e.cargoGold>0||e.cargoWood>0))return 'Select a collector carrying resources.';if(o.targetId!==undefined){const target=state.entities.find(t=>t.id===o.targetId&&t.hp>0&&t.owner===0&&!t.construction&&['base','depot'].includes(t.type));if(!target)return 'Choose your completed Stronghold or Resource Outpost.';task.target=target;}task.mine=e.mineResume;}
 if(o.kind==='gather'){const target=state.resources.find(r=>r.resourceId===o.resourceId&&r.amount>0);if(e.type!=='worker'||!target||!visible(target.x,target.y))return 'Choose a visible resource with a collector.';task.target=target;}
 if(o.kind==='stop')stopUnit(e);else if(o.kind==='build')assignBuilder(e,task.target,!!c.append);else queueTask(e,task,!!c.append);return null;}
 if(c.kind==='train'){const options={base:['worker'],barracks:state.players[0].faction==='horde'?['melee','ranged','sniper','devoured']:['melee','ranged','sniper','cavalier'],forge:['siege'],roost:['air','air2'],altar:['hero','hero2','hero3']};if(!e.building||!options[e.type]?.includes(c.type))return 'Invalid troop for this building.';train(e,c.type);return globalThis.lastMatchMessage||null;}
 if(c.kind==='upgrade'){const options={base:['stronghold'],mill:['lumber','goldMining','capacity'],armory:['meleeTraining','rangedTraining','sniperTraining','devouredTraining','cavalierTraining','fire'],foundry:['artillery']};if(!e.building||typeof c.key!=='string'||!(options[e.type]?.includes(c.key)))return 'Invalid research for this building.';upgrade(e,c.key);return globalThis.lastMatchMessage||null;}
 if(c.kind==='cancel'){if(!e.building)return 'Select a building.';return cancelProduction(e.id,String(c.jobId))?null:'This work has already finished or was canceled.';}
 if(c.kind==='ability'){if(!isHeroType(e.type))return 'Select a hero.';return heroAbility(e)?null:'Hero ability is not ready.';}
 if(c.kind==='power'){if(!isHeroType(e.type)||typeof c.power!=='string')return 'Invalid hero power.';return castHeroPower(e,c.power)?null:globalThis.lastMatchMessage||'Hero power is not ready.';}
 if(c.kind==='heroSkill'){if(!isHeroType(e.type)||typeof c.node!=='string')return 'Invalid hero skill.';return spendHeroPoint(e,c.node)?null:globalThis.lastMatchMessage||'Cannot learn this skill.';}
 if(c.kind==='rally'){if(!e.building||!['base','barracks','forge','roost','altar'].includes(e.type))return 'Invalid rally building.';if(c.clear)e.rally=null;else{if(!point(c.x,c.y))return 'Invalid rally point.';e.rally={x:c.x,y:c.y,resource:state.resources.find(r=>r.resourceId===c.resourceId&&visible(r.x,r.y))||null};}return null;}
 return 'Unknown command.';});},
 snapshot(slot){return this.perspective(slot,()=>{const entities=state.entities.filter(e=>e.owner===0||!e.hiddenInMine&&visible(e.x,e.y)),resources=state.resources.filter(r=>state.seen[Math.floor(r.y/CELL)*N+Math.floor(r.x/CELL)]),es=new Set(state.entities),rs=new Set(state.resources);const encode=v=>{if(v===null||typeof v!=='object')return v;if(es.has(v))return {$entity:v.id};if(rs.has(v))return {$resource:v.resourceId};if(Array.isArray(v))return v.map(encode);const result={};for(const [k,value] of Object.entries(v)){if(k==='route')continue;result[k]=encode(value);}return result;};const root=v=>{const result={};for(const [k,value] of Object.entries(v)){if(k==='route')continue;result[k]=encode(value);}return result;};const alive=state.entities.some(e=>e.owner===0&&e.type==='base'&&e.hp>0);return {matchStats:state.ended?state.players.map((p,i)=>({name:p.name,faction:p.faction,stats:p.stats})): [{name:state.players[0].name,faction:state.players[0].faction,stats:state.players[0].stats}],map:state.map,mountains:state.mountains,plateaus:state.plateaus,rivers:state.rivers,wallVersion:state.wallVersion,blockCache:{},entities:entities.map(e=>e.owner===0?root(e):root({...e,queue:[],research:null,researchQueue:[],rally:null,order:null,tasks:[],jobs:[],route:null})),resources:resources.map(root),players:state.players.map((p,i)=>i?{name:p.name,faction:p.faction,color:p.color,gold:0,wood:0}:p),effects:state.effects.filter(f=>visible(f.x,f.y)).map(root),seen:Array.from(state.seen),visible:Array.from(state.visible),enemyBuildings:state.enemyBuildings,time:state.time,count:state.count,ended:state.ended||!alive,result:!alive?'DEFEAT':state.ended?'VICTORY':null,adminResources:false,formation:'box'};});},
 eliminate(slot){for(const e of state.entities)if(e.owner===slot)e.hp=0;}
};
`;
function createEngine(members,map='highlands'){
 const elements={},element=id=>elements[id]??={value:({color:'#53c9eb',c1:'#ef685a',c2:'#b88af0',ai1:'horde',ai2:'off'})[id],style:{},dataset:{},classList:{toggle(){}},clientWidth:1200,clientHeight:650,getContext(){return{};},appendChild(){},getBoundingClientRect(){return{left:0,top:0,width:210,height:150};}};
 const context=vm.createContext({document:{getElementById:element,querySelectorAll(){return[];},createElement(){return element(Math.random());}},window:{addEventListener(){}},requestAnimationFrame(){},alert(){},console});
 vm.runInContext(source+'\nupdateUI=()=>{};toast=message=>{globalThis.lastMatchMessage=message;};resize=()=>{};\n'+bridge,context);context.matchEngine.init(members,map);return context.matchEngine;
}
module.exports={createEngine};
