'use strict';
const crypto=require('node:crypto');const {createEngine}=require('./engine.cjs');
class LobbyError extends Error{constructor(status,message){super(message);this.status=status;}}
const colors=['#53c9eb','#ef685a','#b88af0','#f2c45b','#81d186','#f19cd1'];
class LobbyService{
 constructor(){this.rooms=new Map();this.attempts=new Map();}
 profile(input){const name=typeof input.name==='string'?input.name.trim().slice(0,24):'';if(!name)throw new LobbyError(400,'Enter a player name.');if(!['human','horde','covenant'].includes(input.faction))throw new LobbyError(400,'Choose a faction.');if(!/^#[0-9a-f]{6}$/i.test(input.color||''))throw new LobbyError(400,'Choose a banner color.');return{name,faction:input.faction,color:input.color.toLowerCase()};}
 passcode(input){if(input===undefined||input==='')return '';if(typeof input!=='string'||input.length<4||input.length>64)throw new LobbyError(400,'Passcodes must be 4–64 characters.');return input;}
 create(input){if(this.rooms.size>=30)throw new LobbyError(503,'The lobby server is full. Try again later.');const profile=this.profile(input),passcode=this.passcode(input.passcode);if(!['highlands','frontier','canyon'].includes(input.map))throw new LobbyError(400,'Choose a battlefield.');let code;do{code=crypto.randomBytes(5).toString('hex').slice(0,7).toUpperCase();}while(this.rooms.has(code));const salt=crypto.randomBytes(16),room={code,map:input.map,salt,password:passcode?crypto.scryptSync(passcode,salt,32):null,members:[],bots:[],created:Date.now(),phase:'waiting'};const member={...profile,id:crypto.randomBytes(8).toString('hex'),token:crypto.randomBytes(32).toString('hex'),ready:true,lastSeen:Date.now(),host:true};room.members.push(member);this.rooms.set(code,room);return{room:this.publicRoom(room),token:member.token};}
 get(code){const room=this.rooms.get(String(code).toUpperCase());if(!room)throw new LobbyError(404,'Lobby not found or expired.');return room;}
 join(code,input,ip='local'){const room=this.get(code),profile=this.profile(input);let attempts=this.attempts.get(ip);if(!attempts||Date.now()-attempts.since>60000){attempts={count:0,since:Date.now()};this.attempts.set(ip,attempts);}if(attempts.count>=8)throw new LobbyError(429,'Too many join attempts. Try again in a minute.');attempts.count++;const passcode=typeof input.passcode==='string'&&input.passcode.length<=64?input.passcode:'';if(room.password&&!crypto.timingSafeEqual(room.password,crypto.scryptSync(passcode,room.salt,32)))throw new LobbyError(403,'Incorrect lobby passcode.');if(room.phase!=='waiting')throw new LobbyError(409,'This battle has already started.');if(room.members.length+room.bots.length>=6)throw new LobbyError(409,'Lobby is full (6 slots). Remove an AI opponent to make room.');if([...room.members,...room.bots].some(m=>m.color===profile.color))profile.color=colors.find(c=>![...room.members,...room.bots].some(m=>m.color===c));const member={...profile,id:crypto.randomBytes(8).toString('hex'),token:crypto.randomBytes(32).toString('hex'),ready:false,lastSeen:Date.now(),host:false};room.members.push(member);return{room:this.publicRoom(room),token:member.token};}
 authenticate(room,token){const member=room.members.find(m=>m.token===token&&!m.left);if(!member)throw new LobbyError(401,'Lobby session expired. Join again.');member.lastSeen=Date.now();return member;}
 publicRoom(room){return{code:room.code,map:room.map,phase:room.phase,protected:!!room.password,maxPlayers:6,members:[...room.members,...room.bots].map(m=>({id:m.id,name:m.name,faction:m.faction,color:m.color,ready:m.ready,host:!!m.host,ai:!!m.ai,difficulty:m.difficulty,left:!!m.left,connected:!!m.ai||Date.now()-m.lastSeen<6000}))};}
 poll(code,token){const room=this.get(code),member=this.authenticate(room,token);return{room:this.publicRoom(room),you:member.id,...(room.engine?{snapshot:room.engine.snapshot(member.slot)}:{})};}
 act(code,token,input){const room=this.get(code),member=this.authenticate(room,token);if(input.action==='leave'){member.left=true;if(room.phase==='waiting'){room.members=room.members.filter(m=>m!==member);if(member.host&&room.members[0])room.members[0].host=room.members[0].ready=true;}else room.engine.eliminate(member.slot);if(!room.members.some(m=>!m.left))this.rooms.delete(room.code);return{ok:true};}
 if(input.action==='profile'){if(room.phase!=='waiting')throw new LobbyError(409,'Battle already started.');const p=this.profile(input);if([...room.members,...room.bots].some(m=>m!==member&&m.color===p.color))throw new LobbyError(409,'Choose a different banner color.');Object.assign(member,p,{ready:!!input.ready});return{room:this.publicRoom(room)};}
 if(input.action==='bot'){if(!member.host)throw new LobbyError(403,'Only the host can configure AI opponents.');if(room.phase!=='waiting')throw new LobbyError(409,'Battle already started.');const bot=room.bots.find(b=>b.id===input.id);if(input.remove){if(!bot)throw new LobbyError(404,'AI opponent not found.');room.bots=room.bots.filter(b=>b!==bot);return{room:this.publicRoom(room)};}if(!bot&&room.members.length+room.bots.length>=6)throw new LobbyError(409,'Lobby is full (6 slots).');const p=this.profile({...input,name:input.name||'AI Commander'});if(!['easy','normal','hard','extreme'].includes(input.difficulty))throw new LobbyError(400,'Choose an AI difficulty.');if([...room.members,...room.bots].some(m=>m!==bot&&m.color===p.color))throw new LobbyError(409,'Choose a different banner color.');if(bot)Object.assign(bot,p,{difficulty:input.difficulty});else room.bots.push({...p,id:'ai-'+crypto.randomBytes(8).toString('hex'),ai:true,difficulty:input.difficulty,ready:true});return{room:this.publicRoom(room)};}
 if(input.action==='start'){if(!member.host)throw new LobbyError(403,'Only the host can start the battle.');if(room.phase!=='waiting'||room.members.length+room.bots.length<2||room.members.some(m=>!m.ready||Date.now()-m.lastSeen>6000))throw new LobbyError(409,'At least two players (human or AI) are required; all humans must be ready and connected.');if([...this.rooms.values()].filter(r=>r.phase==='playing').length>=6)throw new LobbyError(503,'All match slots are busy.');room.members.forEach((m,i)=>m.slot=i);const participants=[...room.members,...room.bots];participants.forEach((m,i)=>m.slot=i);room.engine=createEngine(participants,room.map);room.phase='playing';room.started=Date.now();return{room:this.publicRoom(room)};}
 if(input.action==='command'){if(room.phase!=='playing')throw new LobbyError(409,'No active battle.');if(!input.command||typeof input.command!=='object')throw new LobbyError(400,'Missing command.');const now=Date.now();if(now-(member.commandWindow||0)>1000){member.commandWindow=now;member.commands=0;}if(++member.commands>80)throw new LobbyError(429,'Too many commands.');const error=room.engine.apply(member.slot,input.command);if(error)throw new LobbyError(400,error);return{ok:true};}throw new LobbyError(400,'Unknown lobby action.');}
 step(dt=.05){const now=Date.now();for(const room of this.rooms.values()){if(now-room.created>3*60*60*1000){this.rooms.delete(room.code);continue;}if(room.engine)for(const m of room.members)if(!m.left&&now-m.lastSeen>90000){m.left=true;room.engine.eliminate(m.slot);}if(room.phase==='playing'){room.engine.step(dt);if(room.engine.state.ended)room.phase='finished';}else if(room.phase==='waiting'){room.members=room.members.filter(m=>now-m.lastSeen<90000);if(!room.members.some(m=>m.host)&&room.members[0])room.members[0].host=room.members[0].ready=true;}if(!room.members.some(m=>!m.left))this.rooms.delete(room.code);}for(const [ip,a]of this.attempts)if(now-a.since>60000)this.attempts.delete(ip);}
}
module.exports={LobbyService,LobbyError};
