'use strict';
// Atomic, private server checkpoints. Never accept authoritative states from clients.
const fs=require('node:fs'),path=require('node:path'),{createEngine}=require('./engine.cjs');
class MatchStore{
 constructor(directory){this.directory=directory;this.file=path.join(directory,'matches.json');this.pending=null;this.lastError=null;fs.mkdirSync(directory,{recursive:true,mode:0o700});}
 encode(service){return{version:1,at:Date.now(),rooms:[...service.rooms.values()].map(r=>({code:r.code,map:r.map,listed:r.listed===true,rules:r.rules,aiTakeover:r.aiTakeover===true,readyCheckDeadline:null,salt:r.salt.toString('base64'),password:r.password?.toString('base64')||null,members:r.members,spectators:r.spectators,bots:r.bots,created:r.created,phase:r.phase,started:r.started,checkpoint:r.engine?.checkpoint()}))};}
 async save(service){if(this.pending)return this.pending.then(()=>this.save(service));let body;try{body=JSON.stringify(this.encode(service));}catch(e){this.lastError=e.message;return false;}this.pending=(async()=>{const temporary=this.file+'.next';try{await fs.promises.writeFile(temporary,body,{mode:0o600});const handle=await fs.promises.open(temporary,'r+');try{await handle.sync();}finally{await handle.close();}await fs.promises.rename(temporary,this.file);this.lastError=null;return true;}catch(e){this.lastError=e.message;console.error('Match checkpoint failed:',e.code||'storage error');return false;}finally{this.pending=null;}})();return this.pending;}
 load(service){if(!fs.existsSync(this.file))return 0;let data;try{if(fs.statSync(this.file).size>100*1024*1024)throw Error('Checkpoint too large');data=JSON.parse(fs.readFileSync(this.file,'utf8'));if(data.version!==1||!Array.isArray(data.rooms)||data.rooms.length>30)throw Error('Unsupported checkpoint');}catch(e){this.lastError=e.message;console.error('Match recovery failed:',e.message);return 0;}let restored=0;for(const r of data.rooms){try{if(Date.now()-r.created>3*3600000||!/^\w{7}$/.test(r.code)||!Array.isArray(r.members)||r.members.length>6||!Array.isArray(r.bots)||r.bots.length>6||r.members.length+r.bots.length>6)continue;const room={...r,salt:Buffer.from(r.salt,'base64'),password:r.password?Buffer.from(r.password,'base64'):null,spectators:r.spectators||[],recoveredAt:Date.now(),recovering:r.phase==='playing'};if(room.salt.length!==16||room.password&&room.password.length!==32)throw Error('Invalid lobby credentials');for(const m of [...room.members,...room.spectators])m.lastSeen=Date.now();if(r.checkpoint){room.engine=createEngine([...r.members,...r.bots],r.map,r.rules);room.engine.restore(r.checkpoint);}delete room.checkpoint;service.rooms.set(room.code,room);restored++;}catch(e){console.error('Skipped invalid match checkpoint:',e.message);}}return restored;}
}
module.exports={MatchStore};
